databendlabs/openraft

async-raft/src/core/append_entries.rs, async-raft/tests/fixtures/logging.rs, async-raft/tests/fixtures/mod.rs
before:
`ut{add_remove_voter}:initialize{members={0}}:call_core new`
after:
`ut#1{add_remove_voter}:initialize#10000000000004{members={0}}:call_core#10000000000005: new`
Having a span id in log makes it easier to filter a specific event.
---
- Improvement
=> refactor: record span id #xxx for logging

async-raft/src/core/admin.rs, async-raft/src/core/append_entries.rs, async-raft/src/core/mod.rs, async-raft/src/core/vote.rs, async-raft/src/metrics.rs, async-raft/src/raft.rs, async-raft/src/replication/mod.rs, async-raft/tests/client_writes.rs, memstore/src/lib.rs
=> refactor: reduce log output when integration test. "client_writes" fails if log outputs too many

.github/workflows/ci.yaml, .mergify.yml
=> ci: limit NO threads for test to 2, to reduce timeout caused by starving

.gitignore, openraft/src/core/client.rs, openraft/src/core/mod.rs, openraft/src/core/replication.rs, openraft/src/replication/mod.rs, openraft/tests/membership/t00_learner_restart.rs
Close #42 
Remove `RaftEvent::Replicate::entry`, add a new field `appended: LogId` instead.
=> refactor: remove RaftEvent::Replicate::entry

change-log.md, guide/src/cluster-controls.md, guide/src/delete_log.md, guide/src/dynamic-membership.md, guide/src/threading.md
=> fix some guide doc typo

.github/workflows/issue-cmds.yml
Currently, `xt0rted/slash-command-action` will fail when a non-matching comment is created. Refer to https://github.com/xt0rted/slash-command-action/issues/124. This pr skips the entire job if the comment does not match.
=> ci: skip slash-command-action if comment does not match

memstore/src/lib.rs, memstore/src/test.rs, openraft/src/core/admin.rs, openraft/src/core/append_entries.rs, openraft/src/core/install_snapshot.rs, openraft/src/core/mod.rs, openraft/src/storage.rs, openraft/src/store_ext.rs, openraft/tests/snapshot_overrides_membership.rs, openraft/tests/snapshot_uses_prev_snap_membership.rs
Goal: minimize the work for users to implement a correct raft application.
Now RaftStorage provides default implementations for `get_membership()`
and `last_membership_in_log()`.
These two methods just can be implemented with other basic user impl
methods.
- fix: #59
---
=> change: trait RaftStore: remove get_membership_config(), add last_membership_in_log() and get_membership() with default impl

memstore/src/lib.rs, openraft/src/storage.rs
Signed-off-by: grapebaba <281165273@qq.com>
**Checklist**
=> [#62]Make first_known_log_id default impl

openraft/tests/client_api/main.rs, openraft/tests/client_api/t10_client_writes.rs, openraft/tests/client_api/t20_client_reads.rs, openraft/tests/client_api/t50_lagging_network_write.rs
=> Refactor: move client-api tests to tests/client_api/

memstore/src/test.rs, openraft/src/core/mod.rs, openraft/src/storage.rs
=> Refactor: use read_hard_state() to check hard state in storage test

memstore/Cargo.toml, memstore/src/lib.rs, openraft/Cargo.toml, openraft/src/core/admin.rs, openraft/src/core/append_entries.rs, openraft/src/core/client.rs, openraft/src/core/install_snapshot.rs, openraft/src/core/mod.rs, openraft/src/core/replication.rs, openraft/src/core/vote.rs, openraft/src/error.rs, openraft/src/lib.rs, openraft/src/metrics.rs, openraft/src/metrics_wait_test.rs, openraft/src/raft.rs, openraft/src/storage_error.rs, openraft/tests/api_install_snapshot.rs, openraft/tests/metrics/t40_metrics_wait.rs
- Add: Fatal as a collection of all errors that will shutdown a raft
node. Currently it has only one sub-error: StorageError.
- Add: error types for every API, such as AppendEntriesError or
VoteError.
- Remove: `map_storage_error()` and `map_fatal_storage_error()`.
A fatal error should be popped up and be dealt with at the top level.
Avoid changing target state everywhere, which is hard to review or
debug.
- Use crate anyerror as a wrapper of external error.
- Remove: RaftError, which is vague about what it is for.
- Makes API error serializable for transport.
---
=> Refactor: error system; add Fatal and API errors

openraft/src/core/append_entries.rs, openraft/src/core/mod.rs
Problem:
A follower saves hard state `(term=msg.term, voted_for=None)`
when a `msg.term > local.term` when handling append-entries RPC.
This is quite enough to be correct but not perfect. Correct because:
- In one term, only an established leader will send append-entries;
- Thus, there is a quorum voted for this leader;
- Thus, no matter what `voted_for` is saved, it is still correct. E.g.
when handling append-entries, a follower node could save hard state
`(term=msg.term, voted_for=Some(ANY_VALUE))`.
The problem is that a follower already knows the legal leader for a term
but still does not save it. This leads to an unstable cluster state: The
test sometimes fails.
Solution:
A follower always save hard state with the id of a known legal leader.
---
- fix: #5
=> Fix: save leader_id if a higher term is seen when handling append-entries RPC

guide/src/dynamic-membership.md, openraft/src/membership/membership.rs, openraft/src/membership/membership_test.rs
Define extended change-membership safety.
With this definition raft membership management becomes more flexible.
Joint-uniform-joint-... wont be the only choice.
---
=> Feature: Membership::is_safe_to() check membership change safety

openraft/tests/client_api/main.rs, openraft/tests/client_api/t30_stepdown.rs
in https://github.com/datafuselabs/openraft/issues/58, within CI if some task is delayed a new round of election will be fired,so use a bigger timeout in this test to avoid new election timeout.
also,move stepdown to client_api unit tests.
=> Fix: fix stepdown CI run fail by use a bigger election timeout

openraft/src/metrics.rs, openraft/src/metrics_wait_test.rs, openraft/tests/client_api/t30_stepdown.rs, openraft/tests/fixtures/mod.rs
- Feature: add Metrix.Wait().log_at_least() to wait for last and applied
log index to become equal or greater than specified value.
- In test "stepdown", the last log index of a non-leader node in the old
cluster is unstable: because when change-membership, the second log
just need the new cluster quorum to commit.
Thus there is chance a node in old cluster does not have this log.
The check on this value should be loosened: replace `Wait().log()`
with `Wait().log_at_least()`.
---
=> Refactor: loosen state check in test "stepdown"

openraft/tests/append_entries/main.rs, openraft/tests/append_entries/t50_append_entries_with_bigger_term.rs, openraft/tests/fixtures/mod.rs
Fix: add unit test for save leader_id if a higher term is seen when handling append-entries RPC, related to pr https://github.com/datafuselabs/openraft/pull/95
=> Fix: add unit test for save leader_id if a higher term is seen when handling append-entries RPC

memstore/src/test.rs, openraft/src/storage.rs
=> Fixup: first_known_log_id() should return first in in log if last_applied is None

openraft/src/core/client.rs, openraft/src/raft.rs, openraft/tests/fixtures/mod.rs
=> Refactor: use Membership to check commit condition before replication

memstore/src/lib.rs, memstore/src/test.rs, openraft/src/core/append_entries.rs, openraft/src/core/client.rs, openraft/src/core/install_snapshot.rs, openraft/src/core/mod.rs, openraft/src/raft_types.rs, openraft/src/replication/mod.rs, openraft/src/storage.rs, openraft/src/store_ext.rs, openraft/tests/fixtures/mod.rs, openraft/tests/log_compaction/compaction.rs
- `get_initial_state()` does not need to return None any more.
Because the fields in it can be None.
E.g. `last_membership` is None and it leaves the job building a
default membership to its caller.
- Before this patch `get_initial_state()` returns None for
`last_log_id`, when hard state is not found.
Now it just returns the actual value of `last_log_id`, even though
that logs without hard state is not possible.
---
=> Feature: add default impl for RaftStorage::get_initial_state()

memstore/src/lib.rs, openraft/src/core/admin.rs, openraft/src/core/append_entries.rs, openraft/src/core/install_snapshot.rs, openraft/src/core/mod.rs, openraft/src/core/replication.rs, openraft/src/core/startup_test.rs, openraft/src/core/vote.rs, openraft/src/defensive.rs, openraft/src/replication/mod.rs, openraft/src/storage.rs, openraft/src/storage_error.rs, openraft/src/store_ext.rs, openraft/src/store_wrapper.rs, openraft/src/testing/suite.rs, openraft/tests/fixtures/mod.rs
-   Change: `get_log_state()` returns the `last_purged_log_id` instead of the `first_log_id`.
Because there are some cases in which log are empty:
When a snapshot is install that covers all logs,
or when `max_applied_log_to_keep` is 0.
Returning `None` is not clear about if there are no logs at all or
all logs are deleted.
In such cases, raft still needs to maintain log continuity
when repilcating. Thus the last log id that once existed is important.
Previously this is done by checking the `last_applied_log_id`, which is
dirty and buggy.
Now an implementation of `RaftStorage` has to maintain the
`last_purged_log_id` in its store.
-   Change: Remove `first_id_in_log()`, `last_log_id()`, `first_known_log_id()`,
because concepts are changed.
-   Change: Split `delete_logs()` into two method …
=> Change: RaftStorage::get_log_state() returns last purge log id

memstore/src/lib.rs, openraft/src/core/mod.rs, openraft/src/core/vote.rs, openraft/src/metrics.rs, openraft/src/metrics_wait_test.rs, openraft/tests/membership/main.rs, openraft/tests/membership/t16_change_membership_cases.rs, openraft/tests/membership/t30_step_down.rs
A Candidate should check if it is the only member in a cluster before
sending vote request.
Otherwise a single node cluster does work.
- Change: `Wait::log_at_least()` use `Option<u64>` instead of u64 for log index.
---
=> Fix: a single Candidate should be able to vote itself.

openraft/src/core/admin.rs, openraft/src/core/append_entries.rs, openraft/src/error.rs, openraft/src/lib.rs, openraft/src/network.rs, openraft/src/replication/mod.rs, openraft/src/storage_error.rs
- Add sub errors such as Timeout and NetworkError.
- Remove ReplicationError::IO, use StorageError instead.
- Cleanup finished TODOs.
---
=> Change: add sub error types of ReplicationError

openraft/src/core/client.rs, openraft/src/error.rs, openraft/src/lib.rs, openraft/src/network.rs, openraft/src/replication/mod.rs, openraft/tests/fixtures/mod.rs
- When a remote error encountered when replication, the replication will
be stopped at once.
- Fix: #140
---
=> Change: RaftNetwork return `RPCError` instead of anyhow::Error

openraft/src/core/vote.rs, openraft/tests/membership/t16_change_membership_cases.rs
When a Candidate saw a higher vote, it store it at once.
Then no more further granted votes are valid to this candidate,
because vote they granted are changed.
Thus it was wrong to compare `last_log_id` before decide if to revert to
Follower.
The right way is to revert to Follower at once and stop the voting
procedure.
The test `leader_metrics()` sometimes fails because of this bug.
---
=> Fix: a Candidate should revert to Follower at once when a higher vote is seen

openraft/tests/membership/t16_change_membership_cases.rs
This is normal but sometimes fails the test.
Loosen the condition check: allows a node in the old cluster to stay in
Candidate state.
---
=> Refactor: in membership test, there is a chance a node has no 2nd change-membership log keeps electing

example-raft-kv/Cargo.toml, example-raft-kv/README.md, example-raft-kv/src/bin/main.rs, example-raft-kv/src/client.rs, example-raft-kv/src/lib.rs, example-raft-kv/src/network/api.rs, example-raft-kv/src/network/management.rs, example-raft-kv/tests/cluster/main.rs, example-raft-kv/tests/cluster/test_cluster.rs, openraft/src/error.rs, openraft/src/replication/mod.rs
Add raft client in rust `ExampleClient` to show how to talk to a raft
cluster.
It implements 2 application APIs and several administrative APIs for managing or
monitor a raft cluster.
This client also shows how to deal `ForwardToLeader` error when a
**write** request is sent to a non-leader.
Also a new demo `test_cluster.rs` of how to set up a raft cluster with `ExampleClient` is
added.
Other modification:
- All API replies are made into a uniform form: `Result<T, E>`.
- `openraft` adds new error `NodeNotFound` and `Infallible`.
- fix: #158
---
=> Feature: add ExampleClient to example-raft-kv

openraft/tests/fixtures/mod.rs
RaftRouter does not have to use `tokio::sync::RwLock` for routing_table and isolated_nodes.
`std::sync::Mutex` is good enough.
issue: https://github.com/datafuselabs/openraft/issues/165
**Checklist**
=> Refactor: use std::sync::Mutex for routing_table and isolated_nodes

openraft/src/raft.rs, openraft/tests/client_api/t10_client_writes.rs, openraft/tests/client_api/t20_client_reads.rs, openraft/tests/concurrent_write_and_add_learner.rs, openraft/tests/fixtures/mod.rs, openraft/tests/membership/t10_add_learner.rs, openraft/tests/membership/t16_change_membership_cases.rs, openraft/tests/membership/t25_elect_with_new_config.rs, openraft/tests/membership/t30_step_down.rs, openraft/tests/metrics/t10_current_leader.rs
=> Refactor: openraft tests: remove async if a method is sync.

example-raft-kv/Cargo.toml, memstore/Cargo.toml, openraft/Cargo.toml
=> Refactor: update anyerror to 0.1.4: by default do not generate backtrace. It can be very slow: 500ms

openraft/Cargo.toml, openraft/src/core/mod.rs, openraft/src/metrics.rs, openraft/src/metrics_wait_test.rs, openraft/src/raft.rs
The two commits address the unnecessary allocation of message summary for each message passed via Raft and unnecessary allocations of membership infos before publishing metrics.
This alone improved the performance (in ops/second) of an empty Raft with a dummy state machine by about 40%.
=> Remove some overhead caused by unnecessary memory allocations (improving performance by 40%)

openraft/src/core/admin.rs, openraft/src/core/mod.rs, openraft/src/raft_types.rs, openraft/src/testing/suite.rs, openraft/src/vote/vote.rs
Note: It would be ideal to wrap NodeId into a newtype to prevent wrong usage in the future, but that's a breaking change.
Further, NodeId should ideally be a generic argument of Raft type, but that's even bigger breaking change.
The fix in `suite.rs` is not perfect, since it's still using a literal (as are all the tests).
This change is in preparation for another PR that introduces a possibility to use `NodeId` as a GUID/128-bit entity (e.g., you could also code IPv6 address there directly).
=> Fix: Use NodeId where NodeId is meant, not u64

openraft/src/core/admin.rs, openraft/src/core/client.rs, openraft/src/core/mod.rs, openraft/src/core/vote.rs, openraft/src/raft.rs, openraft/src/replication/mod.rs
Currently, traced node IDs are used directly, which works, since `NodeId` is a `u64`. If the `NodeId` is anything more complex, the formatting will fail. Use `Display` trait to format the `NodeId` in trace messages to allow replacing `NodeId` with a different type.
Note: This subsumes https://github.com/datafuselabs/openraft/pull/190, only look at the second commit.
=> Change: Format NodeId using `Display` for tracing

openraft/src/core/admin.rs, openraft/src/core/mod.rs, openraft/src/core/replication.rs, openraft/src/replication/mod.rs, openraft/tests/metrics/t30_leader_metrics.rs
Replication metrics were cloned for each leader metrics update. This is not necessary. Instead, keep a hashmap of replication metrics with *atomic* indices of matching log on individual replicas. Only if anything else changes clone the map.
The change improves the performance of the empty Raft benchmark by about 5% by reducing reallocations of the replication metrics.
Further improvement could be made by reducing the number of atomic operations on the `Arc` backing the `LeaderMetrics`, but that's likely not worth it as of now.
NOTE: This change slightly changes the API of `ReplicationMetrics`. Previously, public access was given to the member `matched`. Now, the member access was replaced with a method `matched()` and a constructor to construct the object. I.e., any user of the …
=> Change: Do not copy replication metrics over and over

example-raft-kv/src/bin/main.rs, example-raft-kv/src/client.rs, example-raft-kv/src/lib.rs, example-raft-kv/src/network/raft.rs, example-raft-kv/src/network/raft_network_impl.rs, example-raft-kv/src/store/mod.rs, memstore/src/lib.rs, openraft/src/core/admin.rs, openraft/src/core/append_entries.rs, openraft/src/core/client.rs, openraft/src/core/install_snapshot.rs, openraft/src/core/mod.rs, openraft/src/core/replication.rs, openraft/src/core/vote.rs, openraft/src/defensive.rs, openraft/src/lib.rs, openraft/src/network.rs, openraft/src/raft.rs, openraft/src/replication/mod.rs, openraft/src/storage.rs, openraft/src/store_ext.rs, openraft/src/store_wrapper.rs, openraft/src/testing/store_builder.rs, openraft/src/testing/suite.rs, openraft/tests/append_entries/t10_conflict_with_empty_entries.rs, openraft/tests/append_entries/t20_append_conflicts.rs, openraft/tests/append_entries/t50_append_entries_with_bigger_term.rs, openraft/tests/fixtures/mod.rs
Currently only the request and response type are configured, but other types can be now easily configured as well, such as `NodeId` (to be done in the next change) or `Runtime`.
Storage and network factory types are still provided as a separate type, since otherwise it would be hard to provide storage wrappers for testing.
This addresses https://github.com/datafuselabs/openraft/issues/204.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/211)
=> Change: Use a `RaftConfig` trait to configure common types

.github/workflows/pages.yaml, openraft/src/replication/mod.rs, openraft/tests/append_entries/main.rs, openraft/tests/append_entries/t90_issue_216_stale_last_log_id.rs
- fix: #216
---
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/214)
=> Fix: consistency issue between ReplicationCore.last_log_id and last_log_state.last_log_id

openraft/src/raft_types.rs, openraft/src/replication/mod.rs, openraft/src/vote/leader_id.rs, openraft/src/vote/leader_id_test.rs, openraft/src/vote/vote.rs
@schreter 
What about avoiding using `RaftTypeConfig` if possible?
For some of the basic type such as `LogId` and `LeaderId`, it seems a trait bound `NodeId` is quite enough:
```rust
#[derive(Debug, Default, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
// Clear the bound so that serde will generate required bounds.
#[serde(bound = "")]
pub struct LeaderId<NID>
where NID: NodeId
{
pub term: u64,
pub node_id: NID,
}
```
It seems working for now, 
But I do not know if there are any concerns in the future we will have to use `RaftTypeConfig` for these basic types.
---
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/221)
=> Refactor: replace the trait bound RaftTypeConfig of LeaderId with NodeId

.gitignore, example-raft-kv/src/client.rs, example-raft-kv/src/lib.rs, example-raft-kv/src/network/api.rs, example-raft-kv/tests/cluster/test_cluster.rs, guide/src/architecture.md, openraft/src/core/append_entries.rs, openraft/src/core/client.rs, openraft/src/core/mod.rs, openraft/src/error.rs, openraft/src/raft.rs, openraft/tests/append_entries/t60_large_heartbeat.rs, openraft/tests/client_api/t20_client_reads.rs, openraft/tests/fixtures/mod.rs, openraft/tests/singlenode.rs
1. Refactor: add consistent_read in example base on `is_leader` API to provide consistent read from statemacine"
2. rename API `client_read` to `is_leader`.
3. update gitignore file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/218)
=> Refactor: add consistent_read in example base on client_read API to provide consistent read from statemacine

example-raft-kv/src/store/mod.rs, memstore/src/lib.rs, openraft/src/core/admin.rs, openraft/src/core/append_entries.rs, openraft/src/core/mod.rs, openraft/src/core/replication.rs, openraft/src/core/replication_state_test.rs, openraft/src/defensive.rs, openraft/src/error.rs, openraft/src/metrics.rs, openraft/src/raft.rs, openraft/src/raft_types.rs, openraft/src/replication/mod.rs, openraft/src/storage.rs, openraft/src/storage_error.rs, openraft/src/store_ext.rs, openraft/tests/fixtures/mod.rs
- #222 
---
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/224)
=> Refactor: LogId only needs a generic NodeId, not all of the RaftTypeConfig

openraft/src/core/replication.rs, openraft/src/replication/mod.rs, openraft/tests/metrics/t30_leader_metrics.rs
commit-id:79a9ac46
---
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/232)
=> Refactor: ReplicationMetrics.matched does not need to be an Option. A `LogId` is just enough

openraft/src/core/admin.rs, openraft/src/core/mod.rs, openraft/src/core/replication.rs, openraft/src/leader_metrics.rs, openraft/src/leader_metrics_test.rs, openraft/src/lib.rs, openraft/src/metrics.rs, openraft/src/replication/mod.rs, openraft/src/versioned/mod.rs, openraft/src/versioned/versioned.rs, openraft/tests/append_entries/t90_issue_216_stale_last_log_id.rs, openraft/tests/metrics/t30_leader_metrics.rs
- Add `Versioned<D>` to track changes of an `Arc<D>`.
In openraft, some frequently updated object such metrics are wrapped
in an `Arc`, and some modification is made in place: by storing an
`AtomicU64`.
Thus we can not tell whether an `Arc<D>` is changed by comparing them
with `==` any more.
In order to determine whether to broadcast a metrics instance, we need
an additional `version` to track the changes applied to the `Arc<D>`.
These are all included in the `Versioned<D>`.
- Add trait `Update` to define variant update operation to apply to
`Versioned<D>`.
`Update` has to implement two methods:
- `apply_in_place()` to apply a modification in place if possible
- and `apply_mut()` if it has to apply modification to a cloned
instance.
`Update` will increment the `Versioned.version` by 1 …
=> Feature: use a version to track metics change

openraft/tests/append_entries/t90_issue_216_stale_last_log_id.rs
commit-id:a8e61520
---
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/236)
=> Test: disable stale_last_log_id(), very easy to get timeout

openraft/src/core/mod.rs, openraft/src/leader_metrics.rs, openraft/src/leader_metrics_test.rs, openraft/src/metrics.rs, openraft/src/replication/mod.rs
commit-id:e8bb9b9e
commit-id:484fe19d
---
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/237)
=> Refactor: replace generic type RaftTypeConfig with NodeId if possible

openraft/src/node.rs
By mistake, a temporary `From<u64>` requirement on `NodeId` type was left in the code, which was intended to make tests run.
The requirement was properly removed from the `NodeId` trait, but not from the requirements on `T` needed to default-implement the `NodeId`.
Remove this requirement.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/238)
=> Fix: Remove `From<u64>` from default-implemented `NodeId`

openraft/src/core/mod.rs, openraft/src/raft.rs, openraft/tests/fixtures/mod.rs, openraft/tests/initialization.rs
This addresses #234
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/239)
=> Feature: Add support for external requests to be executed inside of Raft core loop

openraft/src/core/append_entries.rs, openraft/src/core/install_snapshot.rs, openraft/src/core/mod.rs, openraft/src/lib.rs, openraft/src/raft_types.rs, openraft/tests/append_entries/t40_append_updates_membership.rs, openraft/tests/membership/t10_add_learner.rs, openraft/tests/membership/t20_change_membership.rs, openraft/tests/singlenode.rs
Refactor: optimize `report_metrics` call, avoids call this function everywhere
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/242)
=> Refactor: optimize `report_metrics` call, avoids call this function everywhere

.github/workflows/ci.yaml
---
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/257)
=> CI: move example-test and lint out of unit-test

.github/workflows/ci.yaml, Makefile, example-raft-kv/src/store/mod.rs, memstore/src/lib.rs, memstore/src/test.rs, openraft/src/core/admin.rs, openraft/src/core/append_entries.rs, openraft/src/core/client.rs, openraft/src/core/install_snapshot.rs, openraft/src/core/mod.rs, openraft/src/core/replication.rs, openraft/src/core/vote.rs, openraft/src/defensive.rs, openraft/src/error.rs, openraft/src/membership/membership.rs, openraft/src/membership/membership_test.rs, openraft/src/metrics.rs, openraft/src/raft.rs, openraft/src/replication/mod.rs, openraft/src/storage.rs, openraft/src/storage_error.rs, openraft/src/store_ext.rs, openraft/src/testing/suite.rs, openraft/src/vote/vote.rs
- Change: from `DefensiveError<C: RaftTypeConfig>` to `DefensiveError<NID: NodeId>`
- Change: from `ErrorSubject<C: RaftTypeConfig>` to `ErrorSubject<NID: NodeId>`
- Change: from `Membership<C: RaftTypeConfig>` to `Membership<NID: NodeId>`
- Change: from `MissingNodeInfo<C: RaftTypeConfig>` to `MissingNodeInfo<NID: NodeId>`
- Change: from `SnapshotMeta<C: RaftTypeConfig>` to `SnapshotMeta<NID: NodeId>`
- Change: from `StorageError<C: RaftTypeConfig>` to `StorageError<NID: NodeId>`
- Change: from `StorageIOError<C: RaftTypeConfig>` to `StorageIOError<NID: NodeId>`
- Change: from `Violation<C: RaftTypeConfig>` to `Violation<NID: NodeId>`
- Change: from `Vote<C: RaftTypeConfig>` to `Vote<NID: NodeId>`
- CI: lint example-raft-kv
---
--- …
=> Change: use NodeId instead of RaftTypeConfig if a type only needs node-id as type param.

openraft/src/core/append_entries.rs, openraft/src/core/mod.rs, openraft/src/membership/membership.rs, openraft/src/metrics.rs, openraft/src/storage.rs, openraft/tests/fixtures/mod.rs
---
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/264)
=> Refactor: let the initial effective membership be an empty set

example-raft-kv/src/store/mod.rs, memstore/src/lib.rs, openraft/src/core/admin.rs, openraft/src/core/append_entries.rs, openraft/src/core/install_snapshot.rs, openraft/src/core/mod.rs, openraft/src/metrics_wait_test.rs, openraft/src/storage.rs, openraft/src/store_ext.rs, openraft/src/testing/suite.rs, openraft/tests/initialization.rs, openraft/tests/membership/t10_add_learner.rs, openraft/tests/snapshot/snapshot_overrides_membership.rs, openraft/tests/snapshot/snapshot_uses_prev_snap_membership.rs, openraft/tests/state_machine/t20_state_machine_apply_membership.rs
The value of membership config of an uninitialized raft-node should be:
```rust
EffectiveMembership {
log_id: None,
membership: Membership::default(),
}
```
I.e., there is always a membership config for either an initialized or
an uninitialized raft-node.
Because `EffectiveMembership` is not a value that could be `None`, but it is more like a container of values.
Changed struct:
```rust
struct InitialState {
pub last_membership: EffectiveMembership<C>,
...
}
```
Changed methods:
```rust
RaftStorage::get_membership() -> Result<EffectiveMembership<C>, _>;
RaftStorage::last_applied_state() -> Result<(_, EffectiveMembership<C>), _>;
```
---
--- …
=> Change: RaftStorage: use `EffectiveMembership` instead of `Option<_>`

example-raft-kv/src/client.rs, example-raft-kv/tests/cluster/test_cluster.rs, openraft/src/core/admin.rs, openraft/src/core/mod.rs, openraft/src/core/replication.rs, openraft/src/error.rs, openraft/src/raft.rs, openraft/tests/fixtures/mod.rs, openraft/tests/membership/t20_change_membership.rs
Changed Errors type parameter from `RaftTypeConfig` to `NodeId`:
- `AddLearnerError<NodeId>`
- `ChangeMembershipError<NodeId>`
- `ForwardToLeader<NodeId>`
- `InProgress<NodeId>`
- `LearnerIsLagging<NodeId>`
- `LearnerNotFound<NodeId>`
---
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/267)
=> Change: learner-related errors do not need RaftTypeConfig

example-raft-kv/src/client.rs, openraft/src/core/admin.rs, openraft/src/core/mod.rs, openraft/src/core/replication.rs, openraft/src/raft.rs, openraft/tests/fixtures/mod.rs, openraft/tests/membership/t16_change_membership_cases.rs
- `AddLearnerResponse<NodeId>`
- `ChangeMembers<NodeId>`
---
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/268)
=> Change: AddLearnerResponse and ChangeMembers do not need RaftTypeConfig

guide/src/cluster-formation.md, openraft/src/core/admin.rs, openraft/src/core/mod.rs, openraft/src/error.rs, openraft/src/raft_types.rs, openraft/src/storage.rs
- Feature: add error `NotAllowed{last_log_id, vote}` to explain why
initialization is now allowed.
- Doc: explain the conditions to satisfied to initialize.
---
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/269)
=> Feature: add error NotAllowed

openraft/src/storage.rs, openraft/src/testing/suite.rs
---
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/274)
=> Change: InitialState use NodeId as type param instead of RaftTypeConfig

example-raft-kv/src/client.rs, example-raft-kv/src/network/api.rs, example-raft-kv/src/network/raft_network_impl.rs, openraft/src/core/admin.rs, openraft/src/core/append_entries.rs, openraft/src/core/client.rs, openraft/src/core/install_snapshot.rs, openraft/src/core/mod.rs, openraft/src/core/vote.rs, openraft/src/error.rs, openraft/src/network.rs, openraft/src/raft.rs, openraft/tests/fixtures/mod.rs
- `InitializeError`
- `ClientWriteError`
- `CheckIsLeaderError`
- `AppendEntriesError`
- `VoteError`
- `InstallSnapshotError`
---
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/275)
=> Change: errors that only need NodeId instead of RaftTypeConfig as type param

example-raft-kv/src/network/raft_network_impl.rs, openraft/src/core/append_entries.rs, openraft/src/core/install_snapshot.rs, openraft/src/core/vote.rs, openraft/src/network.rs, openraft/src/raft.rs, openraft/tests/fixtures/mod.rs
- `AppendEntriesResponse`
- `VoteResponse`
- `InstallSnapshotResponse`
---
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/276)
=> Change: response types that only need NodeId instead of RaftTypeConfig as type param

openraft/src/core/admin.rs, openraft/src/core/client.rs, openraft/src/core/mod.rs, openraft/src/core/replication.rs
It does not need to cache the entry, only the response tx.
Log entry can be fetched from storage by index.
Only tx channels for sending back result to client are stored and are
indexed by log-index.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/278)
=> rename RaftMetrics.leader_metrics to replication

openraft/src/core/admin.rs, openraft/src/core/client.rs, openraft/src/core/mod.rs, openraft/src/metrics/raft_metrics.rs, openraft/src/metrics/wait_test.rs, openraft/tests/metrics/t30_leader_metrics.rs
- part of #229
---
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/279)
=> Refactor: replicate_client_request() does not need an entry, only log_id

openraft/src/core/admin.rs, openraft/src/core/client.rs
Installing callback is not a job of `replicate_client_request()`.
---
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/280)
=> Refactor: move installation of client resp callback out of `replicate_client_request()`

openraft/src/testing/suite.rs
Signed-off-by: MrCroxx <mrcroxx@outlook.com>
A small fix for #282 . Make test log indices continuous to prevent from causing log gaps.
**Checklist**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/283)
=> Fix: continuous index in test suit last_membership_in_log

openraft/src/core/admin.rs, openraft/src/core/append_entries.rs, openraft/src/core/client.rs, openraft/src/core/install_snapshot.rs, openraft/src/core/leader_state.rs, openraft/src/core/learner_state.rs, openraft/src/core/mod.rs, openraft/src/core/raft_core.rs, openraft/src/core/replication.rs, openraft/src/core/vote.rs, openraft/src/engine.rs, openraft/src/entry.rs, openraft/src/lib.rs, openraft/src/runtime/mod.rs, openraft/src/storage.rs
`Engine` implement raft algorithm and stores a `state` in it which
contains just enough information to run raft.
It does not contain any application related data, such as `AppData` or
`AppDataResponse`.
`Engine` receives events, deals with them, then output several
`Command` that a `Runtime` executes them to update the application
state, such as push log entries into `RaftStorage`.
`RaftCore` is a `RaftRuntime` impl.
`LeaderState`, `FollowerState` and so on are **wrapper** Runtime.
A `RaftRuntime` talks to `RaftStorage` and `RaftNetwork` to get things done.
The workflow of writing something through raft protocol with engine and runtime would be like
this:
```text
Client                    Engine                         Runtime      Storage      Netwoork
|                         | …
```
=> Refactor: Engine impl raft, Runtime execute commands

openraft/src/engine.rs, openraft/tests/append_entries/t30_append_inconsistent_log.rs, openraft/tests/append_entries/t60_large_heartbeat.rs, openraft/tests/append_entries/t90_issue_216_stale_last_log_id.rs, openraft/tests/client_api/t20_client_reads.rs, openraft/tests/concurrent_write_and_add_learner.rs, openraft/tests/fixtures/mod.rs, openraft/tests/membership/t00_learner_restart.rs, openraft/tests/membership/t10_add_learner.rs, openraft/tests/membership/t15_add_remove_follower.rs, openraft/tests/membership/t16_change_membership_cases.rs, openraft/tests/membership/t20_change_membership.rs, openraft/tests/membership/t25_elect_with_new_config.rs, openraft/tests/membership/t30_step_down.rs, openraft/tests/membership/t40_removed_follower.rs, openraft/tests/metrics/t20_metrics_state_machine_consistency.rs, openraft/tests/metrics/t30_leader_metrics.rs, openraft/tests/metrics/t40_metrics_wait.rs, openraft/tests/singlenode.rs, openraft/tests/state_machine/t10_total_order_apply.rs, openraft/tests/state_machine/t20_state_machine_apply_membership.rs
- Refactor: `TypedRaftRouter::wait()` does not need to be async
- Refactor: remove `TypedRaftRouter::initialize_with()`: without this
wrapper it is much simpler.
- Fix: Test: `metrics_state_machine_consistency()` used wrong `log_index`.
---
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/289)
=> Refactor: simplify TypedRaftRouter

openraft/src/engine/engine.rs, openraft/src/engine/initialize_test.rs, openraft/src/engine/mod.rs, openraft/src/error.rs, openraft/src/raft_types.rs, openraft/tests/initialize/t20_initialization.rs
- Change: fix error usage for `initialize()`: new error to return:
NotAMembershipEntry and NotInMembers;
MissingNodeInfo should not be returned when the node to initialize is
not a member.
- Refactor: move engine to dir engine/
- Test: add engine test for `Engine::initialize()`
- part of #292
---
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/295)
=> Feature: add err: NotAMembershipEntry, NotInMembers

openraft/src/core/admin.rs, openraft/src/engine/engine.rs, openraft/src/engine/initialize_test.rs, openraft/src/membership/membership.rs, openraft/src/storage.rs
- Feature: impl TryFrom<BTreeMap> for Membership.
- part of #292
---
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/296)
=> Refactor: Engine::initialize() sets server state to Candidate

example-raft-kv/src/network/raft.rs, example-raft-kv/src/network/raft_network_impl.rs, openraft/src/core/vote.rs, openraft/src/network.rs, openraft/src/raft.rs, openraft/tests/fixtures/mod.rs
---
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/308)
=> Change: VoteRequest does not need type param RaftTypeConfig. Only NodeId

openraft/src/core/admin.rs, openraft/src/core/learner_state.rs, openraft/src/core/raft_core.rs, openraft/src/engine/engine.rs, openraft/src/engine/initialize_test.rs
---
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/309)
=> Refactor: Engine does not set metrics_flags one by one. metrics changes can be extracted from the engine output commands

openraft/src/engine/initialize_test.rs, openraft/src/engine/mod.rs, openraft/src/engine/testing.rs
---
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/310)
=> Refactor:  move engine test supporting types to engine::testing

openraft/src/core/follower_state.rs, openraft/src/core/internal_msg.rs, openraft/src/core/leader_state.rs, openraft/src/core/learner_state.rs, openraft/src/core/mod.rs, openraft/src/core/raft_core.rs, openraft/src/core/snapshot_state.rs, openraft/src/runtime/mod.rs
Election does not need to create a channel to collect vote responses.
We create an internal channel `rx_internal` for all kinds of internal
communication.
- Refactor: avoid potential recursive call of `run_engine_commands()`.
E.g., do not wait for external event inside `run_engine_commands()`.
Because most external event handler(e.g., a timer for a new round
election) will call an Engine event handler(such as `Engine::elect()`)
with a following `run_engine_commands()`.
Recursive call to `run_engine_commands()` may cause a unexpected order
of cammand execution.
---
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/312)
=> Refactor: using a universal receiver for internal messaging

openraft/src/core/install_snapshot.rs, openraft/src/core/mod.rs, openraft/src/core/raft_core.rs
A local log that is included in snapshot may be inconsistent with the leader.
It has to purge all of them to prevent these log form being replicated, when this node becomes leader.
When deleting these logs, it does not need to consider the `max_applied_log_to_keep` config.
Thus `purge_applied_logs()` does not need to deal with the condition
that `last_log_id` is inconsistent with `last_applied`.
---
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/323)
=> Refactor: when installing snapshot, delete logs included in snapshot

openraft/src/core/admin.rs, openraft/src/core/append_entries.rs, openraft/src/core/client.rs, openraft/src/core/install_snapshot.rs, openraft/src/core/leader_state.rs, openraft/src/core/raft_core.rs, openraft/src/core/replication.rs, openraft/src/engine/elect_test.rs, openraft/src/engine/engine_impl.rs, openraft/src/engine/handle_vote_req_test.rs, openraft/src/engine/handle_vote_resp_test.rs, openraft/src/engine/initialize_test.rs, openraft/src/lib.rs, openraft/src/membership/membership_state.rs, openraft/src/membership/mod.rs, openraft/src/raft_state.rs, openraft/src/storage.rs, openraft/src/testing/suite.rs, openraft/tests/membership/t10_add_learner.rs, openraft/tests/snapshot/snapshot_overrides_membership.rs, openraft/tests/snapshot/snapshot_uses_prev_snap_membership.rs
A raft node needs to store at most 2 membership config log:
- The first one must be committed, because
(1): raft allows to propose new membership only when the previous one is committed.
- The second may be committed or not.
By (1) we have:
(2) there is at most one outstanding, uncommitted membership log. On
either leader or follower, the second last one must be committed.
A committed log must be consistent with the leader.
(3) By raft design, the last membership takes effect.
When handling append-entries RPC:
(4) a raft follower will delete logs that are inconsistent with the leader.
By (3) and (4), a follower needs to revert the effective membership to the previous one.
By (2), a follower only need to revert at most one membership log.
Thus a raft node will only need to store at most …
=> Change: RaftState tracks last 2 membership configs

example-raft-kv/src/store/mod.rs, memstore/src/lib.rs, openraft/src/storage.rs, openraft/src/testing/suite.rs, openraft/tests/api_install_snapshot.rs
Raft actually has two slots of logs: the membership log and the application log.
In order to simplify the design and implementation, raft stores these two slots of logs in one slot.
A log snapshot, should contain the information about these two slots:
- last applied business log: `last_applied`,
- and last applied membership log: `last_applied_membership`, which is not included in `SnapshotMeta` and should be added.
With `last_applied_membership`, the `Engine` will be able to handle the install-snapshot event without accessing the `RaftStorage`.
- Fix: #334
---
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/335)
=> Change: add `last_membership` to `SnapshotMeta`

example-raft-kv/src/client.rs, example-raft-kv/src/network/raft_network_impl.rs, openraft/src/error.rs, openraft/src/network.rs, openraft/src/replication/mod.rs, openraft/tests/fixtures/mod.rs
Changed error: RPCError, ReplicationError,  HigherVote, LackEntry, Timeout, RemoteError.
---
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/336)
=> Change: error generic param does not need to be RaftTypeConfig, NodeId is enough.

openraft/tests/append_entries/t30_append_inconsistent_log.rs, openraft/tests/append_entries/t60_large_heartbeat.rs, openraft/tests/append_entries/t90_issue_216_stale_last_log_id.rs, openraft/tests/fixtures/mod.rs, openraft/tests/membership/t00_learner_restart.rs, openraft/tests/membership/t10_add_learner.rs, openraft/tests/membership/t15_add_remove_follower.rs, openraft/tests/membership/t16_change_membership_cases.rs, openraft/tests/membership/t20_change_membership.rs, openraft/tests/membership/t30_step_down.rs, openraft/tests/membership/t40_removed_follower.rs, openraft/tests/metrics/t20_metrics_state_machine_consistency.rs, openraft/tests/metrics/t30_leader_metrics.rs, openraft/tests/metrics/t40_metrics_wait.rs, openraft/tests/state_machine/t10_total_order_apply.rs, openraft/tests/state_machine/t20_state_machine_apply_membership.rs
---
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/337)
=> Refactor: fixtures::TypedRaftRouter::wait() do not need to return a Result

example-raft-kv/src/store/mod.rs, memstore/src/lib.rs, openraft/src/core/leader_state.rs, openraft/src/core/replication.rs, openraft/src/core/replication_state.rs, openraft/src/core/replication_state_test.rs, openraft/src/replication/mod.rs, openraft/src/storage.rs, openraft/src/store_ext.rs
- `Snapshot<C:RaftTypeConfig, _>` change to `Snapshot<NID: NodeId, _>`.
- And other refactored non-pub types:
`ReplicaEvent, ReplicationStream, RaftEvent, TargetReplState, ReplicationState`
---
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/338)
=> Change: Snapshot does not need RaftTypeConfig as type param:

.github/workflows/ci.yaml, openraft/src/config/config.rs, openraft/src/config/config_test.rs, openraft/src/config/error.rs, openraft/src/config/mod.rs, openraft/src/core/admin.rs, openraft/src/core/replication.rs, openraft/src/core/replication_state.rs, openraft/src/error.rs, openraft/src/lib.rs, openraft/src/replication/mod.rs, openraft/tests/membership/main.rs, openraft/tests/membership/t45_remove_unreachable_follower.rs
The default trigger event to remove the replication to a node that is
not in membership is uniform membership log being committed and
replicated to that node.
But if the node is unreachable, the uniform membership log can never be
replicated.
This PR introduces another config: `Confg.remove_replication` to specify
when to remove a replication:
- `RemoveReplicationPolicy::CommittedAdvance(n)`: if the leader already
committed `n` more logs than the uniform membership log index, remove
the replication.
- `RemoveReplicationPolicy::MaxNetworkFailures(n)`: if the leader
encountered `n` network failures, such as `ReplicationError::Timeout`
or `ReplicationError::NetworkError`, remove the replication.
Changes:
- Add config: --remove-replication to specify when to stop replication to a unreachable …
=> Feature: remove replication stream for unreachable node

guide/src/SUMMARY.md, guide/src/effective-membership.md, guide/src/replication.md, openraft/src/core/append_entries.rs, openraft/src/core/install_snapshot.rs, openraft/tests/fixtures/mod.rs, openraft/tests/snapshot/main.rs, openraft/tests/snapshot/t10_snapshot_delete_conflict_logs.rs
Raft Engine only need to keep track of at most two membership: the last
committed one and the effective one.
Because Raft does not allow to propose new membership config if the
effective one has not yet committed.
When deleting conflicting logs on a Follower/Learner, it needs to revert
at most one membership config to previous one, i.e., discard the
effective one and make the last committed one effective.
This way we do not need to load membership from the storage, which is
expensive.
Update doc: explain snapshot replication and effective membership.
---
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/346)
=> Refactor: reverting membership state does not need to bother the store.

openraft/src/core/admin.rs, openraft/src/core/client.rs, openraft/src/core/leader_state.rs, openraft/src/core/mod.rs, openraft/src/core/raft_core.rs, openraft/src/core/replication.rs, openraft/src/replication/mod.rs
Remove `MetricsProvider`, use an `Option` instead.
Otherwise, the test script believes replication is shut down then
restore the network communication, there will be unexpected logs sent to
a follower hense the test fails: `stop_replication_to_removed_unreachable_follower_network_failure`.
---
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/349)
=> Refactor: clearn metrics flags every time metrics is reported

openraft/src/core/raft_core.rs, openraft/src/lib.rs, openraft/src/raft.rs, openraft/src/timer/mod.rs, openraft/src/timer/timeout.rs, openraft/src/timer/timeout_test.rs
-   Refactor: Merge `follower_loop` and `learner_loop`.
And  use a `Timeout` instance to trigger election. Avoid building unnecessary futures.
-   Feature: add oneshot Timeout supporting update deadline.
- The `callback` will be called at most once.
- If the `Timeout` is dropped, the callback will be canceled.
- The timeout deadline can only be updated to a higher value.
Synopsis:
```
let t = Timeout::new(|| {println!("hello");},  Duration::from_milli(10));
t.update_timeout(Duration::from_millis(10));
```
-   Refactor: add server_state_count to count ServerState changes to
track different round of follower-loop.
-   Refactor: RaftCore keeps a `tx_api` for Timeout to send message.
-   Fix: #351
---
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" …
=> Refactor: merge follower_loop and learner_loop

guide/src/effective-membership.md, openraft/src/engine/command.rs, openraft/src/engine/engine_impl.rs, openraft/src/engine/follower_append_entries_test.rs, openraft/src/engine/initialize_test.rs, openraft/src/engine/mod.rs, openraft/src/raft_state.rs
- Refactor: `Command::UpdateMembership.membership` type is changed to
`EffectiveMembership`
- Refactor: Engine: add `follower_append_entries()` to deal with
append-entries operation on a follower/learner.
It appends logs and update the membership if there are membership
entries in the input.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/354)
=> Refactor: Engine: ad `follower_append_entries()`

openraft/src/engine/log_id_list.rs, openraft/src/engine/log_id_list_test.rs, openraft/tests/membership/t16_change_membership_cases.rs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/355)
=> Refactor: LogIdList::truncate() delete items since the specified index

openraft/src/engine/engine_impl.rs, openraft/src/engine/mod.rs, openraft/src/engine/truncate_logs_test.rs, openraft/tests/fixtures/mod.rs, openraft/tests/membership/t10_add_learner.rs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/356)
=> Refactor: Engine::truncate() to delete logs that conflict with the leader and update membership.

guide/src/SUMMARY.md, guide/src/delete_log.md, openraft/src/core/raft_core.rs, openraft/src/engine/engine_impl.rs, openraft/src/raft.rs, openraft/src/vote/vote.rs, openraft/tests/membership/t16_change_membership_cases.rs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/360)
=> Doc: explain why to delete conflicting logs when handle append-entries RPC

openraft/src/core/raft_core.rs, openraft/src/raft.rs, openraft/tests/fixtures/mod.rs, openraft/tests/initialize/t20_initialization.rs
This change let user do more things with a external fn request.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/361)
=> Change: `external_request()` replace the 1st arg ServerState with RaftState

openraft/src/core/append_entries.rs, openraft/src/core/replication.rs, openraft/tests/membership/t20_change_membership.rs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/362)
=> Fix: membership_state.committed should be updated when a membership-config log is committed on leader or follower

openraft/src/engine/engine_impl.rs, openraft/src/engine/leader_append_entries_test.rs, openraft/src/engine/mod.rs, openraft/src/membership/effective_membership.rs
If there is a membership log in the log entries to append,
the quorum is changed, thus fast-commit is disallowed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/364)
=> Fix: leader should not fast-commit if there is a membership entry that changes the quorum

openraft/src/core/append_entries.rs, openraft/src/core/leader_state.rs, openraft/src/core/raft_core.rs, openraft/src/engine/command.rs, openraft/src/engine/engine_impl.rs, openraft/src/engine/leader_append_entries_test.rs, openraft/src/entry.rs, openraft/src/error.rs, openraft/tests/membership/t30_step_down.rs
- Add `Command::LeaderCommit` and `Command::FollowerCommit` since leader
and follower do differently when committing an entry.
- Add `Command::RejectElection` to inform the runtime to reject election
for a while, when a active leader is found, e.g., when receiving an
append-entries RPC.
- Extract vote checking logic into standalone method
`internal_handle_vote_req()`, which will be used by all 3 RPC handler:
`vote`, `append-entries` and `install-snapshot`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/367)
=> Refactor: add Engine commands, extract `internal_handle_vote_req()`

openraft/src/engine/engine_impl.rs, openraft/src/engine/truncate_logs_test.rs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/370)
=> Refactor: truncate_log should update server-state if membership config log is truncated

openraft/Cargo.toml
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/374)
=> CI: workaround pin clap version to 3.1 or there are inappropriate lint errors: https://github.com/clap-rs/clap/issues/3822

openraft/Cargo.toml
Updates the requirements on [clap](https://github.com/clap-rs/clap) to permit the latest version.
- [Release notes](https://github.com/clap-rs/clap/releases)
- [Changelog](https://github.com/clap-rs/clap/blob/master/CHANGELOG.md)
- [Commits](https://github.com/clap-rs/clap/compare/clap_complete-v3.1.0...v3.2.5)
---
updated-dependencies:
- dependency-name: clap
dependency-type: direct:production
...
Signed-off-by: dependabot[bot] <support@github.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/376)
=> Dep: Update clap requirement from ~3.1 to ~3.2

.github/workflows/commit-message-check.yml, .github/workflows/release-raft.yaml, README.md, derived-from-async-raft.md, openraft/src/replication/mod.rs, openraft/tests/membership/t25_elect_with_new_config.rs, openraft/tests/metrics/t30_leader_metrics.rs, scripts/build_change_log.py, scripts/requirements.txt
- Move derived-from-async-raft out of README
And skip version change log when exists
- fix: #381 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/382)
=> Fix: span.enter() in async block will leak memory

openraft/src/error.rs, openraft/src/raft.rs, openraft/tests/shutdown.rs
- Fix: #373
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/385)
=> Change: after shutdown(), it should return an error when accessing Raft, instead of panicking.

openraft/src/engine/log_id_list.rs, openraft/src/engine/log_id_list_test.rs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/387)
=> Fix: LogIdList::purge() panic when it is empty.

openraft/src/core/admin.rs, openraft/src/core/install_snapshot.rs, openraft/src/core/raft_core.rs, openraft/src/core/replication.rs, openraft/src/engine/calc_purge_upto_test.rs, openraft/src/engine/elect_test.rs, openraft/src/engine/engine_impl.rs, openraft/src/engine/follower_do_append_entries_test.rs, openraft/src/engine/handle_append_entries_req_test.rs, openraft/src/engine/handle_vote_req_test.rs, openraft/src/engine/initialize_test.rs, openraft/src/engine/internal_handle_vote_req_test.rs, openraft/src/engine/leader_append_entries_test.rs, openraft/src/engine/purge_log_test.rs, openraft/src/engine/truncate_logs_test.rs, openraft/src/raft_state.rs, openraft/src/raft_state_test.rs, openraft/src/storage.rs, openraft/src/testing/suite.rs
Remove these two fields, which are already included in
`RaftState.log_ids`; use `last_log_id()` and `last_purged_log_id()`
instead.
- Fix: #389
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/391)
=> Change: remove `RaftState.last_log_id` and `RaftState.last_purged_log_id`

openraft/src/core/client.rs, openraft/src/core/leader_state.rs, openraft/src/core/raft_core.rs, openraft/src/core/replication.rs, openraft/src/replication/mod.rs, openraft/tests/snapshot/t43_snapshot_delete_conflict_logs.rs
Replace the event type enum with a struct:
One struct to notify the replication to update either new last_log_id or
new committed.
Remove the unused span from the channel.
By entering candidate state, run a round of election, in order to
intialize the every state, such as the `vote` should be committed before
entering leader state.
Avoid a specialized running path, e.g. let the single node in the
cluster to enter leader state at once.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/393)
=> Refactor: simplify communication from RaftCore to ReplicationStream

openraft/src/core/client.rs, openraft/src/engine/engine_impl.rs, openraft/src/engine/leader_append_entries_test.rs, openraft/src/leader/leader.rs, openraft/src/lib.rs, openraft/src/membership/membership.rs, openraft/src/membership/membership_test.rs, openraft/src/membership/mod.rs, openraft/src/membership/quorum.rs, openraft/src/quorum/mod.rs, openraft/src/quorum/quorum_set.rs, openraft/src/quorum/quorum_set_impl.rs, openraft/src/quorum/quorum_set_test.rs, openraft/src/quorum/util.rs, openraft/src/quorum/util_test.rs
Move the quorum related functions from `Membership` to standalone mod
`QuorumSet`.
- Auto implement a simple majority quorum set for `BTreeSet` and `slice`.
- Auto implement a joint quorum set for `Vec` of some `QuorumSet`
implementation.
- Fix: #395
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/397)
=> Refactor: add QuorumSet to impl a set of quorum

openraft/Cargo.toml, openraft/src/lib.rs, openraft/src/membership/bench/is_quorum.rs, openraft/src/membership/bench/mod.rs, openraft/src/membership/membership.rs, openraft/src/membership/mod.rs, openraft/src/quorum/bench/is_quorum.rs, openraft/src/quorum/bench/mod.rs, openraft/src/quorum/joint.rs, openraft/src/quorum/joint_impl.rs, openraft/src/quorum/mod.rs, openraft/src/quorum/quorum_set.rs, openraft/src/quorum/quorum_set_impl.rs, openraft/src/quorum/quorum_set_test.rs
It let a user use a vector of `QuorumSet` as a joint quorum set with:
```
vec![vec![1, 2, 3], vec![4, 5, 6]].as_joint().is_quorum([1, 2, 4, 5].iter())
```
Add benchmark for various `QuorumSet` and `Membership.is_quorum()`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/400)
=> Feature: add openraft::quorum::Joint

openraft/src/lib.rs, openraft/src/progress/bench/mod.rs, openraft/src/progress/bench/vec_progress_update.rs, openraft/src/progress/mod.rs, openraft/src/quorum/mod.rs
Progress is stored in a `Vec<(ID, VALUE)>`.
Calling `update(id, new_value)` when replication to target `id` is
updated to `new_value`.
Algorithm:
Only when the **previous value** is less or equal the committed,
and the **new value** is greater than the currently committed,
there is possibly an update to the committed.
This way it gets rid of a portion of unnecessary re-calculation of committed,
and avoids unnecessary sorting: progresses are kept in order and only values greater than committed need to
sort.
E.g., given 3 ids with value `1,3,5`,
the committed is `3` and assumes a majority quorum set is used.
Then:
- update(a, 6): nothing to do: committed is still 3;
- update(b, 4): re-calc:       committed becomes 4;
- update(b, 6): re-calc:       committed becomes 5;
- update(c, 2): …
=> Refactor: add Progress to track replication state and to calculate committed log id

openraft/src/progress/bench/vec_progress_update.rs, openraft/src/progress/mod.rs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/406)
=> Refactor: VecProgress::new() do not need arg ids

openraft/src/membership/membership.rs, openraft/src/progress/mod.rs, openraft/src/quorum/joint.rs, openraft/src/quorum/quorum_set.rs, openraft/src/quorum/quorum_set_impl.rs, openraft/src/quorum/quorum_set_test.rs
As @schreter suggested, prefer using `Iterator` to a concrete type.
The return value of `QuorumSet::ids()` now is defined by a associated
type: `QuorumSet::Iter`. In this implementation, it always uses a
`btree_set::IntoIter`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/410)
=> Refactor: QuorumSet::ids() returns `Iterator` instead of `BTreeSet`.

openraft/src/membership/membership.rs, openraft/src/membership/membership_test.rs, openraft/src/quorum/coherent.rs, openraft/src/quorum/coherent_impl.rs, openraft/src/quorum/coherent_test.rs, openraft/src/quorum/joint.rs, openraft/src/quorum/mod.rs
**Coherent** quorum set A and B is defined as: `∀ qᵢ ∈ A, ∀ qⱼ ∈ B: qᵢ ∩ qⱼ != ø`, i.e., `A ~ B`.
- `is_coherent()` checks if two `QuorumSet`s are coherent, i.e, it is
safe to change from one to another.
- `find_coherent()` builds an `QuorumSet` as an intermediate one to help
changing membership between two incoherent ones.
Other changes:
- Remove unused `Membership::is_safe_to()`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/411)
=> Refactor: add coherent QuorumSet support

example-raft-kv/tests/cluster/test_cluster.rs, openraft/src/core/admin.rs, openraft/src/core/client.rs, openraft/src/core/leader_state.rs, openraft/src/core/raft_core.rs, openraft/src/core/replication.rs, openraft/src/engine/engine_impl.rs, openraft/src/leader/leader.rs, openraft/src/membership/bench/is_quorum.rs, openraft/src/membership/effective_membership.rs, openraft/src/membership/effective_membership_test.rs, openraft/src/membership/membership.rs, openraft/src/membership/membership_state.rs, openraft/src/membership/membership_test.rs, openraft/src/membership/mod.rs, openraft/src/membership/node_type.rs, openraft/src/metrics/wait.rs, openraft/src/metrics/wait_test.rs, openraft/src/quorum/joint.rs, openraft/src/replication/mod.rs, openraft/tests/fixtures/mod.rs, openraft/tests/life_cycle/t20_initialization.rs, openraft/tests/membership/t10_add_learner.rs, openraft/tests/membership/t30_step_down.rs
- Refactor: move impl of `QuorumSet` from `Membership` to `EffectiveMembership`.
Add a field `EffectiveMembership.quorum_set`, to store a
`QuorumSet` built from the `Membership` config. This quorum set can have
a different structure from the `Membership`, to optimized quorum check.
- Refactor: impl methods in `Membership` or `EffectiveMembership` with
Iterator if possible.
- Refactor: use term `voter` and `learner` for methods and fields.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/413)
=> Change: API: cleanup APIs in Membership and EffectiveMembership

openraft/tests/client_api/t10_client_writes.rs, openraft/tests/state_machine/t10_total_order_apply.rs
- Ignore test `total_order_apply`.
- Reduce the number of put for `client_write`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/416)
=> Refactor: reduce test time

example-raft-kv/src/client.rs, example-raft-kv/src/network/management.rs, openraft/src/core/raft_core.rs, openraft/src/metrics/raft_metrics.rs, openraft/src/metrics/wait.rs, openraft/src/metrics/wait_test.rs, openraft/src/raft.rs, openraft/tests/fixtures/mod.rs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/417)
=> Change: `RaftMetrics` and `Wait` do not need type param `C`, but just a `NID: NodeId`

openraft/src/core/admin.rs, openraft/src/core/leader_state.rs, openraft/src/core/replication.rs, openraft/src/core/replication_state.rs, openraft/src/raft.rs, openraft/tests/membership/t10_add_learner.rs
Replication should not be responsible invoke the callback when
replication become upto date. It makes the logic dirty.
Such a job can be done by watching the metrics change.
- Change: API: AddLearnerResponse has a new field `membership_log_id`
which is the log id of the membership log that contains the newly
added learner.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/419)
=> Change: remove `tx` from `spawn_replication_stream()`

openraft/src/error.rs
Even when the learner to add already exists, the caller may still want
to block until the replication catches up. Thus it does not expect an
error.
And `Exists` is not an issue the caller has to deal with, it does not
have to be an error.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/420)
=> Change: remove error `AddLearnerError::Exists`

openraft/src/engine/log_id_list.rs, openraft/src/raft_state.rs, openraft/src/storage.rs
This method does not need to be a method of `RaftState`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/421)
=> Refactor: move `load_log_ids()` from `RaftState` to `LogIdList`

openraft/src/core/raft_core.rs, openraft/src/engine/log_id_list.rs, openraft/src/lib.rs, openraft/src/storage/helper.rs, openraft/src/storage/mod.rs, openraft/src/testing/suite.rs, openraft/tests/membership/t10_add_learner.rs, openraft/tests/snapshot/t41_snapshot_overrides_membership.rs, openraft/tests/snapshot/t42_snapshot_uses_prev_snap_membership.rs, openraft/tests/snapshot/t43_snapshot_delete_conflict_logs.rs
- `get_initial_state()`
- `get_log_id()`
- `get_membership()`
- `last_membership_in_log()`
In the trait `RaftStorage`, these methods provide several default
methods that users do not need to care about. It should no longer
be methods that user may need to implement.
To upgrade:
If you have been using these methods, replace `sto.xxx()` with
`StorageHelper::new(&mut sto).xxx()`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/422)
=> Change: move default impl methods in `RaftStorage` to `StorageHelper`.

openraft/src/storage/helper.rs, openraft/src/testing/suite.rs
The iterating range searching for membership log entries should be
`[end-step, end)`, not `[start, end)`.
With this bug it will return duplicated membership entries.
- Related: #424
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/425)
=> Fix: bug in searching for membership entries: `[end-step, end)`.

openraft/src/storage.rs, openraft/src/testing/suite.rs
The iterating range searching for membership log entries should be
`[end-step, end)`, not `[start, end)`.
With this bug it will return duplicated membership entries.
- Bug: #424
**Checklist**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/426)
=> Fix: #424 wrong range when searching for membership entries: `[end-step, end)`

memstore/Cargo.toml, openraft/Cargo.toml, openraft/src/types/v065/storage.rs, openraft/tests/append_conflicts.rs, openraft/tests/conflict_with_empty_entries.rs, openraft/tests/fixtures/mod.rs
Future versions of openraft will be able to import this store
implementation for compatibility test.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/429)
=> publish memstore as openraft-memstore

memstore/Cargo.toml
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/434)
=> Dep: memstore 0.7.0 depends on openraft 0.7.0

README.md, openraft/src/config/config.rs, openraft/src/config/config_test.rs, openraft/src/core/admin.rs, openraft/src/core/append_entries.rs, openraft/src/core/client.rs, openraft/src/core/leader_state.rs, openraft/src/core/mod.rs, openraft/src/core/raft_core.rs, openraft/src/engine/calc_purge_upto_test.rs, openraft/src/engine/engine_impl.rs, openraft/src/engine/follower_commit_entries_test.rs, openraft/src/engine/mod.rs, openraft/src/engine/update_progress_test.rs, openraft/tests/append_entries/t90_issue_216_stale_last_log_id.rs, openraft/tests/benchmark/bench_cluster.rs, openraft/tests/log_compaction/t10_compaction.rs, openraft/tests/membership/t10_add_learner.rs, openraft/tests/snapshot/t24_snapshot_ge_half_threshold.rs, openraft/tests/snapshot/t40_after_snapshot_add_learner_and_request_a_log.rs, openraft/tests/snapshot/t41_snapshot_overrides_membership.rs, openraft/tests/snapshot/t42_snapshot_uses_prev_snap_membership.rs, openraft/tests/snapshot/t43_snapshot_delete_conflict_logs.rs, openraft/tests/state_machine/t40_clean_applied_logs.rs
- Feature: add config `purge_batch_size`: purge applied log in a batch of the specified size.
This will reduce unnecessary storage access.
- Refactor: move `client_resp_channels` from `LeaderState` to
`RaftCore`. So that Engine `Command` execution in future can be moved
to `RaftCore`.
- Refactor: simplify `apply_to_state_machine()`. Remove duplicated
implementation for leader and follower.
- Refactor: add `EngineConfig` that contains configurations used by
Engine.
- Refactor: Engine emits `Command::PurgeLog`. `RaftCore` does not need
to trigger purging manually.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/442)
=> Refactor: simplify `apply_to_state_machine()`.

openraft/src/engine/elect_test.rs, openraft/src/engine/engine_impl.rs, openraft/src/engine/handle_vote_resp_test.rs, openraft/src/engine/update_effective_membership_test.rs, openraft/src/leader/leader.rs, openraft/src/progress/mod.rs, openraft/src/raft_state.rs
learner progresses are tracked by `Progress` but these progresses won't
be counted when calculate the `granted` value, i.e. the value that is
granted by a quorum.
- Refactor: rename `Progress::committed()` to `granted()`, because in
raft granted by a quorum does not imply it is committed. A second
requirement is that the value has to be the greatest, i.e., a log
entry is proposed by the current leader.
- Refactor: add method `Progress::iter()` to iterate all ids and values.
- Refactor: add method `Progress::is_voter()` to check if a given id is
a `voter`,  i.e., one defined in its quorum-set.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/445)
=> Refactor: Progress also tracks replication progress to learners

guide/src/SUMMARY.md, guide/src/dynamic-membership.md, guide/src/node-lifecycle.md, openraft/src/config/config.rs, openraft/src/config/config_test.rs, openraft/src/config/error.rs, openraft/src/config/mod.rs, openraft/src/core/admin.rs, openraft/src/core/client.rs, openraft/src/core/leader_state.rs, openraft/src/core/raft_core.rs, openraft/src/core/replication.rs, openraft/src/core/replication_state.rs, openraft/src/engine/command.rs, openraft/src/engine/engine_impl.rs, openraft/src/engine/leader_append_entries_test.rs, openraft/src/engine/update_effective_membership_test.rs, openraft/src/lib.rs, openraft/tests/membership/t15_add_remove_follower.rs, openraft/tests/membership/t40_removed_follower.rs, openraft/tests/membership/t45_remove_unreachable_follower.rs, openraft/tests/metrics/t30_leader_metrics.rs
Before this commit, when membership changes, e.g., from a joint config
`[(1,2,3), (3,4,5)]` to uniform config `[3,4,5]`(assuming the leader is
`3`), the leader stops replication to `1,2` when `[3,4,5]` is
committed.
This is an unnecessarily complicated solution.
It is OK for the leader to stop replication to `1,2` as soon as config `[3,4,5]` is seen, instead of when config `[3,4,5]` is committed.
- If the leader(`3`) finally committed `[3,4,5]`, it will eventually stop replication to `1,2`.
- If the leader(`3`) crashes before committing `[3,4,5]`:
- And a new leader sees the membership config log `[3,4,5]`, it will continue to commit it and finally stop replication to `1,2`.
- Or a new leader does not see membership config log `[3,4,5]`, it will re-establish replication to `1,2`.
In any …
=> Change: Stop replication to removed node at once when new membership is seen

openraft/src/core/admin.rs, openraft/src/core/client.rs, openraft/src/core/leader_state.rs, openraft/src/core/raft_core.rs, openraft/tests/membership/t16_change_membership_cases.rs, openraft/tests/membership/t45_remove_unreachable_follower.rs
If the effective membership that does not contain the current leader is
committed, no matter it is a joint config or uniform config, the leader
will step down.
Before this commit only when a **uniform** config is committed a leader
will step down, which is a unnecessary limit.
- Refactor: Move stepdown related methods to `RaftCore`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/448)
=> Refactor: leader step down if either a uniform or joint config is committed.

openraft/src/core/admin.rs, openraft/src/core/client.rs, openraft/src/core/leader_state.rs, openraft/src/core/mod.rs, openraft/src/core/replication.rs, openraft/src/core/replication_state.rs, openraft/src/replication/mod.rs, openraft/tests/membership/t15_add_remove_follower.rs
`ReplicationState` now is simply a wrapper of `ReplicationStream`.
Use `ReplicationStream` instead.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/449)
=> Refactor: remove `ReplicationState`

openraft/src/core/admin.rs, openraft/src/core/leader_state.rs, openraft/src/core/raft_core.rs, openraft/src/core/replication.rs, openraft/src/replication/mod.rs
So that `RaftCore` can report metrics without accessing `LeaderState`.
Let sub task such as replication enter a span that is a child of
`RaftCore.span`, to provide better tracing hierarchy.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/450)
=> Refactor: move field `repliation_metrics` from `LeaderState` to `RaftCore.leader_data`

openraft/src/core/admin.rs, openraft/src/core/client.rs, openraft/src/core/leader_state.rs, openraft/src/core/raft_core.rs, openraft/src/core/replication.rs, openraft/src/engine/engine_impl.rs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/451)
=> Refactor: move `LeaderState.nodes` to `RaftCore.leader_data`

guide/src/SUMMARY.md, guide/src/vote.md, openraft/src/core/raft_core.rs, openraft/src/raft.rs, openraft/src/replication/mod.rs
Every server state has a unique corresponding `vote`, thus `vote` can be
used to identify different server states, i.e, if the `vote` changes,
the server state must have been changed.
`vote` in openraft defines the pseudo **time** in the distributed
consensus. Each `vote` can be thought as unique time point.
(Although in standard raft there is no such concept.)
E.g.:
- A vote `(term=1, node_id=2, committed=false)` is in a candidate state for
node-2.
- A vote `(term=1, node_id=2, committed=true)` is in a leader state for
node-2.
- A vote `(term=1, node_id=2, committed=false|true)` is in a follower state for
node-3.
- A vote `(term=1, node_id=1, committed=false|true)` is in a different follower state for
node-3.
---
This change is [<img src="https://reviewable.io/review_button.svg" …
=> Refactor: use `vote` to identify a server state.

openraft/src/core/install_snapshot.rs, openraft/src/core/internal_msg.rs, openraft/src/core/mod.rs, openraft/src/core/raft_core.rs, openraft/src/core/tick.rs, openraft/src/engine/command.rs, openraft/src/engine/engine_impl.rs, openraft/src/engine/handle_append_entries_req_test.rs, openraft/src/engine/handle_vote_req_test.rs, openraft/src/engine/handle_vote_resp_test.rs, openraft/src/engine/internal_handle_vote_req_test.rs, openraft/src/raft.rs, openraft/tests/elect/t10_elect_compare_last_log.rs
- Refactor: use Tick instead of setting up timer everywhere.
When RaftCore is spawned, another task is spawn for emitting a `tick`
event at a fixed interval, to wake up the RaftCore regularly to check
timeout events, such as election timeout for follower.
- Refactor: use api-channel(`tx_api`) for election task to send vote-response to RaftCore.
- Refactor: when switch to follower state, the election timeout is set
differently: If the follower can become a leader, i.e, it does not
see a greater last-log-id when electing, give it a short sleep time.
Otherwise, there are greater last-log-id in the cluster, give it a
longer sleep time. This way to reduce election conflict.
--- …
=> Refactor: reduce election conflict

openraft/src/core/raft_core.rs, openraft/src/engine/engine_impl.rs, openraft/src/engine/internal_handle_vote_req_test.rs, openraft/src/error.rs, openraft/src/membership/membership_state.rs, openraft/src/membership/membership_state_test.rs, openraft/src/replication/mod.rs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/461)
=> Refactor: move last-log-id check out of Engine::internal_handle_vote_change()

Makefile, openraft/src/core/raft_core.rs, openraft/src/engine/elect_test.rs, openraft/src/engine/engine_impl.rs, openraft/src/engine/handle_append_entries_req_test.rs, openraft/src/engine/handle_vote_req_test.rs, openraft/src/engine/handle_vote_resp_test.rs, openraft/src/engine/internal_handle_vote_req_test.rs, openraft/src/engine/update_effective_membership_test.rs, openraft/src/internal_server_state.rs, openraft/src/lib.rs, openraft/src/raft_state.rs, openraft/src/storage/helper.rs, openraft/src/timer/timeout_test.rs
In openraft there are only two state for a server:
Leading(raft leader or raft candidate) and following(raft follower or raft learner):
- A leading state is able to vote(candidate in original raft) and is able to propose new log if its vote is granted
by quorum(leader in original raft).
In this way the leadership won't be lost when it sees a higher `vote` and needs upgrade its `vote`.
- A following state just receives replication from a leader. A follower that is one of the member will be able to
become leader. A following state that is not a member is just a learner.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/463)
=> Refactor: add InternalServerState

openraft/src/core/raft_core.rs, openraft/src/engine/elect_test.rs, openraft/src/engine/engine_impl.rs, openraft/src/engine/initialize_test.rs, openraft/tests/membership/t16_change_membership_cases.rs, openraft/tests/membership/t40_removed_follower.rs
Candidate loop should run in a passive mode: just handles messages.
A timer for election will trigger a candidate to elect when candidate
timed out collecting enough vote response.
This way in the candidate loop it does not need to call
`Engine::elect()` it self any more.
Other parts are updated according to this change:
such as `Engine::initialize()` can not rely on `candidate_loop()` to
trigger election. `initialize()` has to manually call `elect()` to enter
candidate state.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/464)
=> Refactor: candidate_loop() should not trigger election

openraft/src/config/config.rs, openraft/src/config/config_test.rs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/465)
=> Refactor: simplify config arg attributes for keep_unsnapshoted_log

.github/workflows/ci.yaml, memstore/Cargo.toml, memstore/src/lib.rs, openraft/Cargo.toml, openraft/src/core/mod.rs, openraft/src/error.rs, openraft/src/lib.rs, openraft/src/storage_error.rs, openraft/src/types/v065/storage_error.rs
`--features bt` enables backtrace when generating errors.
By default errors does not contain backtrace info.
Thus openraft can be built on stable rust by default.
To use on stable rust with backtrace, set `RUSTC_BOOTSTRAP=1`, e.g.:
```
RUSTUP_TOOLCHAIN=stable RUSTC_BOOTSTRAP=1 make test
```
- Fix: #469
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/470)
=> Feature: add feature-flag: `bt` enables backtrace

openraft/src/core/raft_core.rs, openraft/src/core/replication_state.rs, openraft/src/raft.rs, openraft/tests/membership/main.rs, openraft/tests/membership/t99_issue_471_adding_learner_uses_uninit_leader_id.rs
When waiting for a newly added learner to become up to date,
it tries to compare last-log-id and the reported `matched` replication
state.
But the `matched` may have not yet receive any update and is
unitialized, in such case, it tries to create a temp LogId with
`leader_id(0, 0)`, which is illegal.
The fix is simple: do not use log-id. Just calculating replication lag by log index.
Add test to reproduce it: openraft/tests/membership/t99_issue_471_adding_learner_uses_uninit_leader_id.rs
- Fix: #471
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/473)
=> Fix: avoid creating log-id with unitialized `matched.leader_id`.

openraft/src/engine/engine_impl.rs, openraft/src/engine/handle_vote_resp_test.rs
It does not to leave candidate state when a vote request is rejected.
Since follower loop and candidate loop are totally the same.
The only thing needs to do is to reset the timeout for next election,
when vote is rejected.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/481)
=> Refactor: when vote is rejected it stays in candidate state.

.github/workflows/ci.yaml
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/484)
=> CI: move release building out of `ut`

examples/raft-kv-memstore/src/network/api.rs, examples/raft-kv-rocksdb/src/network/api.rs, openraft/src/core/raft_core.rs, openraft/src/engine/engine_impl.rs, openraft/src/raft.rs, openraft/tests/fixtures/mod.rs
Remove struct `ClientWriteRequest`.
`ClientWriteRequest` is barely a wrapper that does not provide any
additional function.
`Raft::client_write(ClientWriteRequest)` is changed to
`Raft::client_write(app_data: D)`, where `D` is application defined
`AppData` implementation.
- Fix: #171
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/485)
=> Change: remove ClientWriteRequest

examples/raft-kv-memstore/src/store/mod.rs, examples/raft-kv-rocksdb/src/store.rs, memstore/src/lib.rs, openraft/src/core/install_snapshot.rs, openraft/src/replication/mod.rs, openraft/src/storage/mod.rs, openraft/src/storage/snapshot_signature.rs, openraft/src/storage_error.rs, rocksstore/src/lib.rs
Change `ErrorSubject::Snapshot(SnapshotMeta)` to `ErrorSubject::Snapshot(SnapshotSignature)`.
`SnapshotSignature` is the same as `SnapshotMeta` except it does not include
`Membership` information.
This way errors do not have to depend on type `Node`, which is used in
`Membership` and it is a application specific type.
Then when a user-defined generic type `NodeData` is introduced, error
types do not need to change.
- Part of: #480
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/487)
=> Change: `ErrorSubject::Snapshot(SnapshotSignature)`

examples/raft-kv-memstore/src/network/raft_network_impl.rs, examples/raft-kv-rocksdb/src/network/raft_network_impl.rs, openraft/src/core/raft_core.rs, openraft/src/error.rs, openraft/src/network.rs, openraft/tests/append_entries/t10_conflict_with_empty_entries.rs, openraft/tests/append_entries/t50_append_entries_with_bigger_term.rs, openraft/tests/fixtures/mod.rs, openraft/tests/life_cycle/main.rs, openraft/tests/life_cycle/t30_connect_error.rs, openraft/tests/log_compaction/t10_compaction.rs, openraft/tests/metrics/t30_leader_metrics.rs, openraft/tests/snapshot/t41_snapshot_overrides_membership.rs, openraft/tests/snapshot/t43_snapshot_delete_conflict_logs.rs
`RaftNetworkFactory::connect()` let user specify an error when it fails
to create a new `RaftNetwork` instance, with associated type:
`RaftNetworkFactory::ConnectionError`.
- Fix: #466
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/488)
=> Change: now RaftNetworkFactory::connect() returns a Result.

openraft/src/core/raft_core.rs
Signed-off-by: ClSlaid <cailue@bupt.edu.cn>
This PR solves #467.
1. vote requests should not exceed the timeout of `heartbeat_interval`.
2. timeout will be logged
3. log `JoinError`s in parallel tasks
**Checklist**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/486)
=> Refactor: timeout control in votes

examples/raft-kv-memstore/src/network/management.rs, examples/raft-kv-memstore/src/network/raft_network_impl.rs, examples/raft-kv-memstore/tests/cluster/test_cluster.rs, examples/raft-kv-rocksdb/src/network/management.rs, examples/raft-kv-rocksdb/src/network/raft_network_impl.rs, examples/raft-kv-rocksdb/tests/cluster/test_cluster.rs, openraft/src/core/raft_core.rs, openraft/src/engine/command.rs, openraft/src/engine/engine_impl.rs, openraft/src/engine/leader_append_entries_test.rs, openraft/src/engine/update_effective_membership_test.rs, openraft/src/error.rs, openraft/src/membership/effective_membership.rs, openraft/src/membership/membership.rs, openraft/src/membership/membership_test.rs, openraft/src/metrics/mod.rs, openraft/src/network.rs, openraft/src/raft.rs, openraft/src/replication/mod.rs, openraft/tests/append_entries/t10_conflict_with_empty_entries.rs, openraft/tests/append_entries/t50_append_entries_with_bigger_term.rs, openraft/tests/fixtures/mod.rs, openraft/tests/log_compaction/t10_compaction.rs, openraft/tests/membership/t10_add_learner.rs, openraft/tests/snapshot/t41_snapshot_overrides_membership.rs, openraft/tests/snapshot/t43_snapshot_delete_conflict_logs.rs
Replication state belongs to a specific membership config.
E.g. given 3 membership log:
- `log_id=1, members={a,b,c}`
- `log_id=5, members={a,b}`
- `log_id=10, members={a,b,c}`
When log_id=1 is appended, openraft spawns a replication to node `c`.
Then log_id=1 is replicated to node `c`.
Then a replication state update message `{target=c, matched=log_id-1}` is piped in message queue(`tx_api`),
waiting the raft core to process.
Then log_id=5 is appended, replication to node `c` is dropped.
Then log_id=10 is appended, another replication to node `c` is spawned.
Now node `c` is a new empty node, no log is replicated to it.
But the delayed message `{target=c, matched=log_id-1}` may be process by raft core and make raft core believe
node `c` already has `log_id=1`, and commit it.
In this …
=> Change: Membership.nodes remove Option from value

openraft/src/core/raft_core.rs, openraft/src/engine/elect_test.rs, openraft/src/engine/engine_impl.rs, openraft/src/engine/handle_vote_resp_test.rs, openraft/src/engine/initialize_test.rs, openraft/tests/membership/t30_step_down.rs
`RaftCore::leader_loop()` does not need to setup replication.
`Engine` decides when to do it.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/493)
=> Refactor: Engine decide when to set up replication

openraft/src/core/raft_core.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/494)
=> Refactor: leader_loop does not need to report metric; its done by runtime_loop

openraft/src/core/raft_core.rs, openraft/src/engine/command.rs, openraft/src/engine/engine_impl.rs, openraft/src/engine/leader_append_entries_test.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/495)
=> Refactor: Commond::ReplicateEntries use log id

openraft/src/core/raft_core.rs, openraft/src/engine/command.rs, openraft/src/engine/elect_test.rs, openraft/src/engine/engine_impl.rs, openraft/src/engine/handle_vote_resp_test.rs, openraft/src/engine/initialize_test.rs, openraft/tests/metrics/t30_leader_metrics.rs
`RaftCore` does not need to track `ServerState` and switch to different
loop any more. Server state will be tracked by `Engine`.
- Refactor: Add `Command::AppendBlankLog` for leader initialization.
- Leader initial blank log now is emitted by `Engine`. `RaftCore`
becomes a pure runtime that just passively execute commands emitted by
Engine.
- Fix: #496
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/497)
=> Refactor: merge loops for all server state into one loop

openraft/src/core/raft_core.rs, openraft/src/engine/engine_impl.rs, openraft/src/error.rs, openraft/src/raft.rs, openraft/src/replication/mod.rs, openraft/tests/append_entries/main.rs, openraft/tests/append_entries/t10_see_higher_vote.rs
When a leader reverts to follower, e.g., if a higher vote is seen,
it should inform waiting clients that leadership is lost.
- Let Engine deals with vote change event.
- Add test for reverting to follower behavior.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/500)
=> Fix: when leader reverts to follower, send error to waiting clients

openraft/src/core/raft_core.rs, openraft/src/engine/elect_test.rs, openraft/src/engine/engine_impl.rs, openraft/src/engine/follower_commit_entries_test.rs, openraft/src/engine/follower_do_append_entries_test.rs, openraft/src/engine/handle_append_entries_req_test.rs, openraft/src/engine/handle_vote_req_test.rs, openraft/src/engine/handle_vote_resp_test.rs, openraft/src/engine/initialize_test.rs, openraft/src/engine/internal_handle_vote_req_test.rs, openraft/src/engine/leader_append_entries_test.rs, openraft/src/engine/truncate_logs_test.rs, openraft/src/engine/update_committed_membership_test.rs, openraft/src/engine/update_effective_membership_test.rs, openraft/src/raft_types.rs, openraft/tests/membership/t25_elect_with_new_config.rs, openraft/tests/state_machine/t40_clean_applied_logs.rs
And remove unnecessary `sleep()`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/501)
=> Refactor: split metrics change flags to three: data changes, replication changes and cluster info changes

openraft/src/core/raft_core.rs, openraft/src/raft.rs, openraft/tests/life_cycle/t30_connect_error.rs, openraft/tests/membership/t25_elect_with_new_config.rs, openraft/tests/metrics/t30_leader_metrics.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/503)
=> Feature: add `Raft::trigger_elect()` and `Raft::trigger_heartbeat()` to let user manually trigger a election or send a heartbeat log

openraft/src/core/raft_core.rs, openraft/src/raft.rs, openraft/tests/snapshot/main.rs, openraft/tests/snapshot/t20_trigger_snapshot.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/504)
=> Feature: add Raft::trigger_snapshot() to manually trigger to build snapshot at once

openraft/src/core/append_entries.rs, openraft/src/defensive.rs, openraft/tests/append_entries/main.rs, openraft/tests/append_entries/t31_append_prev_is_purged.rs, openraft/tests/fixtures/mod.rs
When handling append-entries, if the local log at `prev_log_id.index` is
purged, a follower should not believe it is a **conflict** and should
not delete all logs. It will get committed log lost.
To fix this issue, use `last_applied` instead of `committed`:
`last_applied` is always the committed log id, while `committed` is not
persisted and may be smaller than the actually applied, when a follower
is restarted.
**Checklist**
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/509)
=> Fix: when handling append-entries, if prev_log_id is purged, it should not delete any logs.

openraft/src/core/install_snapshot.rs, openraft/src/core/raft_core.rs, openraft/src/engine/calc_purge_upto_test.rs, openraft/src/engine/command.rs, openraft/src/engine/elect_test.rs, openraft/src/engine/engine_impl.rs, openraft/src/engine/follower_commit_entries_test.rs, openraft/src/engine/handle_append_entries_req_test.rs, openraft/src/engine/initialize_test.rs, openraft/src/engine/leader_append_entries_test.rs, openraft/src/engine/update_progress_test.rs, openraft/src/raft_state.rs, openraft/src/storage/helper.rs, openraft/src/testing/suite.rs
- Fix: when handling append-entries, if `prev_log_id` is purged, it
should not treat it as a **conflict** log and should not delete any
log.
This bug is caused by using `committed` as `last_applied`.
`committed` may be smaller than `last_applied` when a follower just
starts up.
The solution is merging `committed` and `last_applied` into one field:
`committed`, which is always greater than or equal the actually
committed(applied).
- Change: remove `RaftState.last_applied`, use `committed` to represent
the already committed and applied log id.
- Refactor: Command::LeaderCommit and Command::FollowerCommit
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/510)
=> Fix: when handling append-entries, if `prev_log_id` is purged, it should not treat it as a **conflict**

openraft/src/store_ext.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/513)
=> Refactor: let StoreExt deref to inner storage implementation

openraft/src/core/client.rs, openraft/src/core/mod.rs, openraft/src/raft.rs, openraft/src/types/v070/mod.rs, openraft/src/types/v070/rpc.rs, openraft/tests/fixtures/mod.rs
ClientWriteRequest is nothing more than a wrapper of entry payload.
**Checklist**
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/515)
=> Change: remove ClientWriteRequest, client_write() parameter now is an AppData

examples/raft-kv-memstore/src/store/mod.rs, examples/raft-kv-rocksdb/src/store.rs, memstore/src/lib.rs, openraft/src/core/install_snapshot.rs, openraft/src/core/raft_core.rs, openraft/src/core/snapshot_state.rs, openraft/src/raft_types.rs, openraft/src/replication/mod.rs, openraft/src/storage/mod.rs, openraft/src/testing/suite.rs, openraft/tests/fixtures/mod.rs, openraft/tests/snapshot/t20_api_install_snapshot.rs, rocksstore/src/lib.rs
`SnapshotMeta.last_log_id` should be the same type as
`StateMachine.last_applied`.
By making `SnapshotMeta.last_log_id` an Option of LogId, a snapshot can
be build on an empty state-machine(in which `last_applied` is None).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/517)
=> Change: SnapshotMeta.last_log_id from LogId to Option of LogId

Cargo.toml, sledstore/Cargo.toml, sledstore/src/lib.rs, sledstore/src/test.rs
Hey, this adds a [sled db](https://github.com/spacejam/sled) example based on rocks db example as mentioned in #418. New example are at-par functionality wise with current but achieve it in different ways showcasing a different set of libraries to achieve comparable results.
**Checklist**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/441)
=> Feature: Added sled store example based on rocks example

README.md, guide/src/SUMMARY.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/521)
=> Doc: add 0.6 to 0.7 upgrade guide to readme

openraft/src/core/install_snapshot.rs, openraft/src/core/mod.rs, openraft/src/core/raft_core.rs, openraft/src/core/snapshot_state.rs, openraft/src/core/streaming_state.rs, openraft/src/engine/calc_purge_upto_test.rs, openraft/src/engine/command.rs, openraft/src/engine/engine_impl.rs, openraft/src/engine/install_snapshot_test.rs, openraft/src/engine/mod.rs, openraft/src/engine/update_snapshot_test.rs, openraft/src/raft.rs, openraft/src/raft_state.rs, openraft/src/storage/mod.rs, openraft/tests/snapshot/t20_api_install_snapshot.rs, openraft/tests/snapshot/t43_snapshot_delete_conflict_logs.rs
- Refactor: change `Option<SnapshotState>` to `SnapshotState`.
Let `SnapshotState` itself include a `None` state.
- Refactor: `Engine::install_snapshot()` handles snapshot installation,
and decides what to do next.
`RaftCore` as a runtime for the Engine, it is still in charge of with
snapshot fragmentation when streaming a snapshot.
- Refactor: rename `RaftMsg::SnapshotUpdate` to
`RaftMsg::BuildingSnapshotResult`. To be clear, it's only about
the state of building a snapshot locally.
And more info are added: complete snapshot meta is sent when succeeded
building snapshot, or exact error when it failed buliding a snapshot.
- Refactor: change `Engine.snapshot_last_log_id` to
`Engine.snapshot_meta`. Now Engine has all snapshot information
execpt the snapshot data.
- Fix: #498
- - -
This …
=> Refactor: Engine handles install-snapshot

examples/raft-kv-memstore/src/network/raft_network_impl.rs, examples/raft-kv-rocksdb/src/lib.rs, examples/raft-kv-rocksdb/src/network/raft_network_impl.rs, openraft/src/core/raft_core.rs, openraft/src/core/tick.rs, openraft/src/network.rs, openraft/src/raft_types.rs, openraft/tests/append_entries/t10_conflict_with_empty_entries.rs, openraft/tests/append_entries/t10_see_higher_vote.rs, openraft/tests/append_entries/t50_append_entries_with_bigger_term.rs, openraft/tests/fixtures/mod.rs, openraft/tests/log_compaction/t10_compaction.rs, openraft/tests/snapshot/t41_snapshot_overrides_membership.rs, openraft/tests/snapshot/t43_snapshot_delete_conflict_logs.rs
This change introduces a reconnect logic for when
RaftNetworkFactory::connect fails. This way, nodes that are down during
leader promotion are eventually connected to when they are brought back
up.
Fixes: #525
**Checklist**
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/526)
=> Fix: reconnect to unreachable nodes.

openraft/tests/fixtures/mod.rs
If faking network delay first, when a node is restored(with `router.restore()`),
a previous delayed RPC with stale state will be sent out.
But in tests, `router.restore()` should be a **barrier**: no RPC built
with the state before the barrier should **NOT** be reordered after the
barrier.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/536)
=> CI: in tests: check reachability before faking network delay

examples/raft-kv-memstore/src/store/mod.rs, examples/raft-kv-rocksdb/src/store.rs, memstore/src/lib.rs, openraft/src/core/raft_core.rs, openraft/src/lib.rs, openraft/src/raft_types.rs, openraft/src/storage/mod.rs, openraft/src/store_ext.rs, openraft/tests/snapshot/t40_purge_in_snapshot_logs.rs, rocksstore/src/lib.rs, sledstore/src/lib.rs
The caller of `RaftStorage::install_snapshot()` knows about what changes
have been made, the return value is unnecessary.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/537)
=> Change: RaftStorage::install_snapshot() does not need to return state changes

openraft/src/engine/engine_impl.rs, openraft/src/engine/handle_vote_resp_test.rs, openraft/src/internal_server_state.rs, openraft/src/membership/membership.rs, openraft/src/raft_state.rs, openraft/src/replication/mod.rs
Leader state only needs a QuorumSet to determine quorum granted
progress. It does not need complete Membership information, e.g., it
does not need to know about `Node`, but only `NodeId`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/538)
=> Refactor: use Joint in Leader state, instead of EffectiveMembership

openraft/snapshot_le_last_applied.rs, openraft/src/core/install_snapshot.rs
Otherwise, the state machine will revert to an older state, while the
in-memory `last_applied` is unchanged.
This finally causes logs that fall in range `(snapshot.last_log_id, last_applied]` can not be applied.
**Checklist**
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/543)
=> Fix: snapshot with smaller last_log_id than last_applied should not be installed

.github/workflows/ci.yaml, openraft/src/core/append_entries.rs, openraft/src/core/install_snapshot.rs
The conflicting logs that are before `snapshot_meta.last_log_id` should
be deleted before installing a snapshot.
Otherwise, there is a chance the snapshot is installed but conflicting logs
are left in the store, when a node crashes.
**Checklist**
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/561)
=> Fix: potential inconsistency when installing a snapshot

openraft/src/core/install_snapshot.rs, openraft/src/core/raft_core.rs, openraft/src/engine/engine_impl.rs, openraft/src/entry.rs
During jepsen testing our little raft cluster, we found it regularly panicking upon network splits. It was hitting the assert given in the handling of `AppendEntriesResponse::HigherVote(vote)`. For some reason the current state `vote` was higher than the one reported in the `HigherVote` response.
It looks reasonable to only warn when the current vote is higher or equal to the one reported, assuming the raft engine will be in a valid state. But I am not 100% sure this is true. Any guidance is welcome.
Instead of panicking this PR tries to return the appropriate errors.
**Checklist**
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/564)
=> Fix: Try to handle `AppendResponse::HigherVote` more correctly

rocksstore/Cargo.toml, rocksstore/src/lib.rs
Updates the requirements on [rocksdb](https://github.com/rust-rocksdb/rust-rocksdb) to permit the latest version.
- [Release notes](https://github.com/rust-rocksdb/rust-rocksdb/releases)
- [Changelog](https://github.com/rust-rocksdb/rust-rocksdb/blob/master/CHANGELOG.md)
- [Commits](https://github.com/rust-rocksdb/rust-rocksdb/compare/v0.18.0...v0.19.0)
---
updated-dependencies:
- dependency-name: rocksdb
dependency-type: direct:production
...
Signed-off-by: dependabot[bot] <support@github.com>
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/579)
=> Build(deps): Update rocksdb requirement from 0.18.0 to 0.19.0

openraft/src/core/admin.rs, openraft/src/core/client.rs, openraft/src/core/mod.rs, openraft/src/error.rs, openraft/src/raft.rs, openraft/tests/membership/main.rs, openraft/tests/membership/t20_change_membership.rs, openraft/tests/membership/t21_change_membership_keep_learner.rs
If `blocking` is `true`, `Raft::change_membership(..., blocking)` will
block until replication to new nodes become up to date.
But it won't return an error when proposing a change-membership log.
- Change: remove two errors: `LearnerIsLagging` and `LearnerNotFound`.
- Fix: #581
- Part of https://github.com/datafuselabs/databend/issues/8386
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/582)
=> Change: change-membership does not return error when replication lags

openraft/src/core/raft_core.rs, openraft/src/error.rs, openraft/src/membership/membership.rs, openraft/src/membership/membership_test.rs
Because in a membership the type `Node` is not an `Option` any more,
`MissingNodeInfo` error will never occur.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/590)
=> Change: remove error MissingNodeInfo

openraft/src/core/raft_core.rs, openraft/src/membership/effective_membership.rs, openraft/src/membership/membership.rs
`EffectiveMembership::get_node()` should return an `Option<&Node>`
instead of a `&Node`.
Otherwise it panic if the node is not found.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/593)
=> Change: EffectiveMembership::get_node() should return an Option

openraft/src/core/raft_core.rs, openraft/tests/fixtures/mod.rs, openraft/tests/membership/main.rs, openraft/tests/membership/t30_remove_leader.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/594)
=> Fix: when responding ForwardToLeader, make `leader_id` a None if the leader is no longer in the cluster

openraft/src/core/raft_core.rs, openraft/src/engine/engine_impl.rs, openraft/tests/membership/t30_remove_leader.rs
When a membership that removes the leader is committed,
the leader continue to work for a short while before reverting to a learner.
This way, let the leader replicate the `membership-log-is-committed` message to followers.
Otherwise, if the leader step down at once, the follower might have to re-commit the membership log
again.
After committing the membership log that does not contain the leader,
the leader will step down in the next `tick`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/598)
=> Fix: delay leader step down

examples/raft-kv-rocksdb/src/store.rs, openraft/src/engine/engine_impl.rs, openraft/src/leader/leader.rs, openraft/src/progress/bench/vec_progress_update.rs, openraft/src/progress/mod.rs
The leader must keep track of addtional information such as the
`max_possible_matche` index, in order to give `Engine` full control over
replication.
This is the first step to extend Progress to hold complete replication
state: the `matching` log id and the `max_possible_matching` log index.
I.e., progress should be `Progress<ID, (Option<LogId>, Option<LogIndex>), _>`.
Because `max_possible_matching` is decided by the leader, the default
value of a progress entry must be specified when it is created.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/601)
=> Refactor: specify the default value when building Progress

openraft/src/core/raft_core.rs, openraft/src/engine/command.rs, openraft/src/engine/engine_impl.rs, openraft/src/engine/handle_vote_resp_test.rs, openraft/src/engine/leader_append_entries_test.rs, openraft/src/engine/update_effective_membership_test.rs, openraft/src/leader/leader.rs, openraft/src/progress/entry.rs, openraft/src/progress/mod.rs, openraft/src/raft_state.rs, openraft/src/replication/mod.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/603)
=> Refactor: add ProgressEntry as a container of replication state

openraft/src/core/raft_core.rs, openraft/tests/life_cycle/main.rs, openraft/tests/life_cycle/t90_issue_607_single_restart.rs
A node should not set `server_state` to `Leader` when just starting up,
even when it's the only voter in a cluster. It still needs several step
to initialize leader related fields to become a leader.
- Fix: #607
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/609)
=> Fix: become non-leader when restarting single node cluster

openraft/src/core/raft_core.rs, openraft/src/engine/command.rs, openraft/src/engine/elect_test.rs, openraft/src/engine/engine_impl.rs, openraft/src/engine/follower_do_append_entries_test.rs, openraft/src/engine/handle_append_entries_req_test.rs, openraft/src/engine/handle_vote_req_test.rs, openraft/src/engine/handle_vote_resp_test.rs, openraft/src/engine/initialize_test.rs, openraft/src/engine/internal_handle_vote_req_test.rs, openraft/src/engine/mod.rs, openraft/src/engine/startup_test.rs, openraft/src/engine/truncate_logs_test.rs, openraft/src/engine/update_committed_membership_test.rs, openraft/src/engine/update_effective_membership_test.rs, openraft/src/raft.rs
A runtime(RaftCore) should always run in a passive mode and should not
depend on `server_state` to run.
`engine.state.server_state` should be only used for metrics reporting.
Flow control does not depend on it. Because `server_state` is a
duplicated information in `Engine`, and using it makes it difficult to
verify that it is consistent with other fields.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/610)
=> Refactor: replace Command::UpdateServerState with BecomeLeader and QuitLeader

openraft/src/engine/elect_test.rs, openraft/src/engine/engine_impl.rs, openraft/src/engine/follower_do_append_entries_test.rs, openraft/src/engine/handle_append_entries_req_test.rs, openraft/src/engine/handle_vote_req_test.rs, openraft/src/engine/initialize_test.rs, openraft/src/engine/install_snapshot_test.rs, openraft/src/engine/internal_handle_vote_req_test.rs, openraft/src/engine/leader_append_entries_test.rs, openraft/src/engine/truncate_logs_test.rs, openraft/src/engine/update_committed_membership_test.rs, openraft/src/engine/update_effective_membership_test.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/611)
=> Refactor: do not emit QuitLeader command when switch between non-leader states

openraft/src/core/raft_core.rs, openraft/src/engine/engine_impl.rs, openraft/src/progress/entry.rs, openraft/src/raft.rs, openraft/src/replication/mod.rs, openraft/src/replication/replication_session_id.rs
Provide methods to update a matching log id or conflicting log index that
is found on the replication target node.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/612)
=> Refactor: ProgressEntry: support updating matching and conflict

openraft/src/config/config.rs, openraft/src/config/config_test.rs, openraft/src/core/raft_core.rs, openraft/src/core/snapshot_state.rs, openraft/src/raft.rs, openraft/src/replication/mod.rs, openraft/tests/membership/t10_add_learner.rs
`replication_lag_threshold >= config.SnapshotPolicy.LogsSinceLast`
should be held;
Asking for a snapshot only when a follower behind the `committed` index by `replication_lag_threshold`.
When a ReplicationCore asks RaftCore for a snapshot, RaftCore just
sends back the last built snapshot, it does not have to build a new one.
ReplciationCore guarantees it asks for a snapshot only when the last
snapshot fulfill its need: i.e., when it tries to replicate a purged
log(which must be included in the last snapshot).
When `ReplicationCore` asks for a snapshot for replication, `RaftCore`
could just gives it the last built one. There is never need to rebuild
one. Because a log won't be purged until a snapshot including it is
built.
- - - …
=> simplify snapshot replication

openraft/src/core/raft_core.rs, openraft/src/progress/entry.rs, openraft/src/raft.rs, openraft/src/replication/mod.rs
ReplicationCore stores the most recent matching log id and max possible
matching log index in a `ProgressEntry`, which contains progress
related information and operations.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/614)
=> Refactor: use ProgressEntry to store replication progress

.github/workflows/ci.yaml, Makefile, examples/raft-kv-memstore/src/client.rs, examples/raft-kv-memstore/src/lib.rs, examples/raft-kv-memstore/src/network/raft_network_impl.rs, examples/raft-kv-memstore/tests/cluster/test_cluster.rs, openraft/src/core/raft_core.rs
On Linux: command `cargo run` pollutes environment variables: It leaks
`SSL_CERT_FILE` and `SSL_CERT_DIR` to the testing sub progress it runs.
Which cause `reqwest` spending ~50 ms loading the certificates for every
RPC.
We just extend the RPC timeout to work around.
- Fix: #550
- Test examples on debug level. Initialize logging for example
- Add timeout control to client in the example. Do not let it block for
ever.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/615)
=> Fix: workaround cargo leaking SSL_CERT_FILE issue

openraft/src/core/install_snapshot.rs, openraft/src/core/raft_core.rs, openraft/src/core/snapshot_state.rs
Before starting a new snapshot streaming, the previous building task has
to be finished. Otherwise there might be race condition that streaming a
snapshot and building a snapshot may be done in arbitrary order, i.e.,
old data overrides new data.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/621)
=> Refactor: serialize snapshot building and streaming

examples/raft-kv-memstore/tests/cluster/test_cluster.rs, examples/raft-kv-rocksdb/src/network/raft_network_impl.rs, openraft/src/error.rs, openraft/src/replication/mod.rs, openraft/tests/fixtures/mod.rs
A node is stored in `Membership` thus it should always be found.
Otherwise it is a bug of openraft.
In either case, there is no need for an application to deal with
`RPCError::NodeNotFound` error.
An application that needs such an error should define it as an
application error.
- Migration guide:
if you do have been using it, you could just replace `NodeNotFound` with `NetworkError`.
- Fix: #623
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/624)
=> Change: remove error NodeNotFound

openraft/src/error.rs, openraft/src/replication/mod.rs
Replace `ReplicationError::{Timeout, Network, RemoteError}` with
`ReplicationError::RPCError`. Because these three errors are dealt with
in the same way.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/625)
=> Refactor: add ReplicationError::RPCError

openraft/src/core/raft_core.rs, openraft/src/engine/calc_purge_upto_test.rs, openraft/src/engine/engine_impl.rs, openraft/src/engine/install_snapshot_test.rs, openraft/src/engine/update_snapshot_test.rs, openraft/src/raft_state.rs, openraft/src/storage/helper.rs
Snapshot meta should be part of the `RaftState`.
Move it from `Engine` to `RaftState`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/627)
=> Change: RaftState: add field snapshot_meta

openraft/src/engine/engine_impl.rs, openraft/src/engine/follower_do_append_entries_test.rs, openraft/src/engine/handle_append_entries_req_test.rs, openraft/src/engine/initialize_test.rs, openraft/src/engine/leader_append_entries_test.rs, openraft/src/engine/purge_log_test.rs, openraft/src/engine/truncate_logs_test.rs, openraft/src/raft_state.rs, openraft/src/raft_state_test.rs, openraft/src/raft_types.rs, openraft/src/testing/suite.rs
Returns `Option<&LogId>` instead of `Option<LogId>`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/628)
=> Refactor: RaftState::last_log_id() and RaftState::last_purged_log_id() returns an ref of log-id

openraft/src/core/raft_core.rs, openraft/src/engine/engine_impl.rs, openraft/src/engine/follower_do_append_entries_test.rs, openraft/src/engine/handle_append_entries_req_test.rs, openraft/src/engine/initialize_test.rs, openraft/src/engine/leader_append_entries_test.rs, openraft/src/engine/purge_log_test.rs, openraft/src/engine/truncate_logs_test.rs, openraft/src/raft_state.rs, openraft/src/raft_state_test.rs, openraft/src/testing/suite.rs
Openraft components need information of significant log ids to
function, there should be a standard interface for them to read these
log ids.
```
old                           new
øøøøøøLLLLLLLLLLLLLLLLLLLL
+----+----+----+----+----+--->
|    |    |    |    |
|    |    |    |    '--- last_log_id
|    |    |    '-------- committed
|    |    '------------- applied
|    '------------------ snapshot_last_log_id
'----------------------- last_purged_log_id
```
- See: https://datafuselabs.github.io/openraft/log-data-layout
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/630)
=> Refactor: add trait LogStateReader to define API for getting log ids reflecting the raft state

openraft/src/core/raft_core.rs, openraft/src/engine/command.rs, openraft/src/engine/engine_impl.rs, openraft/src/engine/update_progress_test.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/632)
=> Refactor: make replication metrics update an engine command

openraft/src/progress/mod.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/633)
=> Refactor: add Progress::get_mut to return a mutable reference to a value

openraft/src/core/raft_core.rs, openraft/src/engine/elect_test.rs, openraft/src/engine/engine_impl.rs, openraft/src/engine/handle_vote_req_test.rs, openraft/src/engine/handle_vote_resp_test.rs, openraft/src/engine/internal_handle_vote_req_test.rs, openraft/src/engine/leader_append_entries_test.rs, openraft/src/engine/update_effective_membership_test.rs, openraft/src/engine/update_progress_test.rs, openraft/src/raft_state.rs, openraft/src/storage/helper.rs
The leading state data is independent of following state data, i.e., a
traditional raft leader has leading state data(replication state,
progress etc) and following state data(logs, snapshot), and  a
traditional follower has only following state data, an leading state can
also exist without following state data.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/635)
=> Refactor: move leading state out of RaftState

openraft/src/core/raft_core.rs, openraft/src/engine/elect_test.rs, openraft/src/engine/engine_impl.rs, openraft/src/engine/follower_commit_entries_test.rs, openraft/src/engine/follower_do_append_entries_test.rs, openraft/src/engine/handle_append_entries_req_test.rs, openraft/src/engine/handle_vote_req_test.rs, openraft/src/engine/handle_vote_resp_test.rs, openraft/src/engine/initialize_test.rs, openraft/src/engine/install_snapshot_test.rs, openraft/src/engine/internal_handle_vote_req_test.rs, openraft/src/engine/leader_append_entries_test.rs, openraft/src/engine/purge_log_test.rs, openraft/src/engine/startup_test.rs, openraft/src/engine/truncate_logs_test.rs, openraft/src/engine/update_committed_membership_test.rs, openraft/src/engine/update_effective_membership_test.rs, openraft/src/engine/update_progress_test.rs, openraft/src/engine/update_snapshot_test.rs
This way to output commands does not depend on the entire Engine.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/637)
=> Refactor: move Engine output entries to Engine.output

openraft/src/core/raft_core.rs, openraft/src/core/server_state.rs, openraft/src/engine/engine_impl.rs, openraft/src/engine/handle_vote_resp_test.rs, openraft/src/engine/mod.rs, openraft/src/engine/startup_test.rs, openraft/src/engine/vote_handler.rs, openraft/tests/life_cycle/t90_issue_607_single_restart.rs
- Test: single-node restart test does not expect the node to run
election any more.
- Refactor: add VoteHandler to handle vote related operations.
- Change: make ServerState default value `Learner`.
- Fix: #607
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/640)
=> Change: A restarted leader should enter leader state at once, without another round of election

openraft/src/engine/calc_purge_upto_test.rs, openraft/src/engine/elect_test.rs, openraft/src/engine/engine_impl.rs, openraft/src/engine/follower_commit_entries_test.rs, openraft/src/engine/follower_do_append_entries_test.rs, openraft/src/engine/handle_append_entries_req_test.rs, openraft/src/engine/handle_vote_req_test.rs, openraft/src/engine/handle_vote_resp_test.rs, openraft/src/engine/handler/snapshot_handler.rs, openraft/src/engine/initialize_test.rs, openraft/src/engine/install_snapshot_test.rs, openraft/src/engine/internal_handle_vote_req_test.rs, openraft/src/engine/leader_append_entries_test.rs, openraft/src/engine/purge_log_test.rs, openraft/src/engine/truncate_logs_test.rs, openraft/src/engine/update_progress_test.rs, openraft/src/lib.rs, openraft/src/raft.rs, openraft/src/raft_state.rs, openraft/src/raft_state_test.rs, openraft/src/storage/helper.rs, openraft/src/storage/mod.rs, openraft/src/valid/bench/mod.rs, openraft/src/valid/bench/valid_deref.rs, openraft/src/valid/mod.rs, openraft/src/valid/valid_impl.rs
- Fix: `last_purged_log_id` should be `None`, but not `LogId{index=0,
..}` when raft startup with a store with log at index 0.
This is fixed by adding another field `next_purge` to distinguish
`last_purged_log_id` value `None` and `LogId{index=0, ..}`, because
`RaftState.log_ids` stores `LogId` but not `Option<LogId>`.
- Add a wrapper `Valid<RaftState>` of `RaftState` to check if the state
is valid every time accessing it. This check is done only when
`debug_assertions` is turned on.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/643)
=> Fix: last_purged_log_id is not loaded correctly

openraft/src/lib.rs, openraft/src/log_id_range.rs, openraft/src/progress/inflight.rs, openraft/src/progress/mod.rs
But it is not used anywhere until replication progress control is moved
from `ReplicationCore` to `Engine`. `Inflight` will be part of the
**progress** data.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/646)
=> Feature: add "Inflight" to store info about inflight replication data

openraft/src/raft_state.rs, openraft/src/raft_state_test.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/648)
=> Improve: add LogStateReader::prev_log_id() to return a log id at specfied index-1

openraft/src/engine/engine_impl.rs, openraft/src/engine/handler/replication_handler.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/656)
=> Refactor: move append_blank_log() to ReplicationHandler

openraft/src/core/raft_core.rs, openraft/src/engine/command.rs, openraft/src/engine/elect_test.rs, openraft/src/engine/engine_impl.rs, openraft/src/engine/handle_vote_resp_test.rs, openraft/src/engine/handler/replication_handler.rs, openraft/src/engine/initialize_test.rs, openraft/src/engine/leader_append_entries_test.rs, openraft/src/engine/leader_append_membership_test.rs, openraft/src/engine/startup_test.rs
Writing to local log store is different from writing to remote.
Local writing is serialized by the runtime(RaftCore) and can be
fast-committed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/657)
=> Refactor: add ReplicationHandler::update_local_progress() to update progress just for local node

openraft/tests/fixtures/mod.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/659)
=> Improve: panic hook for integration test should print error message to stderr, not only record it in log file

openraft/src/core/install_snapshot.rs, openraft/src/core/raft_core.rs, openraft/src/engine/elect_test.rs, openraft/src/engine/engine_impl.rs, openraft/src/engine/handle_append_entries_req_test.rs, openraft/src/engine/handle_vote_req_test.rs, openraft/src/engine/handle_vote_resp_test.rs, openraft/src/engine/handler/following_handler.rs, openraft/src/engine/handler/replication_handler.rs, openraft/src/engine/handler/vote_handler.rs, openraft/src/raft.rs, openraft/src/raft_state.rs, openraft/src/testing/suite.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/664)
=> Refactor: FollowingHandler split logic

Cargo.toml, openraft/Cargo.toml, openraft/src/core/install_snapshot.rs, openraft/src/core/raft_core.rs, openraft/src/engine/command.rs, openraft/src/engine/engine_impl.rs, openraft/src/engine/handler/replication_handler.rs, openraft/src/engine/handler/vote_handler.rs, openraft/src/error.rs, openraft/src/lib.rs, openraft/src/raft.rs, openraft/src/runtime/mod.rs
Sending rpc(vote, append-entries and install-snapshot) response must be
after executing the commands generated by Engine.
Thus introduce `Command` for doing such actions, e.g., `tx.send(res)`.
Command execution can be reordered or batched for performance.
Because `oneshot::Sender` is not `Clone`, `Command` and other related types that includes it are adjusted.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/667)
=> Improve: make sending rpc-response a command and enqueue it in the command list

Cargo.toml, openraft/Cargo.toml, openraft/src/core/raft_core.rs, openraft/src/engine/command.rs, openraft/src/engine/mod.rs, openraft/src/error.rs
Refactor: ExtractFatal is not used any more. Fatal error should only be
raised by Command executor, no more by API handler. There is no need to
extract Fatal error from an API error.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/668)
=> Fix: check_is_leader() should return at once if encountering StorageError

openraft/src/core/raft_core.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/669)
=> Fix: a stepped down leader should ignore replication progress message

examples/raft-kv-memstore/src/client.rs, examples/raft-kv-memstore/src/lib.rs, examples/raft-kv-memstore/src/network/api.rs, examples/raft-kv-memstore/src/network/raft_network_impl.rs, examples/raft-kv-memstore/tests/cluster/test_cluster.rs, examples/raft-kv-rocksdb/src/client.rs, examples/raft-kv-rocksdb/src/network/raft_network_impl.rs, openraft/src/engine/command.rs, openraft/src/engine/engine_impl.rs, openraft/src/engine/initialize_test.rs, openraft/src/error.rs, openraft/src/lib.rs, openraft/src/network.rs, openraft/src/raft.rs, openraft/src/try_as_ref.rs, openraft/tests/fixtures/mod.rs, openraft/tests/life_cycle/t20_initialization.rs, openraft/tests/life_cycle/t20_shutdown.rs, openraft/tests/membership/t20_change_membership.rs, openraft/tests/membership/t30_remove_leader.rs
Add `RaftError<E>` as error type returned by every `Raft::xxx()` API.
RaftError has two variants: Fatal error or API specific error.
This way every API error such as AppendEntriesError does not have to include
an `Fatal` in it.
Upgrade tip:
The affected types is mainly `trait RaftNetwork`, an application should
replace AppendEntriesError, VoteError, InstallSnapshotError with
`RaftError<_>`, `RaftError<_>`, and `RaftError<_, InstallSnapshotError>`.
So is for other parts, e.g., `Raft::append_entries()` now returns
`Result<AppendEntriesResponse, RaftError<_>>`, an application should
also rewrite error handling that calls these APIs.
See changes in examples/.
Such an error can only be caused by internal calls. An application do
not need to handle it.
- - - …
=> Change: add RaftError as API return error type.

rocksstore/Cargo.toml
Updates the requirements on [rocksdb](https://github.com/rust-rocksdb/rust-rocksdb) to permit the latest version.
- [Release notes](https://github.com/rust-rocksdb/rust-rocksdb/releases)
- [Changelog](https://github.com/rust-rocksdb/rust-rocksdb/blob/master/CHANGELOG.md)
- [Commits](https://github.com/rust-rocksdb/rust-rocksdb/compare/v0.19.0...v0.20.1)
---
updated-dependencies:
- dependency-name: rocksdb
dependency-type: direct:production
...
Signed-off-by: dependabot[bot] <support@github.com>
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/672)
=> Build(deps): Update rocksdb requirement from 0.19.0 to 0.20.1

openraft/src/engine/engine_impl.rs, openraft/src/error.rs, openraft/src/raft_state.rs, openraft/src/raft_state_test.rs, openraft/src/vote/vote.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/675)
=> Refactor: move assign_log_ids() to RaftState, add method to build a ForwardToLeader error

examples/raft-kv-memstore/src/client.rs, examples/raft-kv-memstore/src/lib.rs, examples/raft-kv-rocksdb/src/client.rs, openraft/src/core/raft_core.rs, openraft/src/error.rs, openraft/src/raft.rs, openraft/tests/fixtures/mod.rs, openraft/tests/membership/t10_add_learner.rs
In openraft adds a learner is done by committing a membership config
log, which is almost the same as committing any log.
`AddLearnerResponse` contains a field `matched` to indicate the
replication state to the learner, which is not included in
`ClientWriteResponse`. This information can be retrieved via
`Raft::metrics()`.
Therefore to keep the API simple, replace `AddLearnerResponse` with
`ClientWriteResponse`.
Behavior change: adding a learner always commit a new membership config
log, no matter if it already exists in membership.
To avoid duplicated add, an application should check existence first by
examining `Raft::metrics()`
- Fix: #679
Upgrade tips:
- Replace AddLearnerResponse with ClientWriteResponse
- Replace AddLearnerError with ClientWriteError
Passes the application …
=> Change: remove AddLearnerResponse and AddLearnerError

.github/workflows/ci.yaml, examples/raft-kv-memstore/tests/cluster/test_cluster.rs, examples/raft-kv-rocksdb/Cargo.toml
For toy-rpc, use `serde_json` instead of the default `serde_bincode`:
`bincode` which enabled by default by toy-rpc, does not support
`#[serde(flatten)]`:
See: https://docs.rs/bincode/2.0.0-alpha.1/bincode/serde/index.html#known-issues
- Fix: #677
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/681)
=> Refactor: enable `serde_json` for toy-rpc

openraft/src/core/raft_core.rs, openraft/src/membership/membership_state.rs, openraft/src/membership/membership_state_test.rs
The function checks if the current effective membership configuration is
committed to the Raft log or not.
If it is committed, the function returns `Ok()`, otherwise, it returns an
error `Err(InProgress)`.
`create_updated_membership()` has been modified to use the new
`ensure_last_membership_committed()` to validate the committed and effective
configurations of the membership before building a new membership
configuration.
If the committed and effective membership configurations are not the
same, the `create_updated_membership()` function now returns a
`ChangeMembershipError::InProgress` error.
The patch also adds new tests to test the new
`ensure_last_membership_committed()` and modified `create_updated_membership()`
functions.
- - - …
=> Refactor: Adds a new method `ensure_last_membership_committed()` to the `MembershipState`

openraft/src/change_members.rs, openraft/src/core/raft_core.rs, openraft/src/membership/change_handler.rs, openraft/src/membership/membership.rs, openraft/src/membership/membership_state.rs, openraft/src/membership/membership_state_test.rs, openraft/src/membership/membership_test.rs, openraft/src/membership/mod.rs, openraft/src/quorum/coherent.rs, openraft/src/quorum/coherent_impl.rs, openraft/src/quorum/coherent_test.rs, openraft/src/raft.rs, openraft/tests/membership/t10_add_learner.rs, openraft/tests/membership/t16_change_membership_cases.rs, openraft/tests/membership/t20_change_membership.rs
Previously, when adding a learner to a Raft cluster, the last membership was not
always marked as committed, which could cause issues when a follower tried to
truncate logs by reverting to the last committed membership. To prevent this
issue, we have updated the code to ensure the last membership is committed when
adding a learner.
In addition to this fix, we have also made several refactoring changes,
including refining method names for trait `Coherent`, renaming
`Membership::next_safe()` to `next_coherent()` for consistency, and updating
enum `ChangeMembers` to include more variants for adding and removing learners.
We have also removed `RaftCore::add_learner()` in favor of using
`change_membership()` for all membership operations, and added a `ChangeHandler`
to build new membership …
=> Fix: when adding a learner, ensure the last membership is committed

openraft/src/core/raft_core.rs, openraft/src/replication/mod.rs, openraft/src/storage/helper.rs, openraft/src/storage/mod.rs, openraft/src/testing/suite.rs, openraft/tests/append_entries/t20_append_conflicts.rs, openraft/tests/append_entries/t30_append_inconsistent_log.rs, openraft/tests/life_cycle/t20_initialization.rs, openraft/tests/log_compaction/t10_compaction.rs, openraft/tests/membership/t10_add_learner.rs, openraft/tests/membership/t20_change_membership.rs, openraft/tests/membership/t99_new_leader_auto_commit_uniform_config.rs, openraft/tests/snapshot/t42_snapshot_uses_prev_snap_membership.rs
Function `get_log_entries()` and `try_get_log_entry()` are provided by
trait `RaftLogReader` with default implementations. However, they do not
need to be part of this trait and an application does not have to
implement them.
Therefore in this patch they are moved to `StorageHelper` struct, which
provides additional storage access methods that are built based on the
`RaftStorage` trait.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/686)
=> Change: move default implemented method from trait `RaftLogReader` to `StorageHelper`

Cargo.toml, guide/src/feature-flags.md, openraft/Cargo.toml, openraft/src/compat/compat07.rs, openraft/src/compat/mod.rs, openraft/src/compat/testing.rs, openraft/src/compat/upgrade.rs, openraft/src/lib.rs, openraft/src/node.rs, rocksstore-compat07/Cargo.toml, rocksstore-compat07/README.md, rocksstore-compat07/src/compatibility_test.rs, rocksstore-compat07/src/lib.rs, rocksstore-compat07/src/test.rs, rocksstore/Cargo.toml
This is an example `RaftStorage` implementation that can read persistent
data written by either v0.7.4 or v0.8 the latest version openraft.
It is serves as an demostration for applications upgrades from 0.7 to
0.8 .
./rocksstore-compat07 is built with openraft 0.8, in the tests, it reads
data written by rocksstore 0.7.4, whichi is built with openraft 0.7.4 .
In this patch, openraft provides a compatibility layer:
mod `openraft::compat::compat07`, which defines several compatible types
that can be deserialized from v0.7 or v0.8 data, such as
`compat07::LogId` or `compat07::Membership`.
These types will helper users upgrade their application to latest
openraft.
Because openraft 0.8 introduced several generic types, such as `NodeId`
and `Node`, and feature `serde` became an optional feature, …
=> Feature: add v07-v08 compatible store rocksstore-compat07

Cargo.toml, Makefile, memstore/Cargo.toml, openraft/src/core/raft_core.rs, openraft/src/lib.rs, rocksstore-compat07/Cargo.toml, rocksstore/Cargo.toml, sledstore/Cargo.toml
- Fix: #703
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/704)
=> Improve: AppDataResponse does not need a Clone trait bound

openraft/src/lib.rs, openraft/src/raft_state.rs, openraft/src/rust_state_validate_test.rs
A application may not persist snapshot. And when it restarted, the
last-purged-log-id is not `None` but `snapshot_last_log_id()` is None.
This is a valid state and should not emit error.
- An unexpected panic is found in https://github.com/datafuselabs/databend/pull/10480 :
- The failed CI: https://github.com/datafuselabs/databend/actions/runs/4381716399/jobs/7670145716#step:4:3109
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/707)
=> Improve: loosen validity check with RaftState.snapshot_last_log_id()

openraft/src/core/install_snapshot.rs, openraft/src/core/raft_core.rs, openraft/src/engine/elect_test.rs, openraft/src/engine/engine_impl.rs, openraft/src/engine/handle_append_entries_req_test.rs, openraft/src/engine/handle_vote_req_test.rs, openraft/src/engine/handle_vote_resp_test.rs, openraft/src/engine/handler/replication_handler.rs, openraft/src/engine/handler/vote_handler.rs, openraft/src/raft.rs, openraft/src/raft_state.rs, openraft/src/testing/suite.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/709)
=> Refactor: rename RaftState.get_vote() to vote_ref()

openraft/src/engine/engine_impl.rs, openraft/src/engine/handler/vote_handler/mod.rs, openraft/src/membership/effective_membership.rs, openraft/src/membership/into_nodes.rs, openraft/src/membership/membership.rs, openraft/src/membership/membership_test.rs, openraft/src/membership/mod.rs, openraft/src/membership/node_type.rs, openraft/src/raft.rs
`Membership::contains()` is unclear about whether a voter or learner it
is queried for. It is removed and an application uses `is_voter()`,
`is_learner()`, `get_node().is_some()` instead.
`NodeRole` is removed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/713)
=> Refactor: refine Membership API doc

.github/workflows/commit-message-check.yml, README.md, scripts/build_change_log.py, scripts/change-types.yaml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/714)
=> CI: add change type "DataChange:" for commit that introduces on-disk data type changes that may require manual updrade

.github/workflows/ci.yaml, openraft/src/core/raft_core.rs, openraft/src/raft.rs, openraft/src/validate/bench/valid_deref.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/718)
=> Refactor: RaftMsg::ClientWriteRequest does not require an `EntryPayload`, and can instead be simplified to only include an `AppData`.

openraft/src/feature_serde_test.rs, openraft/src/lib.rs, openraft/src/vote/leader_id/leader_id_adv.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/722)
=> Improve: add trait OptionalSerde as a global containing trait of optional serde traits

openraft/src/lib.rs, openraft/src/log_id/mod.rs
- Fix: #725
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/726)
=> Fix: trait RaftLogId should be public

memstore/src/test.rs, openraft/src/testing/store_builder.rs, openraft/src/testing/suite.rs, rocksstore-compat07/src/test.rs, rocksstore/src/test.rs, sledstore/src/test.rs
`StoreBuilder::run_test()` is removed, and a new method `build()` is
added. To test a `RaftStorage` implementation, just implementing
`StoreBuilder::build()` is enough now. It returns a store instance and a
**guard**, for disk backed store to clean up the data when the guard is
dropped.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/730)
=> Change: StoreBuilder does not need to run a test, it only needs to build a store

openraft/src/core/raft_core.rs, openraft/src/engine/command.rs, openraft/src/engine/engine_impl.rs, openraft/src/engine/handle_append_entries_req_test.rs, openraft/src/engine/handler/following_handler/do_append_entries_test.rs, openraft/src/engine/handler/following_handler/mod.rs, openraft/src/engine/handler/leader_handler/append_entries_test.rs, openraft/src/engine/handler/leader_handler/mod.rs, openraft/src/engine/initialize_test.rs
The input entries buffer can not be shared by RaftCore and IO-worker,
thus `Command::AppendInputEntries` implies consuming the input.
The `AppendInputEntries` command moves entries from the input buffer to
IO-worker which makes them consumed and invalid for further use.
Therefore, there is no longer a need to manage the input buffer's cursor
using `MoveInputCursorBy`, when `AppendInputEntries` is executed.
- Fix: #733
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/734)
=> Refactor: Remove Command::MoveInputCursorBy

openraft/src/core/raft_core.rs, openraft/src/engine/elect_test.rs, openraft/src/engine/engine_impl.rs, openraft/src/engine/handle_append_entries_req_test.rs, openraft/src/engine/handle_vote_req_test.rs, openraft/src/engine/handle_vote_resp_test.rs, openraft/src/engine/handler/following_handler/commit_entries_test.rs, openraft/src/engine/handler/following_handler/do_append_entries_test.rs, openraft/src/engine/handler/following_handler/install_snapshot_test.rs, openraft/src/engine/handler/following_handler/truncate_logs_test.rs, openraft/src/engine/handler/following_handler/update_committed_membership_test.rs, openraft/src/engine/handler/leader_handler/append_entries_test.rs, openraft/src/engine/handler/leader_handler/send_heartbeat_test.rs, openraft/src/engine/handler/log_handler/purge_log_test.rs, openraft/src/engine/handler/replication_handler/append_membership_test.rs, openraft/src/engine/handler/replication_handler/update_matching_test.rs, openraft/src/engine/handler/server_state_handler/update_server_state_test.rs, openraft/src/engine/handler/snapshot_handler/update_snapshot_test.rs, openraft/src/engine/handler/vote_handler/handle_message_vote_test.rs, openraft/src/engine/initialize_test.rs, openraft/src/engine/startup_test.rs
Using a `VecDeque` for output commands buffer so that it does not need
to allocate a new `Vec` every time running the commands.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/736)
=> Refactor: replace Vec with VecDeque for Engine output commands type

openraft/src/core/install_snapshot.rs, openraft/src/core/raft_core.rs, openraft/src/raft.rs, openraft/src/runtime/mod.rs, tests/Cargo.toml
`RaftCore.input_entries` stores input log entries to be appended.
These entries comes from user calls to `RaftCore::client_write` for a leader, or
`RaftCore::append_entries` for a follower or learner.
`input_entries` serves as the sole storage for all log entries that are pending to be
written to `RaftStorage`. Group committing will be done on this storage.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/737)
=> Refactor: add `input_entries` to RaftCore

memstore/src/lib.rs, openraft/src/entry/mod.rs, openraft/src/entry/payload.rs, openraft/src/lib.rs, tests/tests/append_entries/t20_append_conflicts.rs, tests/tests/append_entries/t40_append_updates_membership.rs, tests/tests/life_cycle/t20_initialization.rs
Application data `AppData` does not have to be `Clone`.
Upgrade tip:
Nothing needs to be done.
The default `RaftEntry` implementation `Entry` provided by openraft is
still `Clone`, if the AppData in it is `Clone`.
So that Entry does not need to be `Clone`. Therefore `Clone` can be
removed from `AppData`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/740)
=> Change: remove `Clone` from trait `AppData`

examples/raft-kv-memstore/src/store/mod.rs, examples/raft-kv-rocksdb/src/store.rs, memstore/src/lib.rs, openraft/src/core/raft_core.rs, openraft/src/storage/mod.rs, openraft/src/store_ext.rs, openraft/src/testing/suite.rs, rocksstore-compat07/src/lib.rs, rocksstore/src/lib.rs, sledstore/src/lib.rs, tests/tests/append_entries/t30_append_inconsistent_log.rs, tests/tests/elect/t10_elect_compare_last_log.rs, tests/tests/log_compaction/t10_compaction.rs, tests/tests/membership/t99_new_leader_auto_commit_uniform_config.rs, tests/tests/snapshot/t43_snapshot_delete_conflict_logs.rs
Using an `IntoIterator` is more generic than using a slice, and
could avoid potential memory allocation for the slice.
Upgrade tip:
Update the method signature in the `RaftStorage` implementation and
ensure it compiles successfully.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/742)
=> Change: instead of a slice, `RaftStorage::append_to_log()` now accepts an `IntoIterator`

openraft/src/core/install_snapshot.rs, openraft/src/core/raft_core.rs, tests/tests/append_entries/t50_append_entries_with_bigger_term.rs
It is not necessary for every message handler to run engine output
commands. Instead, the `runtime_loop()` can run these commands
immediately after processing a message.
access Engine more than once, such as snapshot handler.
They will be refactored in the upcoming commits
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/743)
=> Refactor: run engine commands after handling a message

openraft/src/core/raft_core.rs, openraft/src/engine/command.rs, openraft/src/engine/engine_impl.rs, openraft/src/engine/engine_output.rs, openraft/src/engine/handle_append_entries_req_test.rs, openraft/src/engine/handler/following_handler/do_append_entries_test.rs, openraft/src/engine/handler/following_handler/mod.rs, openraft/src/engine/handler/leader_handler/append_entries_test.rs, openraft/src/engine/handler/leader_handler/mod.rs, openraft/src/engine/handler/log_handler/mod.rs, openraft/src/engine/handler/replication_handler/mod.rs, openraft/src/engine/handler/server_state_handler/mod.rs, openraft/src/engine/handler/snapshot_handler/mod.rs, openraft/src/engine/handler/vote_handler/mod.rs, openraft/src/engine/initialize_test.rs, openraft/src/engine/testing.rs, openraft/src/raft.rs, openraft/src/raft_state/mod.rs, openraft/src/runtime/mod.rs
Previously the `input_entries` buffer is used to store the input log
entries for writing on a leader or replicating on a follower.
A Command that is generated by Engine only contains an index range to
indicate which log entries it uses.
This method is prone to error as the index and the entries need to be
carefully maintained to ensure consitency.
In this commit log entries are stored directly in a Command.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/746)
=> Refactor: embed log entries in Command

openraft/src/engine/handle_append_entries_req_test.rs, openraft/src/engine/handler/following_handler/append_entries_test.rs, openraft/src/engine/handler/following_handler/commit_entries_test.rs, openraft/src/engine/handler/following_handler/install_snapshot_test.rs, openraft/src/engine/handler/following_handler/mod.rs, openraft/src/raft_state/accepted.rs, openraft/src/raft_state/mod.rs, openraft/src/raft_state/tests/accepted_test.rs, openraft/src/storage/helper.rs
A follower stores the ID of the latest log that has been synchronized by
the leader, represented as `(LeaderId, Option<LogId>)`.
This information is only kept in memory and is not taken into account
when processing vote requests or determining the commit condition.
The reason for storing this information is to allow followers to commit
only those logs that have been replicated by their current leader.
- Fix: #747
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/748)
=> Improve: follower stores the accepted log id

openraft/src/core/raft_core.rs, openraft/src/display_ext.rs, openraft/src/engine/engine_impl.rs, openraft/src/engine/handler/following_handler/append_entries_test.rs, openraft/src/engine/handler/following_handler/commit_entries_test.rs, openraft/src/engine/handler/following_handler/mod.rs, openraft/src/engine/mod.rs, openraft/src/engine/tests/append_entries_test.rs, openraft/src/error.rs
When a follower receives an append-entries request that includes a
series of log entries to append and the log id that the leader
has committed, it responds with an append-entries response after
committing and applying the entries.
However, this is not strictly necessary. The follower could simply send
the response as soon as the log entries have been appended and flushed
to disk, without waiting for them to be committed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/751)
=> Improve: send AppendEntries response before committing entries

openraft/src/core/building_state.rs, openraft/src/core/install_snapshot.rs, openraft/src/core/mod.rs, openraft/src/core/raft_core.rs, openraft/src/core/snapshot_state.rs, openraft/src/core/streaming_state.rs, openraft/src/raft.rs
Although enabling snapshot building and streaming at the same time may
lead to inefficiencies, it enhances the clarity of the system's overall
structure. For instance, when processing a stream, there is
no need to handle any building state.
In this commit, a new `snapshot_state::State` is introduced that includes
both a building state and a streaming state.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/752)
=> Refactor: allow snapshot buillding and streaming at the same time

Cargo.toml, memstore/Cargo.toml, openraft/src/core/install_snapshot.rs, rocksstore/Cargo.toml
There may be log entries that are different from the ones applied to the
snapshot. Using these logs for replication leads to data damage.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/753)
=> Fix: when a snapshot is installed, all logs convered by snapshot should be purged

memstore/src/lib.rs, openraft/src/lib.rs, openraft/src/storage/mod.rs, openraft/src/store_ext.rs, tests/tests/metrics/t20_metrics_state_machine_consistency.rs
`RaftStorageDebug` has only one method `get_state_machine()`,
and state machine is entirely a user defined struct. Obtaining a state
machine does not imply anything about the struct or behavior of it.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/759)
=> Change: remove unused trait RaftStorageDebug

.github/workflows/ci.yaml, openraft/src/compat/compat07.rs, openraft/src/compat/compat07/entry.rs, openraft/src/compat/compat07/entry_payload.rs, openraft/src/compat/compat07/log_id.rs, openraft/src/compat/compat07/membership.rs, openraft/src/compat/compat07/snapshot_meta.rs, openraft/src/compat/compat07/stored_membership.rs, openraft/src/compat/compat07/vote.rs, openraft/src/compat/upgrade.rs, openraft/src/core/sm/mod.rs, openraft/src/storage/adapter.rs, openraft/src/storage/helper.rs, rocksstore-compat07/Cargo.toml, rocksstore-compat07/src/lib.rs, rocksstore-compat07/src/test.rs, tests/tests/snapshot/main.rs, tests/tests/snapshot/t20_startup_snapshot.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/768)
=> Fix: if the application does not persist snapshot, build a snapshot when starting up

openraft/src/core/raft_core.rs, openraft/src/raft.rs, openraft/src/raft_state/io_state.rs
Engine needs to decide when to build a snapshot thus the present
building snapshot state should be a field of `Engine.RaftState`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/769)
=> Refactor: let Engine track building_snapshot status

openraft/src/config/config.rs, openraft/src/core/raft_core.rs, openraft/src/engine/command.rs, openraft/src/engine/engine_config.rs, openraft/src/engine/engine_impl.rs, openraft/src/engine/handler/following_handler/mod.rs, openraft/src/engine/handler/mod.rs, openraft/src/engine/handler/replication_handler/mod.rs, openraft/src/engine/handler/sm_handler/mod.rs
Transfer the control of building-snapshot from `RaftCore` to `Engine`.
`RaftCore` functions as a passive runtime that only responds to
commands, while `Engine` is responsible for managing control flow
and making decisions.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/771)
=> Refactor: let Engine submit a building-snapshot command

.github/workflows/ci.yaml, Cargo.toml, guide/src/feature-flags.md, openraft/Cargo.toml, openraft/src/storage/mod.rs, openraft/src/storage/v2.rs, stores/README.md, stores/rocksstore-v2/Cargo.toml, stores/rocksstore-v2/README.md, stores/rocksstore-v2/src/lib.rs, stores/rocksstore-v2/src/test.rs
`storage-v2`: enables `RaftLogStorage` and `RaftStateMachine` as the v2 storage
This is a temporary feature flag, and will be removed in the future, when v2 storage is stable.
This feature disables `Adapter`, which is for v1 storage to be used as v2.
V2 storage separates log store and state machine store so that log IO and state machine IO can be parallelized naturally.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/777)
=> Refactor: add example stores/rocksstore using v2 storage

Cargo.toml, Makefile, README.md, cluster_benchmark/Cargo.toml, cluster_benchmark/tests/README.md, cluster_benchmark/tests/benchmark/bench_cluster.rs, cluster_benchmark/tests/benchmark/main.rs, cluster_benchmark/tests/benchmark/network.rs, cluster_benchmark/tests/benchmark/store.rs, cluster_benchmark/tests/benchmark/store/test.rs
The `cluster_benchmark` should be moved to a separate directory `cluster_benchmark/`.
Crate `cluster_benchmark` enables the `storage-v2` feature and utilizes a minimized
store and network for benchmarking purposes. The store and network has
been optimized to eliminate any unnecessary performance loss.
Benchmark result:
|  Date      | clients | put/s       | ns/op      |
| :--        | --:     | --:         | --:        |
| 2023-04-23 |  64     | **467,000** |    2,139   |
|            |   1     |    70,000   | **14,273** |
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/781)
=> Refactor: move cluster-benchmark to separate dir cluster_benchmark/

README.md, openraft/src/core/raft_core.rs
The performance increases by 40% with this optimization:
| clients | put/s       | ns/op      | Changes                    |
| --:     | --:         | --:        | :--                        |
|  64     | **652,000** |    1,532   | Reduce metrics report rate |
|  64     | **467,000** |    2,139   |                            |
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/782)
=> Improve: reduce rate to flush metrics

openraft/src/core/raft_core.rs, openraft/src/raft.rs, openraft/src/storage/mod.rs, openraft/src/storage/v2.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/786)
=> Chore: add doc comment to v2 storage api

openraft/src/core/raft_core.rs, openraft/src/engine/command.rs, openraft/src/engine/command_kind.rs, openraft/src/engine/handler/following_handler/commit_entries_test.rs, openraft/src/engine/handler/following_handler/mod.rs, openraft/src/engine/handler/leader_handler/append_entries_test.rs, openraft/src/engine/handler/replication_handler/mod.rs, openraft/src/engine/handler/replication_handler/update_matching_test.rs, openraft/src/engine/tests/elect_test.rs, openraft/src/engine/tests/initialize_test.rs
These two commands do exactly the same thing.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/788)
=> Refactor: merge Command::LeaderCommit and Command::FollowerCommit into one command `Apply`

openraft/src/core/raft_core.rs, openraft/src/engine/command.rs, openraft/src/engine/handler/following_handler/append_entries_test.rs, openraft/src/engine/handler/following_handler/commit_entries_test.rs, openraft/src/engine/handler/following_handler/do_append_entries_test.rs, openraft/src/engine/handler/following_handler/install_snapshot_test.rs, openraft/src/engine/handler/following_handler/truncate_logs_test.rs, openraft/src/engine/handler/following_handler/update_committed_membership_test.rs, openraft/src/engine/handler/leader_handler/append_entries_test.rs, openraft/src/engine/handler/leader_handler/send_heartbeat_test.rs, openraft/src/engine/handler/log_handler/purge_log_test.rs, openraft/src/engine/handler/replication_handler/append_membership_test.rs, openraft/src/engine/handler/replication_handler/mod.rs, openraft/src/engine/handler/replication_handler/update_matching_test.rs, openraft/src/engine/handler/server_state_handler/update_server_state_test.rs, openraft/src/engine/handler/snapshot_handler/update_snapshot_test.rs, openraft/src/engine/handler/vote_handler/accept_vote_test.rs, openraft/src/engine/handler/vote_handler/handle_message_vote_test.rs, openraft/src/engine/testing.rs, openraft/src/engine/tests/append_entries_test.rs, openraft/src/engine/tests/elect_test.rs, openraft/src/engine/tests/handle_vote_req_test.rs, openraft/src/engine/tests/handle_vote_resp_test.rs, openraft/src/engine/tests/initialize_test.rs, openraft/src/engine/tests/log_id_list_test.rs, openraft/src/engine/tests/startup_test.rs, openraft/src/raft_state/membership_state/change_handler_test.rs, openraft/src/raft_state/membership_state/membership_state_test.rs, openraft/src/testing/mod.rs, tests/tests/append_entries/t61_heartbeat_reject_vote.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/789)
=> Refactor: remove Command::AppendBlankLog, use Command::AppendEntry instead

.github/workflows/ci.yaml, openraft/src/core/raft_core.rs, openraft/src/raft.rs, openraft/src/replication/mod.rs, openraft/src/testing/mod.rs, tests/tests/elect/t10_elect_compare_last_log.rs, tests/tests/fixtures/mod.rs, tests/tests/log_compaction/t35_building_snapshot_does_not_block_append.rs, tests/tests/membership/t99_new_leader_auto_commit_uniform_config.rs, tests/tests/metrics/t30_leader_metrics.rs, tests/tests/snapshot/t20_startup_snapshot.rs, tests/tests/snapshot/t33_snapshot_delete_conflict_logs.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/791)
=> Refactor: ReplicationCore returns StorageError to RaftCore

openraft/src/core/raft_core.rs, openraft/src/core/sm/mod.rs, openraft/src/engine/engine_impl.rs, openraft/src/engine/handler/server_state_handler/mod.rs, openraft/src/leader/leader.rs, openraft/src/raft.rs
Vote operations are crucial to ensuring the correctness of the
consensus, while snapshot operations carry a relatively heavy load.
Although both of these operations are important, they occur less
frequently than raft-log operations. As a result, the log level for
these operations should be upgraded to "info".
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/792)
=> Chore: add info level log to vote and snapshot handlers

README.md, openraft/src/core/balancer.rs, openraft/src/core/mod.rs, openraft/src/core/notify.rs, openraft/src/core/raft_core.rs, openraft/src/core/sm/mod.rs, openraft/src/core/tick.rs, openraft/src/raft.rs, openraft/src/replication/mod.rs
`tx_notify` will be used for components such as state-machine worker or
replication stream to send back notification when an action is done.
`tx_api` is left for receiving only external messages, such as
append-entries request or client-write request.
A `Balancer` is added to prevent one channel from starving the others.
The benchmark shows a better performance with 64 clients:
| clients | put/s       | ns/op      | Changes         |
| --:     | --:         | --:        | :--             |
|  64     | **730,000** |    1,369   | This commit     |
|  64     | **652,000** |    1,532   | Previous commit |
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/794)
=> Improve: create a channel `notify` specifically for interal messages

README.md
- Fix: #795
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/797)
=> Doc: fix: add a discord invitation link without expiration

openraft/src/core/notify.rs, openraft/src/core/raft_core.rs, openraft/src/core/sm/command.rs, openraft/src/replication/mod.rs, openraft/src/replication/response.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/796)
=> Refactor: collect replication response in variant `Notify::Network`

openraft/src/replication/mod.rs, tests/tests/snapshot/main.rs, tests/tests/snapshot/t90_issue_808_snapshot_to_unreachable_node_should_not_block.rs
If a replication is sending a snapshot, it should
periodically verify the input channel's status. When the input channel
is closed during replication rebuilding, it should immediately exit the
loop instead of attempting retries indefinitely.
- Fix: #808
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/811)
=> Fix: replication should be able to shutdown when replicating snapshot to unreachable node

openraft/src/membership/into_nodes.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/814)
=> Refactor: mark unused methods of IntoNodes as derepcated

openraft/src/core/raft_core.rs, openraft/src/membership/membership.rs, openraft/src/membership/membership_test.rs, openraft/src/membership/stored_membership.rs, openraft/src/metrics/raft_metrics.rs, openraft/src/metrics/wait.rs, openraft/src/metrics/wait_test.rs, openraft/src/raft_state/io_state.rs, openraft/src/raft_state/mod.rs, openraft/src/storage/helper.rs, openraft/src/vote/vote.rs
The latest approved value of `Vote`, which has been saved to disk, is
referred to as `RaftMetrics.vote`. Additionally, a new `vote()` method
has been included in `Wait` to enable the application to wait for `vote`
to reach the anticipated value.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/815)
=> Feature: add `RaftMetrics.vote`, `Wait::vote()`

memstore/src/lib.rs, openraft/src/core/raft_core.rs, openraft/src/core/sm/mod.rs, openraft/src/storage_error.rs, scripts/README.md, scripts/check.kdl, tests/tests/log_compaction/main.rs, tests/tests/log_compaction/t35_building_snapshot_does_not_block_apply.rs, tests/tests/snapshot/t20_startup_snapshot.rs
Before this commit, snapshot is built in the `sm::Worker`, which blocks
other state-machine writes, such as applying log entries.
This commit parallels applying log entries and building snapshot: A
snapshot is built in another `tokio::task`.
Because building snapshot is a read operation, it does not have to
block the entire state machine. Instead, it only needs a consistent view
of the state machine or holding a lock of the state machine.
- Fix: #596
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/816)
=> Improve: build snapshot in anohter task

tests/tests/fixtures/mod.rs, tests/tests/membership/t12_concurrent_write_and_add_learner.rs, tests/tests/snapshot/t10_api_install_snapshot.rs, tests/tests/snapshot/t31_snapshot_overrides_membership.rs, tests/tests/snapshot/t50_snapshot_when_lacking_log.rs, tests/tests/snapshot/t51_after_snapshot_add_learner_and_request_a_log.rs
`assert_stable_cluster()` does too many things in one function.
Replace it with short and explicit assertions.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/817)
=> Chore: remove testing function assert_stable_cluster

openraft/src/core/raft_core.rs, openraft/src/membership/membership.rs, openraft/src/membership/membership_test.rs, openraft/src/membership/stored_membership.rs, openraft/src/raft.rs, openraft/src/storage/mod.rs, tests/tests/fixtures/logging.rs
Add span target(mod path) to log:
Previously:
```
<func>#<span_id>:<func>#<span_id>: <message>
```
In this commit:
```
<mod>@<func>#<span_id>: <mod>@<func>#<span_id>: <message>
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/824)
=> Chore: refine tracing format for tests

cluster_benchmark/tests/benchmark/bench_cluster.rs, cluster_benchmark/tests/benchmark/network.rs, openraft/src/core/raft_core.rs, openraft/src/network/mod.rs, openraft/src/network/network.rs, openraft/src/network/rpc_option.rs, openraft/src/replication/mod.rs, tests/tests/append_entries/t10_conflict_with_empty_entries.rs, tests/tests/append_entries/t10_see_higher_vote.rs, tests/tests/append_entries/t11_append_entries_with_bigger_term.rs, tests/tests/log_compaction/t10_compaction.rs, tests/tests/log_compaction/t35_building_snapshot_does_not_block_append.rs, tests/tests/log_compaction/t35_building_snapshot_does_not_block_apply.rs, tests/tests/snapshot/t31_snapshot_overrides_membership.rs, tests/tests/snapshot/t33_snapshot_delete_conflict_logs.rs
- `RaftNetwork` introduced 3 new API `append_entries`,
`install_snapshot` and `vote` which accept an additional argument
`RPCOption`, and deprecated the old API `send_append_entries`,
`send_install_snapshot` and `send_vote`.
- The old API will be **removed** in `0.9`. An application can still
implement the old API without any changes. Openraft calls only the new
API and the default implementation will delegate to the old API.
- Implementing the new APIs will disable the old APIs.
- The new APIs accepts an additional argument `RPCOption`, to enable an
application control the networking behaviors based on the parameters
in `RPCOption`.
The `hard_ttl()` and `soft_ttl()` in `RPCOption` sets the hard limit
and the moderate limit of the duration for which an RPC should run.
Once the …
=> Feature: new RaftNetwork API with argument RCPOption

openraft/src/core/raft_core.rs, openraft/src/display_ext.rs, openraft/src/engine/handler/replication_handler/mod.rs, openraft/src/progress/inflight/mod.rs, openraft/src/progress/inflight/tests.rs, openraft/src/raft.rs, openraft/src/replication/mod.rs, openraft/src/replication/response.rs, tests/tests/fixtures/mod.rs, tests/tests/replication/main.rs, tests/tests/replication/t10_append_entries_partial_success.rs
If there are too many log entries and the `RPCOption.ttl` is not
sufficient, an application can opt to only send a portion of the
entries, with `AppendEntriesResponse::PartialSuccess(Option<LogId>)`, to
inform Openraft with the last replicated log id. Thus replication can
still make progress.
For example, it tries to send log entries `[1-2..3-10]`, the application
is allowed to send just `[1-2..1-3]` and return `PartialSuccess(1-3)`,
The returned matching log id must be **greater than or equal to** the
first log id(`AppendEntriesRequest::prev_log_id`) of the entries to
send. If no RPC reply is received, `RaftNetwork::send_append_entries`
**must** return an `RPCError` to inform Openraft that the first log
id(`AppendEntriesRequest::prev_log_id`) may not match on the remote
target node.
- …
=> Feature: `RaftNetwork::send_append_entries()` can return PartialSuccess

openraft/src/engine/handler/leader_handler/send_heartbeat_test.rs, openraft/src/engine/handler/replication_handler/mod.rs, openraft/src/progress/entry/mod.rs, openraft/src/progress/entry/tests.rs, openraft/src/progress/inflight/mod.rs, openraft/src/progress/inflight/tests.rs, openraft/src/progress/mod.rs
The callers to it do not need to check request-id anymore.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/832)
=> Refactor: let Inflight::ack() check request-id

openraft/src/core/sm/mod.rs, openraft/src/replication/mod.rs, tests/tests/fixtures/mod.rs, tests/tests/replication/main.rs, tests/tests/replication/t50_append_entries_backoff_rejoin.rs
- Part of: #833
- Improvement
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/834)
=> Test: new test: unreachable node should catch up with the leader when retarted

openraft/src/error.rs, tests/tests/append_entries/t11_append_inconsistent_log.rs, tests/tests/append_entries/t30_replication_1_voter_to_isolated_learner.rs, tests/tests/client_api/t11_client_reads.rs, tests/tests/fixtures/mod.rs, tests/tests/membership/t11_add_learner.rs, tests/tests/membership/t12_concurrent_write_and_add_learner.rs, tests/tests/membership/t30_commit_joint_config.rs, tests/tests/membership/t30_elect_with_new_config.rs, tests/tests/membership/t51_remove_unreachable_follower.rs, tests/tests/snapshot/t30_purge_in_snapshot_logs.rs, tests/tests/snapshot/t34_replication_does_not_block_purge.rs, tests/tests/snapshot/t50_snapshot_line_rate_to_snapshot.rs, tests/tests/snapshot/t60_snapshot_chunk_size.rs, tests/tests/snapshot/t90_issue_808_snapshot_to_unreachable_node_should_not_block.rs
Upgrade tip:
Do not use it.
Rename `isolate_node()` to `set_node_network_failure()`, to better reflect its functionality:
The struct `TypedRaftRouter` now derives the `Clone` trait.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/838)
=> Change: remove unused error CommittedAdvanceTooMany

openraft/src/raft.rs, tests/tests/membership/t30_commit_joint_config.rs
The `Raft::add_learner()` method, when invoked with the `blocking`
parameter set to `true`, should block forever until the learner
synchronizes its logs with the leader.
In its current implementation, `add_learner()` calls the `Raft::wait()`
method, which has a default timeout of `500ms`. To achieve the desired
blocking behavior, the default timeout should be increased
significantly.
- Fix: #846
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/847)
=> Fix: add_learner() should block forever

examples/raft-kv-memstore/src/store/mod.rs, openraft/src/core/raft_core.rs, openraft/src/docs/docs.md, openraft/src/docs/protocol/leader_lease.md, openraft/src/docs/protocol/mod.rs, openraft/src/engine/engine_impl.rs, openraft/src/engine/handler/following_handler/append_entries_test.rs, openraft/src/engine/handler/following_handler/install_snapshot_test.rs, openraft/src/engine/handler/following_handler/receive_snapshot_chunk_test.rs, openraft/src/engine/handler/replication_handler/mod.rs, openraft/src/engine/handler/vote_handler/handle_message_vote_test.rs, openraft/src/engine/handler/vote_handler/mod.rs, openraft/src/engine/tests/handle_vote_req_test.rs, openraft/src/engine/time_state.rs, openraft/src/leader/leader.rs, openraft/src/leader/voting.rs, openraft/src/membership/effective_membership.rs, openraft/src/progress/mod.rs, openraft/src/raft.rs, openraft/src/replication/mod.rs, openraft/src/replication/response.rs, openraft/src/utime.rs, tests/tests/metrics/t30_leader_metrics.rs, tests/tests/replication/t50_append_entries_backoff.rs
The leader records the most recent time point when an RPC is initiated
towards a target node. The highest timestamp associated with RPCs made
to a quorum serves as the starting time point for a leader lease.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/848)
=> Feature: leader lease

openraft/src/docs/protocol/leader_lease.md, openraft/src/engine/engine_impl.rs, openraft/src/engine/handler/leader_handler/mod.rs, openraft/src/engine/handler/replication_handler/mod.rs, openraft/src/engine/handler/vote_handler/mod.rs, openraft/src/engine/tests/handle_vote_req_test.rs, openraft/src/internal_server_state.rs, openraft/src/leader/leader.rs, openraft/src/leader/mod.rs
Because it actually includes two server state: Leader and Candidate.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/850)
=> Doc: explain election timeout for committed Vote and uncommitted Vote

openraft/src/engine/engine_impl.rs, openraft/src/engine/handler/vote_handler/mod.rs, openraft/src/engine/tests/elect_test.rs, openraft/src/engine/tests/handle_vote_resp_test.rs, openraft/src/internal_server_state.rs, openraft/src/leader/leader.rs, openraft/src/leader/voting.rs
`Voting` should be a standalone state that does not depend on
`RaftState`.
Although it won't happen, the `vote` for a candidate(`Voting`) can be
different from the `vote` in `RaftState`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/853)
=> Refactor: extract voting management into a separate `Voting` struct

openraft/src/core/raft_core.rs, openraft/src/engine/engine_impl.rs, openraft/src/engine/handler/log_handler/mod.rs, openraft/src/engine/mod.rs, openraft/src/engine/tests/trigger_purge_log_test.rs, openraft/src/raft.rs, tests/tests/client_api/main.rs, tests/tests/client_api/t12_trigger_purge_log.rs
This method allows users to purge logs when required.
It initiates the log purge up to and including the given `upto` log index.
Logs that are not included in a snapshot will **NOT** be purged.
In such scenario it will delete as many log as possible.
The `max_in_snapshot_log_to_keep` config is not taken into account when
purging logs.
Openraft won't purge logs at once, e.g. it may be delayed by several
seconds, because if it is a leader and a replication task has been
replicating the logs to a follower, the logs can't be purged until the
replication task is finished.
- Fix: #852
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/855)
=> Feature: add Raft::purge_log()

guide/README.md
mdbook based guide is disabled and move the github-workflow script to a
backup.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/867)
=> Doc: add README to guide/

examples/raft-kv-memstore/test-cluster.sh, examples/raft-kv-rocksdb/test-cluster.sh, openraft/src/core/raft_core.rs, openraft/src/storage/v2.rs, openraft/src/testing/suite.rs
The `RaftStateMachine::apply()` and `RaftLogStorage::append_to_log()`
method contains a `Send` bound on the `IntoIterator` passed to it.
However, the actual iterator returned from `IntoIterator` doesn't have
it. Thus, it's impossible to iterate across awaits in the
implementation.
The correct API should be:
```
async fn apply<I>(&mut self, entries: I) -> Result<...>
where
I: IntoIterator<Item = C::Entry> + Send,
I::IntoIter: Send;
```
Thanks to [schreter](https://github.com/schreter)
- Fix: #860
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/868)
=> Improve: IntoIterator::IntoIter should be Send

openraft/src/raft.rs
Thanks to [xDarksome](https://github.com/xDarksome)
- Fix: #870
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/872)
=> Improve: impl Clone for Raft does not require Clone for its type parameters

openraft/src/change_members.rs, openraft/src/docs/cluster_control/dynamic-membership.md, openraft/src/membership/membership.rs, openraft/src/membership/membership_test.rs, tests/tests/membership/t11_add_learner.rs, tests/tests/membership/t20_change_membership.rs
During dynamic cluster changes, we sometimes need to update an existing
node, for example changing its network address.
Adding `SetNodes` variant to `ChangeMembers` allows replacing an
existing node directly.
However, this also carries risk of creating a split brain scenario if
used incorrectly.
- Fix: #875
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/876)
=> Feature: add ChangeMembers::SetNodes

.github/workflows/ci.yaml, Cargo.toml, macros/Cargo.toml, macros/src/lib.rs, openraft/Cargo.toml, openraft/src/async_runtime.rs, openraft/src/core/raft_core.rs, openraft/src/docs/feature_flags/feature-flags.md, openraft/src/entry/traits.rs, openraft/src/instant.rs, openraft/src/lib.rs, openraft/src/metrics/wait.rs, openraft/src/network/factory.rs, openraft/src/network/network.rs, openraft/src/raft.rs, openraft/src/runtime/mod.rs, openraft/src/storage/adapter.rs, openraft/src/storage/log_store_ext.rs, openraft/src/storage/mod.rs, openraft/src/storage/v2.rs, openraft/src/testing/suite.rs
- 'singlethreaded' compile-time feature gate.
The new feature gate forces the raft instance to be used by a single thread by not implementing `Send` for certain data structures and substituting calls to `tokio::spawn` with calls to `tokio::spawn_local` when using the `tokio` asynchronous runtime. In case the application wants to use a different type of asynchronous runtimes, the `spawn` method has to be appropriately implemented.
- Additional change included.
`openraft::Instant` is implemented for `std::time::Instant` to simplify the usage.
- Fix: [#862](https://github.com/datafuselabs/openraft/issues/862)
FYI: @schreter 
**Checklist**
- - - …
=> Feature: add 'singlethreaded' raft mode

memstore/src/lib.rs, openraft/src/engine/engine_impl.rs, openraft/src/engine/handler/log_handler/mod.rs, openraft/src/engine/handler/replication_handler/mod.rs, openraft/src/engine/handler/vote_handler/mod.rs, openraft/src/internal_server_state.rs, scripts/mprocs-check.yaml, tests/tests/life_cycle/main.rs, tests/tests/life_cycle/t50_single_leader_restart_re_apply_logs.rs
As a leader, the replication progress to itself should be restored upon
startup.
And if this leader is the only node in a cluster, it should re-apply all
of the logs to state machine at once.
- Fix: #883
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/884)
=> Fix: restore replication progress when a leader starts up

openraft/src/raft/message/append_entries.rs, openraft/src/raft/message/client_write.rs, openraft/src/raft/message/install_snapshot.rs, openraft/src/raft/message/mod.rs, openraft/src/raft/message/vote.rs, openraft/src/raft/mod.rs
- `raft::message::AppendEntriesRequest`
- `raft::message::AppendEntriesResponse`
- `raft::message::ClientWriteResponse`
- `raft::message::InstallSnapshotRequest`
- `raft::message::InstallSnapshotResponse`
- `raft::message::VoteRequest`
- `raft::message::VoteResponse`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/886)
=> Refactor: move raft message types to separate files

openraft/src/lib.rs, openraft/src/raft/core_state.rs, openraft/src/raft/mod.rs, openraft/src/raft/raft_inner.rs, openraft/src/raft/trigger.rs, openraft/src/type_config.rs, tests/tests/client_api/t12_trigger_purge_log.rs, tests/tests/client_api/t13_trigger_snapshot.rs, tests/tests/membership/t30_elect_with_new_config.rs, tests/tests/metrics/t10_purged.rs, tests/tests/metrics/t30_leader_metrics.rs, tests/tests/replication/t50_append_entries_backoff_rejoin.rs, tests/tests/snapshot_building/t35_building_snapshot_does_not_block_append.rs, tests/tests/snapshot_building/t35_building_snapshot_does_not_block_apply.rs, tests/tests/snapshot_streaming/t20_startup_snapshot.rs, tests/tests/snapshot_streaming/t30_purge_in_snapshot_logs.rs, tests/tests/snapshot_streaming/t34_replication_does_not_block_purge.rs, tests/tests/snapshot_streaming/t90_issue_808_snapshot_to_unreachable_node_should_not_block.rs
Moved trigger election, heartbeat, snapshot and purge log from `Raft`
to a new `Trigger` struct, to separate externally trigger actions from
the main Raft API.
---
Marked the old trigger methods in `Raft` as deprecated, and recommended
using the new `Trigger` struct instead.
The main motivation of these changes is to organize the Raft API in a
more structured way, by extracting trigger actions into a dedicated
struct, instead of mixing them together in the `Raft` API.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/888)
=> Change: move external command trigger to dedicated Trigger struct

openraft/src/raft/mod.rs, openraft/src/raft/runtime_config_handle.rs, tests/tests/append_entries/t60_enable_heartbeat.rs, tests/tests/append_entries/t61_heartbeat_reject_vote.rs, tests/tests/membership/t21_change_membership_cases.rs, tests/tests/membership/t31_remove_leader.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/889)
=> Change: move runtime config API to dedicated RuntimeConfigHandle

openraft/src/storage/log_store_ext.rs, openraft/src/testing/suite.rs
`get_log_id()` should only return present log id,
and should not be responsible to return id of an already purged log
entry, which introduce unnecessary complexity.
Upgrade tip:
An RaftStorage implementation should have already maintained the
last-purge-log-id. Avoid getting it via `RaftLogReaderExt::get_log_id()`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/892)
=> Change: RaftLogReaderExt::get_log_id() should not return last-purged-id

cluster_benchmark/tests/benchmark/store.rs, examples/raft-kv-memstore/src/store/mod.rs, examples/raft-kv-rocksdb/src/store.rs, memstore/src/lib.rs, openraft/src/compat/compat07.rs, openraft/src/docs/getting_started/getting-started.md, openraft/src/storage/adapter.rs, openraft/src/storage/mod.rs, openraft/src/storage/v2.rs, rocksstore-compat07/src/lib.rs, rocksstore/src/lib.rs, sledstore/src/lib.rs, stores/rocksstore-v2/src/lib.rs, tests/tests/fixtures/mod.rs, tests/tests/metrics/t10_purged.rs, tests/tests/snapshot_streaming/t33_snapshot_delete_conflict_logs.rs
- Move the `get_log_state()` method from the `RaftLogReader` trait to
the `RaftStorage` trait.
- For applications that enable the `storage-v2` feature,
`get_log_state()` will be moved from `RaftLogReader` to
`RaftLogStorage`.
- `get_log_state()` should only be called once when openraft starts up.
Only the `ReplicationCore` uses `RaftLogReader`, and it does not need
`get_log_state()`. The log entries to replicate are decided by
`RaftCore`.
Upgrade tip:
Implement `get_log_state()` in the `RaftStorage` or `RaftLogStorage`
trait instead of `RaftLogReader`.
Refer to the changes in `rocksstore/src/lib.rs` in this commit for an
example.
- - - …
=> Change: move get_log_state() from RaftLogReader to RaftStorage

memstore/src/lib.rs, openraft/src/core/raft_core.rs, openraft/src/engine/command.rs, openraft/src/storage/adapter.rs, openraft/src/storage/helper.rs, openraft/src/storage/mod.rs, openraft/src/storage/v2.rs, openraft/src/testing/suite.rs, tests/tests/log_store/main.rs, tests/tests/log_store/t10_save_committed.rs
- **Wrote committed log id to storage**
Save the committed log id to storage before Raft apply log entries. This can
recover state machine to the state corresponding to the committed log id upon
system startup.
- **Re-applied log entries after startup**
If the last applied log id is smaller than the committed log id saved in
storage, re-apply log entries from the next index of last applied log id to the
committed log id.
Version 1 storage API `RaftStorage` and Version 2 storage API
`RaftLogStorage` both add API `save_committed()` and `read_committed()`
to support saving/reading committed log id.
These two new API are optional and provides default dummy
implementation, an application does not need any modifications if it does
not need this feature.
- - - …
=> Feature: save committed log id

openraft/src/docs/data/log_pointers.md, openraft/src/storage/v2.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/899)
=> Doc: explain why need to persist committed-log-id

.github/workflows/ci.yaml, openraft/Cargo.toml, openraft/src/docs/faq/faq.md, openraft/src/docs/feature_flags/feature-flags.md, openraft/src/progress/entry/mod.rs, tests/Cargo.toml, tests/tests/README.md, tests/tests/replication/main.rs, tests/tests/replication/t60_feature_loosen_follower_log_revert.rs
Add a new feature flag `loosen-follower-log-revert`, to permit the
follower's log to roll back to an earlier state without causing the
leader to panic.
Although log state reversion is typically seen as a bug, enabling it can
be useful for testing or in some special scenarios.
For instance, in an even number nodes cluster, erasing a node's data
and then rebooting it(log reverts to empty) will not result in data
loss.
- Related issue: #898
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/903)
=> Feature: permit follower log to revert to earlier state with `--features loosen-follower-log-revert`

openraft/src/storage/helper.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/906)
=> Chore: logging should be before updating variables in get_initial_state()

openraft/src/replication/mod.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/907)
=> Chore: print first and last log id when unexpected logs are returned while replicating

openraft/src/docs/faq/faq.md
- Related issue: #918
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/919)
=> Doc: add FAQ: can not survive incorrectly configured cluster

README.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/921)
=> Chore: update discord channel link without expiration

openraft/src/docs/data/vote.md, openraft/src/engine/engine_impl.rs, openraft/src/engine/handler/leader_handler/append_entries_test.rs, openraft/src/engine/handler/leader_handler/send_heartbeat_test.rs, openraft/src/engine/handler/vote_handler/mod.rs, openraft/src/engine/tests/startup_test.rs, openraft/src/membership/membership.rs, openraft/src/raft/message/client_write.rs, openraft/src/raft_state/membership_state/mod.rs, openraft/src/raft_state/mod.rs, tests/tests/life_cycle/main.rs, tests/tests/life_cycle/t90_issue_920_non_voter_leader_restart.rs, tests/tests/membership/t11_add_learner.rs, tests/tests/membership/t31_remove_leader.rs
Openraft does not require Leader/Candidate to be a voter.
Before this commit, Openraft's handling of non-voter leader is
inconsistent:
For a node that has a vote proposed by this node and is committed, and is not a voter:
- [`calc_server_state()`](https://github.com/datafuselabs/openraft/blob/97254a31c673e52429ee7187de96fd2ea2a5ce98/openraft/src/raft_state/mod.rs#L323) returns `Learner`.
- But [`is_leader()`](https://github.com/datafuselabs/openraft/blob/97254a31c673e52429ee7187de96fd2ea2a5ce98/openraft/src/raft_state/mod.rs#L353) returns true.
Since this commit,
`calc_server_state()` and `is_leader()` returns consistent result according to the following table:
For node-2:
- Node-2 with vote `(term=1, node_id=2, committed=true)`:
- is a leader if it is **present** in config, either a …
=> Refactor: fix handling of non-voter leader

openraft/src/replication/mod.rs
When streaming a snapshot chunk, it should repeatly `read_buf()` until
`snapshot_max_chunk_size` is full or read EOF.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/925)
=> Fix: AsyncReadExt::read_buf() only reads at most 2MB per call

examples/raft-kv-rocksdb/tests/cluster/test_cluster.rs
I hereby agree to the terms of the CLA available at: https://databend.rs/dev/policies/cla/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/926)
=> Chore: increase timeout for example application. It tends to timeout in a CI

openraft/src/docs/faq/faq.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/928)
=> Doc: refine FAQ, add "What actions are required when a node restarts"

openraft/src/core/tick.rs
Currently, `tick_loop()` would keep printing the trace message every tick even when the receiver (Raft main loop) is gone in this form:
`INFO openraft::core::tick: .../tick.rs:70: Tick fails to send, receiving end quit: channel closed`
If the tick message fails to send, then terminate the loop, since every future message will fail to send as well.
Also adjust the trace message to better describe what happened.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/930)
=> Fix: End `tick_loop()` when the receiver is gone.

openraft/src/replication/mod.rs, tests/tests/replication/t60_feature_loosen_follower_log_revert.rs
Problem:
When "loosen-follower-log-revert" enabled, and a follower log gets
reverted, e.g., all raft-logs are removed from that follower, the leader
encounters a panic due to a `debug_assert()`.
Solution:
- Disable the assertion when this feature is enabled.
- The test `feature_loosen_follower_log_revert` is also revised to reveal this
bug.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/937)
=> Fix: avoid panic with "loosen-follower-log-revert" enabled

openraft/src/async_runtime.rs, openraft/src/core/raft_msg/mod.rs, openraft/src/defensive.rs, openraft/src/docs/feature_flags/feature-flags.md, openraft/src/entry/traits.rs, openraft/src/instant.rs, openraft/src/lib.rs, openraft/src/network/backoff.rs, openraft/src/network/factory.rs, openraft/src/network/network.rs, openraft/src/node.rs, openraft/src/raft/mod.rs, openraft/src/storage/adapter.rs, openraft/src/storage/log_store_ext.rs, openraft/src/storage/mod.rs, openraft/src/storage/v2.rs, openraft/src/timer/timeout.rs, openraft/src/timer/timeout_test.rs, openraft/src/type_config.rs
Some preliminary implementation with `OptionalSend`/`OptionalSync` was done previously, it was not complete, though.
Currently, `Send`/`Sync` bounds are required for `AppData`, `RaftEntry`, async runtime wrappers and other types, but they are only relevant for multi-threaded access. If `openraft` is configured to use single-threaded runtime, then they don't have to be `Send`/`Sync`.
Consequently replace `Send`/`Sync` bounds with `OptionalSend`/`OptionalSync` bounds to clean it up.
This change also fixes `timeout.rs`, which seems to be unused so far, but didn't properly use `AsyncRuntime` abstraction.
Two points for the future:
- We should add at least a compile test where `singlethreaded` feature is set to test it.
- Later, even `Arc` could be replaced with a single-threaded counterpart …
=> Fix: For single-threaded execution, there is no need for `Send`/`Sync` bounds

openraft/src/core/raft_core.rs, openraft/src/replication/mod.rs
Make `replication::Data` a enum, and enable using its variants `Logs(l)`
and `Snapshot(s)` directly.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/944)
=> Chore: internal refactor replication::Data

tests/Cargo.toml, tests/tests/fixtures/mod.rs, tests/tests/replication/t50_append_entries_backoff.rs
Simplify the API to set pre-hook callback.
The first argument is changed from `RPCTypes` to real RPC data, enabling
the hook callback to interact directly with the RPC request.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/949)
=> Refactor: pre-hook callback within tests/fixtures

openraft/src/replication/mod.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/950)
=> Refactor: replication/mod.rs

openraft/src/testing/suite.rs
In case append_to_log, two entries with index = 10 were appended to log, purging will fail if we choose stream-like log store instead of map-like, and it will never happen in the real world.
**Checklist**
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/952)
=> Chore: make case append_to_log more rigorous

openraft/src/error.rs, openraft/src/log_id_range.rs, openraft/src/network/rpc_type.rs, openraft/src/replication/hint.rs, openraft/src/replication/mod.rs, openraft/src/replication/request.rs, tests/tests/fixtures/mod.rs, tests/tests/replication/main.rs, tests/tests/replication/t51_append_entries_too_large.rs
If a `RaftNetwork` implmentation found an `AppendEntriesRequest` is too
large, it could return a `PayloadTooLarge::new_entries_hint(n)` error to
tell openraft devide request into smaller chunks containing at most `n`
entries. Openraft will limit the number of entries in the next 10
`AppendEntrie` RPC.
Exmaple:
```rust
impl<C: RaftTypeConfig> RaftNetwork<C> for MyNetwork {
fn append_entries(&self,
rpc: AppendEntriesRequest<C>,
option: RPCOption
) -> Result<_, RPCError<C::NodeId, C::Node, RaftError<C::NodeId>>> {
if rpc.entries.len() > 10 {
return Err(PayloadTooLarge::new_entries_hint(10).into());
}
// ...
}
}
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/951)
=> Feature: add `PayloadTooLarge` error

openraft/src/raft/mod.rs, tests/tests/client_api/main.rs, tests/tests/client_api/t16_with_raft_state.rs, tests/tests/fixtures/mod.rs, tests/tests/life_cycle/t10_initialization.rs
This new method serves as a convenience wrapper around
`Raft::external_request()`, streamlining use cases where only a single
value needs to be returned.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/957)
=> Feature: add `Raft::access_raft_state()` to access `RaftState` with a function

openraft/src/metrics/wait.rs, openraft/src/metrics/wait_test.rs, tests/tests/append_entries/t11_append_updates_membership.rs, tests/tests/snapshot_streaming/t90_issue_808_snapshot_to_unreachable_node_should_not_block.rs
Membership in Openraft now contains voters and learners, a simple
`members` is not clear about what to assert.
In this PR we add a new method `Wait::voter_ids()` to wait for
membership to become containing the expected voter ids and deprecated
`Wait::members()`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/961)
=> Feature: add `Wait::voter_ids()` and deprecate `Wait::members()`

examples/raft-kv-memstore/src/network/api.rs, examples/raft-kv-rocksdb/src/network/api.rs, memstore/src/lib.rs, openraft/src/core/raft_core.rs, openraft/src/core/raft_msg/mod.rs, openraft/src/docs/protocol/mod.rs, openraft/src/docs/protocol/read.md, openraft/src/engine/log_id_list.rs, openraft/src/engine/tests/log_id_list_test.rs, openraft/src/raft/mod.rs, openraft/src/raft_state/mod.rs, openraft/src/raft_state/tests/read_log_id_test.rs, openraft/src/type_config.rs, tests/tests/client_api/t11_client_reads.rs, tests/tests/fixtures/mod.rs, tests/tests/membership/t10_single_node.rs
The `Raft::is_leader()` method does not fully ensure linearizable read
operations and is deprecated in this version. Instead, applications
should use the `Raft::ensure_linearizable()` method to guarantee
linearizability.
Under the hood, `Raft::ensure_linearizable()` obtains a `ReadIndex` from
`RaftCore` if it remains the leader, and blocks until the state
machine applies up to the `ReadIndex`. This process ensures that the
application observes all state visible to a preceding read operation.
- Fix: #965
Upgrade tip:
Replace `Raft::is_leader()` with `Raft::ensure_linearizable()`.
This PR implements the very basic requirement proposed in:
- #262
- - - …
=> Feature: add `Raft::ensure_linearizable()` to ensure linearizable read

openraft/src/metrics/metric.rs, openraft/src/metrics/metric_display.rs, openraft/src/metrics/mod.rs, openraft/src/metrics/wait.rs, openraft/src/metrics/wait_condition.rs
`Wait` does not need many method for each metric. In this commit, it
provides method `eq()` and `ge()` to specify waiting condition in a
general way. The metric to await is specified by `Metric` as the first
argument.
```rust
my_raft.wait(None).ge(Metric::Term(2), "").await?
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/967)
=> Feature: add `Wait::eq()` and `ge()` to await a metics

openraft/src/docs/faq/faq.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/969)
=> Doc: faq: add differences from std raft

openraft/src/core/sm/mod.rs, openraft/src/testing/suite.rs
When implementing the `RaftStateMachine::apply` method, if the user
fails to return a number of replies that corresponds to the number of
input entries, OpenRaft will panic, often without providing helpful
diagnostic information.
To address this issue, this commit introduces an assertion immediately
after the `apply()` method returns its replies. This assertion checks
that the quantity of replies is equal to the number of input entries,
ensuring consistency.
Additionally, new test cases focusing on the `apply()` method have been
added into the test suites provided by OpenRaft, enhancing the
robustness of the implementation.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/op …
=> Refactor: add defensive check to state machine replies

memstore/src/lib.rs, openraft/src/core/raft_core.rs, openraft/src/raft/mod.rs, tests/tests/append_entries/t10_see_higher_vote.rs, tests/tests/client_api/main.rs, tests/tests/client_api/t51_write_when_leader_quit.rs
Before this commit, the channels used for sending responses to the
client were dropped whenever a leader stepped down, which was not
necessary.
In the current commit, when a leader quits, we now preserve the channel, ensuring that:
- An OK response is sent to the client if the log entry the client has
written is successfully committed;
- Alternatively, a `ForwardToLeader` error is sent if the log is
reverted due to a conflict with the new leader.
In short, OpenRaft now makes a concerted effort to deliver a success
message to the client wherever possible.
Two test cases have been added to cover both successful and erroneous
scenarios.
Special thanks to @tvsfx for proposing this refinement :D
- Fix: #963
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" …
=> Refactor: respond to client even when leader is switched

examples/raft-kv-rocksdb/Cargo.toml, examples/raft-kv-rocksdb/src/app.rs, examples/raft-kv-rocksdb/src/client.rs, examples/raft-kv-rocksdb/src/lib.rs, examples/raft-kv-rocksdb/src/network/api.rs, examples/raft-kv-rocksdb/src/store.rs
- Fix: #976
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/979)
=> Refactor: update example/raft-kv-rocksstore to use `storage-v2` API

macros/Cargo.toml, macros/src/lib.rs, openraft/src/docs/feature_flags/feature-flags.md
Issue #959.
This PR substitutes the existing async_trait macro usage with the async_fn_in_trait language feature which is generally available in Rust 1.75.0 if the singlethreaded feature is turned on.
With this change, in order to use the singlethreaded feature, the minimum supported Rust version is bumped to 1.75.0.
**Checklist**
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/982)
=> Change: #959 ditch async_trait for the singlethreade feature

.github/workflows/ci.yaml, Cargo.toml, examples/raft-kv-memstore-singlethreaded/.gitignore, examples/raft-kv-memstore-singlethreaded/Cargo.toml, examples/raft-kv-memstore-singlethreaded/README.md, examples/raft-kv-memstore-singlethreaded/src/api.rs, examples/raft-kv-memstore-singlethreaded/src/app.rs, examples/raft-kv-memstore-singlethreaded/src/lib.rs, examples/raft-kv-memstore-singlethreaded/src/network.rs, examples/raft-kv-memstore-singlethreaded/src/router.rs, examples/raft-kv-memstore-singlethreaded/src/store.rs, examples/raft-kv-memstore-singlethreaded/test-cluster.sh, examples/raft-kv-memstore-singlethreaded/tests/cluster/main.rs, examples/raft-kv-memstore-singlethreaded/tests/cluster/test_cluster.rs
This example `examples/raft-kv-memstore-singlethreaded` illustrates
building a single threaded Openraft application.
By enabling feature flag `singlethreaded`, Openraft does not require the
data types to be `Send`, which enables using `Rc` in place of `Arc` to
gain a performance improvement.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/989)
=> Test: add example of singlethreaded kv-store

openraft/src/error.rs
While implementing a struct that has a generic `RaftError<E>` as a field, I ran into some issues with trait bounds because `RaftError` does not make a distinction between the serde `Serialize` and `Deserialize` bounds. The consequence is that any `impl` block that requires my struct to be `Serialize` will require `E` to *both* be `Serialize` and `DeserializeOwned`, which is not necessary. This PR splits the two bounds. 
**Checklist**
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/991)
=> Fix: Split serde bound for `RaftError` into serialize and deserialize

openraft/src/async_runtime.rs, openraft/src/config/config.rs, openraft/src/engine/engine_config.rs, openraft/src/raft/mod.rs
Up to now, the `rand` crate was used directly to generate random numbers for `openraft`. However, this has some drawback when integrating with other async runtimes.
Expose the random number generator via `AsyncRuntime` abstraction and implement it by default via `rand::thread_rng()`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/995)
=> Feature: Add random number generator to `AsyncRuntime`

openraft/src/error.rs, openraft/src/testing/suite.rs
Thanks to @tvsfx for giving suggestions on serde trait bound optimization:
https://github.com/datafuselabs/openraft/pull/993#issuecomment-1906027920
A storage implementation may choose to `purge()` logs in background.
The test should wait a short while for the purge to complete.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/999)
=> Refactor: Simplify and refine serde trait bound

openraft/src/core/raft_core.rs, openraft/src/core/raft_msg/external_command.rs, openraft/src/core/raft_msg/mod.rs, openraft/src/core/sm/command.rs, openraft/src/core/sm/mod.rs, openraft/src/raft/mod.rs, openraft/src/raft/raft_inner.rs, openraft/src/replication/mod.rs, openraft/src/replication/request.rs, tests/tests/client_api/main.rs, tests/tests/client_api/t13_get_snapshot.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/1000)
=> Feature: add Raft::get_snapshot() to get the last snapshot from state machine

openraft/src/instant.rs
The crate providing async runtime is responsible to provide an `Instant` implementation, not `openraft`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/1001)
=> Fix: Remove implementation of `Instant` for `std::time::Instant`

examples/raft-kv-rocksdb/tests/cluster/test_cluster.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/1003)
=> Chore: use different port for examples

openraft/src/core/raft_core.rs, openraft/src/core/raft_msg/mod.rs, openraft/src/core/sm/command.rs, openraft/src/core/sm/mod.rs, openraft/src/engine/command.rs, openraft/src/engine/engine_impl.rs, openraft/src/engine/handler/following_handler/mod.rs, openraft/src/raft/mod.rs, openraft/src/storage/mod.rs, tests/tests/client_api/main.rs, tests/tests/client_api/t13_install_complete_snapshot.rs
Using this method, the application provides a full snapshot to
Openraft, which is then used to install and replace the state machine.
It is entirely the responsibility of the application to acquire a
snapshot through any means: be it in chunks, as a stream, or via shared
storage solutions like S3.
This method necessitates that the caller supplies a valid `Vote` to
confirm the legitimacy of the leader, mirroring the requirements of
other Raft protocol APIs such as `append_entries` and `vote`.
- Part of #606
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/1002)
=> Feature: add `Raft::install_complete_snapshot()` to install a snapshot

openraft/src/async_runtime.rs, openraft/src/core/tick.rs, openraft/src/raft/mod.rs
Not all of the async-runtime provide an `abort()` primitive, such as
[`monoio`](https://crates.io/crates/monoio).
In this commit `abort()` is removed in order to allow Openraft to be
compatible with `monoio`.
`Tick` is the only mod that relies on `abort()` for shutdown.
In this commit shutting down is replaced with using `tokio::sync::oneshot::channel`.
Refer to:
- https://github.com/datafuselabs/openraft/pull/1010#pullrequestreview-1885639263
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/1012)
=> Change: remove `AsyncRuntime::abort()`

openraft/src/core/tick.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/1015)
=> Fixup: do not call Tick::shutdown if it is already shutdown

.github/workflows/ci.yaml, openraft/src/config/config.rs, openraft/src/config/config_test.rs, openraft/src/core/raft_core.rs, openraft/src/core/raft_msg/mod.rs, openraft/src/engine/command.rs, openraft/src/engine/engine_impl.rs, openraft/src/engine/handler/replication_handler/mod.rs, openraft/src/error.rs, openraft/src/error/replication_closed.rs, openraft/src/error/streaming_error.rs, openraft/src/membership/into_nodes.rs, openraft/src/membership/membership.rs, openraft/src/metrics/wait.rs, openraft/src/network/network.rs, openraft/src/network/rpc_option.rs, openraft/src/network/stream_snapshot.rs, openraft/src/progress/mod.rs, openraft/src/raft/message/install_snapshot.rs, openraft/src/raft/message/mod.rs, openraft/src/raft/mod.rs, openraft/src/replication/callbacks.rs, openraft/src/replication/mod.rs, openraft/src/replication/request.rs, tests/tests/snapshot_streaming/t33_snapshot_delete_conflict_logs.rs
Add `RaftNetwork::snapshot()` to send a complete snapshot and move
sending snapshot by chunks out of ReplicationCore.
To enable a fully customizable implementation of snapshot transmission
tailored to the application's needs, this commit relocates the
chunk-by-chunk transmission logic from `ReplicationCore` to a new
sub mod, `crate::network::stream_snapshot`.
The `stream_snapshot` mod provides a default chunk-based snapshot
transmission mechanism, which can be overridden by creating a custom
implementation of the `RaftNetwork::snapshot()` method. As part of this
commit, `RaftNetwork::snapshot()` simply delegates to `stream_snapshot`.
Developers may use `stream_snapshot` as a reference when implementing
their own snapshot transmission strategy.
Snapshot transmission is internally divided …
=> Feature: `RaftNetwork::snapshot()` to send a complete snapshot

cluster_benchmark/tests/benchmark/store.rs, examples/raft-kv-memstore/src/store/mod.rs, examples/raft-kv-rocksdb/src/store.rs, memstore/src/lib.rs, openraft/src/storage/adapter.rs, openraft/src/storage/mod.rs, rocksstore-compat07/src/lib.rs, rocksstore/src/lib.rs, sledstore/src/lib.rs, stores/rocksstore-v2/src/lib.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/1021)
=> Refactor: try_get_log_entries() does not need Sync

.github/workflows/ci.yaml, Cargo.toml, examples/memstore/Cargo.toml, examples/memstore/README.md, examples/memstore/src/lib.rs, examples/memstore/src/log_store.rs, examples/memstore/test-cluster.sh, examples/raft-kv-memstore-generic-snapshot-data/Cargo.toml, examples/raft-kv-memstore-generic-snapshot-data/src/lib.rs, examples/raft-kv-memstore-generic-snapshot-data/src/store.rs, examples/raft-kv-memstore/Cargo.toml, examples/raft-kv-memstore/src/app.rs, examples/raft-kv-memstore/src/lib.rs, examples/raft-kv-memstore/src/store/mod.rs, openraft/src/lib.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/1022)
=> Refactor: add examples/memstore to implement LogStore for other example applications

examples/raft-kv-memstore-generic-snapshot-data/src/network.rs, examples/raft-kv-memstore-opendal-snapshot-data/src/network.rs, examples/raft-kv-memstore-singlethreaded/src/network.rs, examples/raft-kv-memstore/src/network/raft_network_impl.rs, examples/raft-kv-rocksdb/src/network/raft_network_impl.rs, openraft/src/error.rs, openraft/src/network/network.rs, openraft/src/raft/message/append_entries.rs, tests/tests/fixtures/mod.rs, tests/tests/replication/t10_append_entries_partial_success.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/1028)
=> Change: remove deprecated RaftNetwork methods without `option` argument

examples/raft-kv-memstore-generic-snapshot-data/README.md, examples/raft-kv-memstore-generic-snapshot-data/src/api.rs, examples/raft-kv-memstore-generic-snapshot-data/src/network.rs, examples/raft-kv-memstore-generic-snapshot-data/tests/cluster/test_cluster.rs, examples/raft-kv-memstore-opendal-snapshot-data/README.md, examples/raft-kv-memstore-opendal-snapshot-data/src/api.rs, examples/raft-kv-memstore-opendal-snapshot-data/src/network.rs, examples/raft-kv-memstore-opendal-snapshot-data/tests/cluster/test_cluster.rs, openraft/src/core/raft_core.rs, openraft/src/core/raft_msg/mod.rs, openraft/src/core/sm/command.rs, openraft/src/core/sm/mod.rs, openraft/src/docs/feature_flags/feature-flags.md, openraft/src/docs/getting_started/getting-started.md, openraft/src/engine/command.rs, openraft/src/engine/engine_impl.rs, openraft/src/engine/handler/following_handler/install_snapshot_test.rs, openraft/src/engine/handler/following_handler/mod.rs, openraft/src/network/network.rs, openraft/src/network/stream_snapshot.rs, openraft/src/raft/message/install_snapshot.rs, openraft/src/raft/mod.rs, openraft/src/replication/mod.rs, tests/tests/client_api/main.rs, tests/tests/client_api/t13_install_full_snapshot.rs
Rename `Raft::install_complete_snapshot()` to `install_full_snapshot()`;
Rename `RaftNetwork::snapshot()` to `full_snapshot()`;
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/1030)
=> Change: rename `Raft::install_complete_snapshot()` to `install_full_snapshot()`

cluster_benchmark/tests/benchmark/store.rs, examples/memstore/src/log_store.rs, examples/raft-kv-memstore-singlethreaded/src/store.rs, examples/raft-kv-rocksdb/src/store.rs, openraft/src/async_runtime.rs, openraft/src/core/raft_core.rs, openraft/src/core/raft_msg/external_command.rs, openraft/src/core/raft_msg/mod.rs, openraft/src/core/sm/command.rs, openraft/src/core/sm/mod.rs, openraft/src/engine/command.rs, openraft/src/engine/engine_impl.rs, openraft/src/engine/handler/vote_handler/accept_vote_test.rs, openraft/src/engine/handler/vote_handler/mod.rs, openraft/src/raft/external_request.rs, openraft/src/raft/mod.rs, openraft/src/raft/raft_inner.rs, openraft/src/replication/mod.rs, openraft/src/replication/request.rs, openraft/src/storage/adapter.rs, openraft/src/storage/callback.rs, openraft/src/storage/v2.rs, openraft/src/testing/mod.rs, openraft/src/testing/suite.rs, openraft/src/timer/timeout_test.rs, openraft/src/type_config.rs, stores/rocksstore-v2/src/lib.rs
A draft for  https://github.com/datafuselabs/openraft/issues/1023 there is a clear colouring of the `AsyncRuntime` when abstracting it this way, WDYT?
**Checklist**
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/1026)
=> AsyncRuntime::oneshot

openraft/src/storage/mod.rs, openraft/src/storage/v2.rs, openraft/src/storage/v2/raft_log_storage_ext.rs, openraft/src/testing/mod.rs, tests/tests/append_entries/t11_append_inconsistent_log.rs, tests/tests/elect/t10_elect_compare_last_log.rs, tests/tests/membership/t99_new_leader_auto_commit_uniform_config.rs, tests/tests/snapshot_building/t10_build_snapshot.rs, tests/tests/snapshot_streaming/t33_snapshot_delete_conflict_logs.rs
The `RaftLogReaderExt::blocking_append()` method enables the caller to
append logs to storage in a blocking manner, eliminating the need to
create and await a callback. This method simplifies the process of
writing tests.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/1034)
=> Feature: add trait `RaftLogStorageExt` to provide additional raft-log methods

openraft/src/network/mod.rs, openraft/src/network/network.rs, openraft/src/network/snapshot_transport.rs, openraft/src/raft/mod.rs, openraft/src/raft/raft_inner.rs
If `generic-snapshot-data` is enabled, the old chunk based transport
such as `RaftNetwork::install_snapshot()` for sending and
`Raft::install_snapshot()` for receiving should be still be available
but just deprecated.
This way the application can upgrade Openraft without modification,
except several `#[allow(deprecated)]` attributes.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/1036)
=> Refactor: even when `generic-snapshot-data` is enabled, the old chunked transport be still available

openraft/src/core/raft_msg/mod.rs, openraft/src/core/sm/command.rs, openraft/src/engine/engine_impl.rs, openraft/src/raft/mod.rs
The returning error should be `RaftError<_, Infallible>`
instead of `RaftError<_, HigherVote>`: it does not return `HigherVote`
error anymore.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/1038)
=> Change: `Raft::begin_receiving_snapshot()` return only `Fatal` error.

macros/Cargo.toml, macros/src/lib.rs, macros/src/lib_readme.md, memstore/README.md, openraft/Cargo.toml, openraft/src/lib.rs, openraft/src/network/factory.rs, openraft/src/network/network.rs, openraft/src/network/snapshot_transport.rs, openraft/src/runtime/mod.rs, openraft/src/storage/log_store_ext.rs, openraft/src/storage/mod.rs, openraft/src/storage/v2.rs, openraft/src/storage/v2/raft_log_storage_ext.rs, openraft/src/testing/store_builder.rs
`macros` is renamed to `openraft-macros` and will be published to
crates.io so that Openraft-0.9 that relies on it can be published.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/1045)
=> Refactor: make `macros` a public crate for publishing

Cargo.toml, README.md, openraft/Cargo.toml, openraft/src/raft/mod.rs, openraft/src/type_config.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/1047)
=> Doc: do not enable `singlethreaded` for docs.rs; fix typos

cluster_benchmark/tests/benchmark/store.rs, examples/raft-kv-memstore/src/lib.rs, openraft/src/docs/upgrade_guide/upgrade-v08-v09.md, openraft/src/raft/mod.rs, rocksstore/src/lib.rs, sledstore/src/lib.rs, stores/rocksstore-v2/src/lib.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/1048)
=> Chore: move entries in declare_raft_types into multiple lines

openraft/src/raft/mod.rs, tests/tests/management/main.rs, tests/tests/management/t10_raft_config.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/1057)
=> Feature: `Raft::config()` returns a ref to Config this raft node uses

examples/raft-kv-memstore-generic-snapshot-data/src/api.rs, examples/raft-kv-memstore-generic-snapshot-data/src/lib.rs, examples/raft-kv-memstore-opendal-snapshot-data/src/api.rs, examples/raft-kv-memstore-opendal-snapshot-data/src/lib.rs, examples/raft-kv-memstore-singlethreaded/src/api.rs, examples/raft-kv-memstore-singlethreaded/src/lib.rs, examples/raft-kv-memstore/src/client.rs, examples/raft-kv-memstore/src/network/management.rs, examples/raft-kv-rocksdb/src/client.rs, examples/raft-kv-rocksdb/src/network/management.rs, openraft/src/core/raft_core.rs, openraft/src/engine/mod.rs, openraft/src/metrics/metric.rs, openraft/src/metrics/metric_display.rs, openraft/src/metrics/raft_metrics.rs, openraft/src/metrics/wait.rs, openraft/src/metrics/wait_condition.rs, openraft/src/metrics/wait_test.rs, openraft/src/raft/mod.rs, openraft/src/raft/raft_inner.rs, tests/tests/fixtures/mod.rs
The `RaftMetrics` type, along with related metric types, previously used
separate type parameters (`NID`, `N`) which have now been replaced with
a single generic parameter `C` bound by `RaftTypeConfig`. This
modification simplifies the type signatures and usage.
Upgrade tip:
To adapt to this change, update the metric-related type parameters from
separate `NID` and `N` to the single generic `C` constrained by
`RaftTypeConfig`:
```rust
RaftMetrics<NID, N>         --> RaftMetrics<C>
RaftDataMetrics<NID>        --> RaftDataMetrics<C>
RaftServerMetrics<NID, NID> --> RaftServerMetrics<C>
Metric<NID>                 --> Metric<C>
Wait<NID, N, A>             --> Wait<C>
```
- - - …
=> Change: Consolidate `RaftMetrics` type parameters into `C`

examples/raft-kv-memstore/src/network/raft_network_impl.rs
**Checklist**
- [*] Updated guide with pertinent info (may not always apply). 
- [*] Squash down commits to one or two logical commits which clearly describe the work you've done.
- [*] Unittest is a friend:)
Updated network implementation in example to return unreachable error for connection related issues to prevent excessive / immediate retrying.
In reference to #1051
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/1059)
=> Updated raft network implementation in example to return unreachable error

openraft/src/engine/handler/replication_handler/mod.rs, openraft/src/engine/handler/vote_handler/mod.rs, openraft/src/leader/leader.rs, openraft/src/utime.rs
Previously, `Leading.vote.utime()` held the last timestamp acknowledged
by a quorum, marking the beginning of the leader lease. The `Leading`
struct updates and calculates this timestamp upon receiving an
`AppendEntries` reply (includes heartbeat) from a follower.
However, the leader's own timestamp was not being updated in this
process.
With this commit, we now update the leader's timestamp every time the
**last-quorum-acked-time** is accessed. This constant recalculation
makes storing the timestamp in `Leading.vote` unnecessary, hence it has
been removed to streamline the code.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/1060)
=> Refactor: Remove redundant storage of last-quorum-acked-time in Leading.vote

openraft/src/core/raft_core.rs, openraft/src/engine/handler/replication_handler/mod.rs, openraft/src/progress/inflight/mod.rs, openraft/src/replication/mod.rs, openraft/src/replication/request.rs, openraft/src/replication/request_id.rs, openraft/src/replication/response.rs
Previously, the heartbeat results were not sent back to
`RaftCore`, which requires these results to calculate the **last
timestamp acknowledged by a quorum**.
This commit resolves the issue by ensuring that the heartbeat RPC
results are sent back to `RaftCore`, allowing it to correctly update the
**last timestamp acknowledged by a quorum**.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/1061)
=> Fix: Ensure heartbeat results are returned to `RaftCore`

openraft/src/core/raft_core.rs, openraft/src/engine/handler/vote_handler/mod.rs, openraft/src/instant.rs, openraft/src/leader/leader.rs, openraft/src/metrics/raft_metrics.rs, openraft/src/metrics/wait_test.rs, tests/tests/metrics/main.rs, tests/tests/metrics/t10_leader_last_ack.rs
`RaftMetrics::millis_since_quorum_ack` is the interval in milliseconds
since the last timestamp a quorum acknowledged.
This duration is used by the application to assess the likelihood that
the leader has lost synchronization with the cluster.
A longer duration without acknowledgment may suggest a higher
probability of the leader being partitioned from the cluster.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/1062)
=> Feature: add `RaftMetrics::millis_since_quorum_ack`

openraft/Cargo.toml, openraft/src/docs/feature_flags/feature-flags-toc.md, openraft/src/docs/feature_flags/feature-flags.md, openraft/src/lib.rs, openraft/src/type_config.rs
For example:
```rust,ignore
use openraft::alias::SnapshotDataOf;
struct MyTypeConfig;
impl RaftTypeconfig For MyTypeConfig { /*...*/ }
// The following two lines are equivalent:
let snapshot_data: SnapshotDataOf<MyTypeConfig>;
let snapshot_data: <MyTypeConfig as RaftTypeConfig>::SnapshotData;
```
Note that the type shortcuts are not stable and may be changed in the future.
It is also a good idea to copy the type shortcuts to your own codebase if you
want to use them.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/1063)
=> Feature: Enable feature-flag `type-alias` to use type shortcuts

examples/raft-kv-memstore/src/network/raft_network_impl.rs, examples/raft-kv-rocksdb/src/client.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/1065)
=> Improve: Use `Unreachable` error in `examples/raft-kv-rocksdb`

openraft/src/engine/engine_impl.rs, openraft/src/engine/handler/following_handler/mod.rs, openraft/src/engine/handler/leader_handler/mod.rs, openraft/src/engine/handler/log_handler/mod.rs, openraft/src/engine/handler/replication_handler/mod.rs, openraft/src/engine/handler/server_state_handler/mod.rs, openraft/src/engine/handler/snapshot_handler/mod.rs, openraft/src/engine/handler/vote_handler/mod.rs, openraft/src/engine/testing.rs, openraft/src/raft/external_request.rs, openraft/src/raft/mod.rs, openraft/src/raft_state/mod.rs, openraft/src/raft_state/tests/forward_to_leader_test.rs, openraft/src/raft_state/tests/log_state_reader_test.rs, openraft/src/raft_state/tests/read_log_id_test.rs, openraft/src/raft_state/tests/validate_test.rs, openraft/src/storage/helper.rs, openraft/src/testing/suite.rs, tests/tests/fixtures/mod.rs
The `RaftState` type, along with related metric types, previously used
separate type parameters (`NID`, `N`, `I`) which have now been replaced
with a single generic parameter `C` bound by `RaftTypeConfig`. This
modification simplifies the type signatures and usage.
Upgrade tip:
To adapt to this change, update the usage of `RaftState` type parameters
from separate `NID`, `N`, `I` to the single generic `C` constrained by
`RaftTypeConfig`:
```rust
RaftState<NID, N, I> --> RaftState<C>
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/1070)
=> Change: Consolidate `RaftState` type parameters into `C`

openraft/src/entry/mod.rs, openraft/src/entry/payload.rs, openraft/src/entry/traits.rs, openraft/src/raft_state/mod.rs, openraft/src/type_config.rs
Upgrade tip:
To adapt to this change, update type parameters from separate `NID`,
`N` to the single generic `C` constrained by `RaftTypeConfig`:
```rust
RaftEntry<NID, N>   --> RaftEntry<C>
RaftPayload<NID, N> --> RaftPayload<C>
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/1072)
=> Change: Consolidate `RaftEntry` and `RaftPayload` type parameters into `C`

openraft/src/docs/feature_flags/feature-flags.md
What does this PR do
1. Corrects a wrong statement in `openraft/src/docs/feature_flags/feature-flags.md` that enabling feature `singlethreaded` will eliminate the `Send` bound rather than requiring it.
**Checklist**
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/1078)
=> Doc: correct a statement feature singlethreaded eliminates Send bound

openraft/src/core/raft_core.rs, openraft/src/engine/handler/replication_handler/mod.rs, openraft/src/membership/membership_test.rs, openraft/src/replication/mod.rs, openraft/src/replication/response.rs, openraft/src/utime.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/1082)
=> Refactor: merge send-progress methods

cluster_benchmark/tests/benchmark/store.rs, examples/memstore/src/log_store.rs, examples/raft-kv-memstore-singlethreaded/src/store.rs, examples/raft-kv-rocksdb/src/store.rs, openraft/src/docs/getting_started/getting-started.md, openraft/src/storage/mod.rs, openraft/src/storage/v2.rs, stores/memstore/src/lib.rs, stores/rocksstore/src/lib.rs, stores/sledstore/src/lib.rs, tests/tests/fixtures/mod.rs, tests/tests/life_cycle/t50_single_follower_restart.rs, tests/tests/snapshot_streaming/t33_snapshot_delete_conflict_logs.rs
closed: #1077 
**Checklist**
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/1080)
=> Change: move read_vote function from RaftLogStorage to RaftLogReader

cluster_benchmark/tests/benchmark/store.rs, examples/raft-kv-memstore-generic-snapshot-data/src/lib.rs, examples/raft-kv-memstore-generic-snapshot-data/src/network.rs, examples/raft-kv-memstore-opendal-snapshot-data/src/lib.rs, examples/raft-kv-memstore-opendal-snapshot-data/src/network.rs, examples/raft-kv-memstore-singlethreaded/src/lib.rs, examples/raft-kv-memstore-singlethreaded/src/network.rs, examples/raft-kv-memstore/src/lib.rs, examples/raft-kv-rocksdb/src/lib.rs, openraft/src/engine/command.rs, openraft/src/raft/declare_raft_types_test.rs, openraft/src/raft/mod.rs, stores/memstore/src/lib.rs, stores/rocksstore/src/lib.rs, stores/sledstore/src/lib.rs
Types used in `declare_raft_types` can be omitted, in which case the default type will be used.
The default values for each type are:
- `D`:            `String`
- `R`:            `String`
- `NodeId`:       `u64`
- `Node`:         `::openraft::BasicNode`
- `Entry`:        `::openraft::Entry<Self>`
- `SnapshotData`: `Cursor<Vec<u8>>`
- `AsyncRuntime`: `::openraft::TokioRuntime`
Note that **The types must be specified in the exact order**:
`D`, `R`, `NodeId`, `Node`, `Entry`, `SnapshotData`, `AsyncRuntime`.
For example, to declare with only `D`, `R` and `Entry` types:
```rust,ignore
openraft::declare_raft_types!(
pub TypeConfig:
D = ClientRequest,
R = ClientResponse,
Entry = MyEntry,
);
```
Type `NodeId`, `Node`, `SnapshotData` and `AsyncRuntime` will be filled
with default values mentioned …
=> Change: Add default value to `declare_raft_types`

openraft/src/async_runtime.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/1090)
=> Refactor: trait `AsyncOneshotSendExt` does not need `Unpin`

openraft/src/core/raft_core.rs, openraft/src/core/raft_msg/mod.rs, openraft/src/core/tick.rs, openraft/src/engine/engine_impl.rs, openraft/src/engine/testing.rs, openraft/src/impls/mod.rs, openraft/src/lib.rs, openraft/src/raft/declare_raft_types_test.rs, openraft/src/raft/impl_raft_blocking_write.rs, openraft/src/raft/message/client_write.rs, openraft/src/raft/message/mod.rs, openraft/src/raft/mod.rs, openraft/src/raft/raft_inner.rs, openraft/src/raft/responder/impls.rs, openraft/src/raft/responder/mod.rs, openraft/src/type_config.rs
This commit introduces the `Responder` trait that defines the mechanism
by which `RaftCore` sends responses back to the client after processing
write requests.  Applications can now customize response handling by
implementing their own version of the `RaftTypeConfig::Responder` trait.
The `Responder::from_app_data(RaftTypeConfig::D)` method is invoked to
create a new `Responder` instance when a client write request is
received.
Once the write operation is completed within `RaftCore`,
`Responder::send(WriteResult)` is called to dispatch the result
back to the client.
By default, `RaftTypeConfig::Responder` retains the existing
functionality using a oneshot channel, ensuring backward compatibility.
This change is non-breaking, requiring no modifications to existing
applications.
- Fix: …
=> Feature: Add `RaftTypeConfig::Responder` to customize returning client write response

openraft/src/core/raft_core.rs, openraft/src/raft/core_state.rs
`RaftCore` should not output ERROR level log on a normal quit.
Reduce ERROR level to INFO.
- Fix: #1096
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/1097)
=> Refactor: Remove inappropraite error log on quit

openraft/src/docs/docs.md, openraft/src/docs/protocol/log_stream.md, openraft/src/docs/protocol/mod.rs, openraft/src/storage/mod.rs
Doc `log_stream.md` discusses the core aspects of streaming log replication.
- Part of #1029
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/1099)
=> Doc: add `log_stream.md`

Cargo.toml, macros/Cargo.toml, macros/src/expand.rs, macros/src/lib.rs, macros/src/lib_readme.md, macros/src/since.rs, macros/src/utils.rs, macros/tests/test_default_types.rs, macros/tests/test_since.rs, openraft/src/lib.rs, openraft/src/raft/declare_raft_types_test.rs, openraft/src/raft/message/client_write.rs, openraft/src/raft/mod.rs
By rewriting the template expanding part with a `#[proc_macro]`
`expand!()` defined in `openraft_macros`, `declare_raft_types`
does not require the types in fixed order:
Example:
```
declare_raft_types!(All:
D = (),
NodeId = u64,
R = (),
Node = (),
```
`expand!()` renders a template with arguments multiple times.
```rust,ignore
expand!(KEYED, // ignore duplicate by `K`
(K, T, V) => {let K: T = V;},
(a, u64, 1),
(a, u32, 2), // duplicate `a` will be ignored
(c, Vec<u8>, vec![1,2])
);
```
The above code will be transformed into:
```rust,ignore
let a: u64 = 1;
let c: Vec<u8> = vec![1, 2];
```
`#[since(version = "1.0.0")]` adds a doc line `/// Since: Version(1.0.0)`.
Example:
```rust,ignore
/// Foo function
#[since(version = "1.0.0")]
fn foo() {}
```
The above code will be transformed into: …
=> Improve: `declare_raft_types` allows the types in any order

openraft/src/storage/helper.rs, openraft/src/testing/suite.rs
I hereby agree to the terms of the CLA available at: https://docs.databend.com/dev/policies/cla/
Modify `StorageHelper::last_membership_in_log()` to scan the log
starting from the last applied index rather than the index of the last
applied membership log. This change reduces unnecessary I/O operations
during startup, previously caused by scanning from an incorrect starting
point.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/1105)
=> Fix: Load mebmership since `last_applied`, not `last_membership.index` on startup

.github/workflows/ci.yaml, openraft/src/network/snapshot_transport.rs
When a `SnapshotMismatch` is received, the sending end should re-send
all snapshot data from the beginning.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/1113)
=> Fix: `Chunked` should reset offset 0 when a `SnapshotMismatch` error is received

openraft/src/engine/engine_impl.rs, openraft/src/engine/handler/following_handler/install_snapshot_test.rs, openraft/src/engine/handler/following_handler/mod.rs, openraft/src/engine/mod.rs, openraft/src/engine/tests/install_full_snapshot_test.rs
When `Engine::handle_install_full_snapshot()` is called and the provided
snapshot is not up-to-date, the snapshot should not be installed, and
the response should be sent back immediately. Previously, the method
might delay the response unnecessarily, waiting for an installation
process that would not proceed.
This commit adjusts the logic so that if the snapshot is recognized as
outdated, it immediately returns a `None` `Condition`, ensuring the
caller is informed straightaway that no installation will occur.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/1116)
=> Fix: immediate response when snapshot installation is unnecessary

examples/raft-kv-memstore/src/lib.rs, examples/raft-kv-memstore/src/store/mod.rs, examples/raft-kv-memstore/src/test.rs, openraft/src/testing/suite.rs
The `raft-kv-memstore` example made some inaccurate assumptions, which this PR aims to resolve by making locking more strict and thereby eliminating the following race conditions:
1. The fact that `build_snapshot` would not be invoked concurrently by the OpenRaft runtime is currently correct, but might not remain true in the future. If this were to happen in the future, this could constitute a race condition.
2. `build_snapshot` and `install_snapshot` might be invoked concurrently on a follower that has log compaction enabled. This could also constitute a race condition, even under the current runtime.
Also in this PR:
1. Wrote a test for snapshot transfer between state machine stores, since this was missing from the test suite and the PR alters the snapshotting logic
2. Use AtomicU64 …
=> Avoid race conditions in `raft-kv-memstore` example

openraft/Cargo.toml, openraft/src/lib.rs, openraft/src/raft/mod.rs, openraft/src/raft/trigger.rs, openraft/src/storage/mod.rs, openraft/src/type_config.rs, scripts/watch-doc.sh
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/1122)
=> Doc: Add link to `Raft::trigger()` for doc of `Trigger`, disable appearence order in doc page

examples/raft-kv-memstore-network-v2/src/network.rs, examples/raft-kv-memstore-opendal-snapshot-data/src/network.rs, openraft/src/network/snapshot_transport.rs, openraft/src/network/v2/adapt_v1.rs, openraft/src/network/v2/network.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/1120)
=> Improve: `cancel` passed to `full_snapshot()` should be `static`

openraft/src/core/raft_core.rs, openraft/src/engine/command.rs, openraft/src/engine/engine_impl.rs, openraft/src/engine/engine_output.rs, openraft/src/engine/handler/following_handler/mod.rs, openraft/src/engine/handler/leader_handler/mod.rs, openraft/src/engine/handler/replication_handler/mod.rs, openraft/src/engine/log_id_list.rs, openraft/src/engine/tests/elect_test.rs, openraft/src/engine/tests/handle_vote_resp_test.rs, openraft/src/engine/tests/initialize_test.rs, openraft/src/leader/leader.rs, openraft/src/raft_state/mod.rs, tests/tests/append_entries/t10_see_higher_vote.rs
This commit addresses a critical issue where if a new leader does not
flush the blank log to disk upon becoming established and then restarts
immediately, there is a possibility that previously committed data
becomes invisible to readers.
Before the blank log is flushed, the leader (identified by vote `v3`)
assumes it will be flushed and commits this log once (|quorum|-1)
replication responses are received. If the blank log is lost and the
server is restarted, data committed by a new leader (vote `v2`) may
not be visible.
This issue is addressed by utilizing `LeaderHandler::leader_append_entries()`
instead of `ReplicationHandler::append_blank_log()`, where the former
does not wait for the blank log to flush.
Changes:
- When assigning log IDs to log entries, the `Leading.last_log_id`, …
=> Fix: New leader must flush blank log

openraft/src/engine/handler/following_handler/mod.rs, openraft/src/engine/handler/leader_handler/mod.rs, openraft/src/raft_state/io_state/log_io_id.rs, openraft/src/vote/leader_id/impl_into_leader_id.rs
In this commit, `LeaderId` has been replaced with `CommittedLeaderId`
for identifying log IO requests. This change is made because
`CommittedLeaderId` is shorter and sufficiently identifies the necessary
attributes since only an established leader (a committed leader) can
write or replicate logs. Thus, using `CommittedLeaderId` streamlines the
identification process for log IO requests.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/1127)
=> Refactor: Use `CommittedLeaderId` in place of `LeaderId` for `LogIOId`

openraft/src/progress/mod.rs
This PR only modifies the comment of the VecProgress::update_with method to make it easier to understand.
**Checklist**
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/1132)
=> Chore: adjust the comment of VecProgress::update_with method

openraft/src/replication/mod.rs, openraft/src/storage/mod.rs, openraft/src/testing/suite.rs
This commit adds the `RaftLogReader::limited_get_log_entries()` method,
which enables applications to fetch log entries that are equal to or
smaller than a specified range. This functionality is particularly
useful for customizing the size of AppendEntries requests at the storage
API level.
- Applications can now decide the number of log entries to return based
on the input range. If the application determines that the requested
log entries range is too large for a single RPC, it can opt to return
only the first several requested log entries instead of the full
range.
- The method provides a default implementation that delegates the
operation to `RaftLogReader::try_get_log_entries`.
This enhancement allows for more flexible and efficient handling of log
entries, particularly in scenarios …
=> Feature: Add `RaftLogReader::limited_get_log_entries()`

examples/raft-kv-rocksdb/src/lib.rs, examples/raft-kv-rocksdb/tests/cluster/test_cluster.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/1138)
=> Chore: extend sleep time for rafk-kv-rocksdb example

examples/raft-kv-memstore-network-v2/src/lib.rs, examples/raft-kv-memstore-network-v2/src/network.rs, examples/raft-kv-memstore-network-v2/src/router.rs, examples/raft-kv-memstore-opendal-snapshot-data/src/lib.rs, examples/raft-kv-memstore-opendal-snapshot-data/src/network.rs, examples/raft-kv-memstore-opendal-snapshot-data/src/router.rs, openraft/src/error.rs, openraft/src/error/decompose.rs, openraft/src/error/into_ok.rs, openraft/src/error/streaming_error.rs, openraft/src/network/v2/adapt_v1.rs, openraft/src/network/v2/network.rs, openraft/src/replication/callbacks.rs, openraft/src/replication/mod.rs, openraft/src/replication/request.rs
This commit updates `RaftNetworkV2` to treat any remote errors occurring
during RPC, like a `Fatal` error, as an `Unreachable` error. This is due
to Openraft's current inability to distinguish between an unreachable
node and a broken node.
Other changes:
- **Helper trait `DecomposeResult`:** Introduced to simplify handling
composite errors. It converts a result of the
form `Result<R, ErrorAOrB>`
into a nested result `Result<Result<R, ErrorA>, ErrorB>`.
Upgrade tip:
- Implementations of `RaftNetworkV2` or `RaftNetwork` should now convert
remote errors such as `Raft::Fatal` to `Unreachable` errors to
maintain consistency in error handling.
- - - …
=> Change: `RaftNetworkV2` treat remote error as `Unreachable`

openraft/src/engine/engine_impl.rs, openraft/src/engine/handler/vote_handler/mod.rs, openraft/src/engine/tests/elect_test.rs, openraft/src/engine/tests/handle_vote_resp_test.rs
This commit addresses an issue in the vote updating mechanism during the
handling of `RequestVote` responses. Previously, encountering a higher
`vote` in a response incorrectly led to an update of the local
`state.vote`, which could break Raft consistency rules.
**Issue Description:**
- A higher `vote` seen in a `RequestVote` response does not necessarily
mean that the vote is granted. The local `state.vote` should only be
updated if the vote is actually granted, i.e., the responding node has
a higher `vote` and a `last_log_id` that allows it to become a leader.
**Resolution:**
- The local `state.vote` will no longer be updated upon merely seeing a
higher `vote` in the `RequestVote` response. Instead, this higher vote
will be recorded in `last_seen_vote` for consideration in the next …
=> Fix: Should not update `vote` when seeing higher vote in `RequestVote` response

openraft/src/core/raft_core.rs, openraft/src/core/sm/handle.rs, openraft/src/core/tick.rs, openraft/src/display_ext.rs, openraft/src/engine/engine_impl.rs, openraft/src/engine/handler/vote_handler/accept_vote_test.rs, openraft/src/engine/handler/vote_handler/mod.rs, openraft/src/engine/tests/install_full_snapshot_test.rs, openraft/src/lib.rs, openraft/src/metrics/wait.rs, openraft/src/network/snapshot_transport.rs, openraft/src/proposer/leader.rs, openraft/src/raft/mod.rs, openraft/src/raft/responder/impls.rs, openraft/src/replication/mod.rs, openraft/src/replication/response.rs, openraft/src/storage/helper.rs, openraft/src/storage/v2/raft_log_storage_ext.rs, openraft/src/testing/suite.rs, openraft/src/type_config.rs, openraft/src/type_config/util.rs, tests/tests/append_entries/t60_enable_heartbeat.rs, tests/tests/metrics/t10_leader_last_ack.rs
This commit introduces a new trait, `TypeConfigExt`, which extends
`RaftTypeConfig`. The purpose of this trait is to simplify the access to
various functionalities provided by the `RaftTypeConfig` trait,
enhancing code readability and reducing complexity.
**Methods Added to `TypeConfigExt`:**
- `now()`
- `sleep()`
- `sleep_until()`
- `timeout()`
- `timeout_at()`
- `oneshot()`
- `spawn()`
**Usage Improvement:**
- Instead of using the
`<<C as RaftTypeConfig>::AsyncRuntime as AsyncRuntime>::Instant::now()`,
you can now simply call `C::now()`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/1145)
=> Feature: Add `TypeConfigExt` to simplify `RaftTypeConfig` Access

openraft/src/core/raft_core.rs, openraft/src/engine/engine_impl.rs, openraft/src/engine/handler/leader_handler/mod.rs, openraft/src/engine/handler/vote_handler/mod.rs, openraft/src/proposer/candidate.rs, openraft/src/proposer/leader.rs, openraft/src/raft_state/mod.rs, openraft/src/replication/replication_session_id.rs, openraft/src/vote/committed.rs, openraft/src/vote/mod.rs, openraft/src/vote/vote.rs
This commit introduces a new type, `CommittedVote`, which represents a
committed vote. This enhancement is aimed at ensuring that only
committed votes are considered valid for the leader's status.
By using the `CommittedVote` type, we can eliminate several runtime
assertion checks previously required to verify the commitment status of
votes.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/1149)
=> Refactor: Introduce `CommittedVote` Type to Enhance Vote Handling

openraft/src/core/raft_core.rs, openraft/src/engine/command.rs, openraft/src/engine/engine_impl.rs, openraft/src/engine/engine_output.rs, openraft/src/engine/handler/following_handler/install_snapshot_test.rs, openraft/src/engine/handler/following_handler/mod.rs, openraft/src/engine/handler/following_handler/truncate_logs_test.rs, openraft/src/engine/handler/server_state_handler/mod.rs, openraft/src/engine/handler/server_state_handler/update_server_state_test.rs, openraft/src/engine/handler/vote_handler/mod.rs, openraft/src/engine/tests/append_entries_test.rs, openraft/src/engine/tests/handle_vote_resp_test.rs, openraft/src/engine/tests/startup_test.rs, openraft/src/proposer/leader.rs, openraft/src/raft/mod.rs
`LeaderData` stores heartbeat time which is now stored in `Engine.leader`.
Remove `Command::BecomeLeader` and `Command::QuitLeader`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/1151)
=> Refactor: Remove `LeaderData` from `RaftCore`

openraft/src/core/raft_core.rs, openraft/src/core/sm/command.rs, openraft/src/core/sm/worker.rs, openraft/src/raft/mod.rs
This commit optimizes the process of applying log entries to the state
machine by moving the log reading responsibilities from `RaftCore` to
the state machine worker.
The state machine worker runs in a separate task, ensuring that the
`RaftCore` main task is not blocked by applying log entries.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/1154)
=> Refactor: Move Log Reading to State Machine Worker

openraft/src/async_runtime.rs, openraft/src/core/raft_core.rs, openraft/src/core/sm/worker.rs, openraft/src/engine/command.rs, openraft/src/raft/mod.rs, openraft/src/raft/responder/impls.rs, openraft/src/storage/callback.rs, openraft/src/timer/timeout_test.rs
**Removal of `TokioOneShotSender`:** Previously,
`TokioOneShotSender(tokio::sync::oneshot::Sender)` was used to
implement `Debug` for a oneshot sender. Given that `Debug`
implementation is not a mandatory requirement, `TokioOneShotSender` is
no longer necessary and has been removed.
**Rename `AsyncOneshotSendExt` to `OneshotSender`:** The renaming
reflects a more streamlined and intuitive naming convention.
Upgrade tip:
- rename `AsyncOneshotSendExt` to `OneshotSender`
---
- `AsyncOneshotSendExt` and `TokioOneShotSender` are introduced in #1026
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/1157)
=> Change: rename `AsyncOneshotSendExt` to `OneshotSender`, remove `TokioOneShotSender`

openraft/src/core/tick.rs, openraft/src/engine/testing.rs, openraft/src/impls/mod.rs, openraft/src/lib.rs, openraft/src/raft/declare_raft_types_test.rs, openraft/src/raft/raft_inner.rs, openraft/src/timer/timeout.rs, openraft/src/timer/timeout_test.rs, openraft/src/type_config.rs, openraft/src/type_config/async_runtime/impls/tokio_runtime.rs, openraft/src/type_config/async_runtime/mod.rs, openraft/src/type_config/async_runtime/oneshot.rs, openraft/src/type_config/util.rs, tests/tests/append_entries/t60_enable_heartbeat.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/1158)
=> Refactor: move async-runtime to dir `type_config/async_runtime/`

openraft/src/core/raft_core.rs, openraft/src/core/sm/handle.rs, openraft/src/core/sm/worker.rs, openraft/src/core/tick.rs, openraft/src/raft/mod.rs, openraft/src/raft/raft_inner.rs, openraft/src/replication/mod.rs, openraft/src/type_config.rs, openraft/src/type_config/async_runtime/impls/tokio_runtime.rs, openraft/src/type_config/async_runtime/mod.rs, openraft/src/type_config/async_runtime/mpsc_unbounded/mod.rs, openraft/src/type_config/async_runtime/mpsc_unbounded/send_error.rs, openraft/src/type_config/async_runtime/mpsc_unbounded/try_recv_error.rs, openraft/src/type_config/util.rs
- Part of: #1013
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/1159)
=> Feature: `AsyncRuntime::MpscUnbounded` to abstract mpsc channels

openraft/src/core/raft_core.rs, openraft/src/engine/handler/replication_handler/mod.rs
When a replication response is handled, RaftCore should initiate next
replication if there are more logs to to replicate.
Before this commit this is done in response-handler.
In this commit it is moved to `RaftCore::runtime_loop`:
replications are re-initiated when all of the events are processed.
This way the replication response handler is simplified.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/1164)
=> Refactor: Initiate replication per event loop

Cargo.toml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/1165)
=> Dep: Require tokio 1.22 for WeakUnboundedSender

openraft/src/engine/engine_impl.rs, openraft/src/engine/handler/vote_handler/mod.rs, openraft/src/engine/tests/startup_test.rs, openraft/src/proposer/leader.rs
This commit enhances the initialization process of a `Leader` instance
by automating the setup of progress information and replication streams.
Previously, these tasks were manually performed by the caller after the
leader's creation, which could lead to inconsistencies or additional
complexity.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/1166)
=> Refactor: Automate Initialization of Leader Progress and Replication

openraft/src/type_config/async_runtime/watch/mod.rs
- `WatchSender` is added in: 1b4ec53df2c548757607261e88287a2fd6cb5131
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/1171)
=> Change: Openraft does not require `Clone` for `WatchSender`

openraft/src/core/notification.rs, openraft/src/core/raft_core.rs, openraft/src/core/raft_msg/mod.rs, openraft/src/core/sm/command.rs, openraft/src/core/sm/response.rs, openraft/src/display_ext.rs, openraft/src/display_ext/display_result.rs, openraft/src/display_ext/display_slice.rs, openraft/src/engine/command.rs, openraft/src/engine/handler/leader_handler/append_entries_test.rs, openraft/src/engine/handler/replication_handler/append_membership_test.rs, openraft/src/engine/handler/replication_handler/mod.rs, openraft/src/engine/mod.rs, openraft/src/engine/replication_progress.rs, openraft/src/engine/tests/handle_vote_resp_test.rs, openraft/src/engine/tests/startup_test.rs, openraft/src/log_id/mod.rs, openraft/src/raft_state/io_state/append_log_io_id.rs, openraft/src/replication/response.rs, openraft/src/summary.rs, openraft/src/vote/vote.rs
This commit refines our logging strategy by utilizing the `Display`
trait instead of `Debug` for significant events. This change is aimed at
producing logs that are easier to read and understand.
Three kinds of significant events are logged at DEBUG level:
- `input`: the `RaftMsg`s received by `RaftCore`, such as client-write
or AppendEntries request from the Leader.
- `cmd`: the `Command` outputted by `Engine` to execute by storage or
network layer, such as `AppendInputEntries` or `ReplicateCommitted`.
- `notify`: the `Notification`s received by `RaftCore` from storage or
network.
Example significant event logs:
```
RAFT_event id=0     cmd: Commit: seq: 5, (T1-N0.4, T1-N0.5]
RAFT_event id=1   input: AppendEntries: vote=<T1-N0:Q>, prev_log_id=T1-N0.5, leader_commit=T1-N0.5, entries=[] …
```
=> Refactor: log significant events with `Display`

examples/raft-kv-memstore-opendal-snapshot-data/src/lib.rs, openraft/src/docs/getting_started/getting-started.md
- Fix: #1168
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/1181)
=> Doc: explain default types used by `RaftTypeConfig` in getting-started.md

openraft/src/docs/faq/faq.md
- Fix: #1175
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/1182)
=> Doc: in FAQ: add: RaftServerMetrics to subscribe server state change

openraft/src/core/notification.rs, openraft/src/core/raft_core.rs, openraft/src/engine/handler/following_handler/mod.rs, openraft/src/replication/mod.rs, openraft/src/replication/response.rs, openraft/src/storage/callback.rs
Whne a `StorageError` occurs locally during replication,
the `RaftCore` has to be shutdown at once. in this case, just send a
generic notification `Notification::StorageError`. There is no need for
`replication::Response` to contain `StorageError`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/1186)
=> Refactor: remove `replication::Response::StorageError`

openraft/src/core/raft_core.rs, openraft/src/display_ext.rs, openraft/src/display_ext/display_btreemap_opt_value.rs, openraft/src/metrics/mod.rs, openraft/src/metrics/raft_metrics.rs, openraft/src/metrics/wait_test.rs, tests/tests/metrics/t10_server_metrics_and_data_metrics.rs
**Checklist**
Will check the above stuff when this PR is no longer a draft:)
-----
This PR attempts to implement the metric discussed in [this thread][link], 
adding the `heartbeat` information (time of the last replication or heartbeat) to
`RaftDataMetrics` and `RaftMetrics` so that users can subscribe to it.
[link]: https://github.com/datafuselabs/openraft/discussions/1174#discussioncomment-10079172
It is a draft PR as I want to ensure it looks basically correct, then I will
try to add tests, code documents, and polish interfaces.
For the time type, I used `RaftTypeConfig::AsyncRuntime::Instant` as it is used 
widely.
And I found the last applied log ID is stored in `struct ProcessEntry`, so I 
stored this time information there as well. When a response to a replication 
request is …
=> Feature: store heartbeat metric in RaftMetrics and RaftDataMetrics

examples/raft-kv-memstore-network-v2/tests/cluster/test_cluster.rs, examples/raft-kv-memstore-opendal-snapshot-data/tests/cluster/test_cluster.rs, examples/raft-kv-memstore-singlethreaded/tests/cluster/test_cluster.rs, examples/raft-kv-memstore/tests/cluster/test_cluster.rs, examples/raft-kv-rocksdb/tests/cluster/test_cluster.rs
Rust nightly 1.82 renamed `std::panic::PanicInfo` to `std::panic::PanicHookInfo` and [mark the old name deprecated](https://doc.rust-lang.org/nightly/std/panic/type.PanicInfo.html), this change is currently exclusive to nightly toolchain 1.82.0 and higher.
Based on our [discussion](https://github.com/datafuselabs/openraft/pull/1177#issuecomment-2241954264), allow them.
**Checklist**
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/1188)
=> Test: allow deprecated std::panic::PanicInfo in example tests

openraft/src/engine/command.rs, openraft/src/engine/handler/vote_handler/mod.rs, openraft/src/lib.rs, openraft/src/storage_error.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/1187)
=> Chore: mark StorageIOError as deprecated

openraft/src/raft/mod.rs
Mention that one can check if a cluster is initialized using `Raft::is_initialized()` in the document of `Raft::initialize()` in case someone want to get rid of that `InitializeError::NotAllowed` error.
**Checklist**
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/1190)
=> Doc: mention is_initialized() in initialize()'s doc

openraft/src/membership/membership_test.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/1193)
=> Chore: add test to ensure change_membership(.., retain=false) wont remove existing learners

openraft/src/raft/impl_raft_blocking_write.rs
The unaffected Learner won't be removed during membership change.
- Discussion: #1191
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/1194)
=> Doc: fix description of `retain` in `change_membership()`

openraft/src/docs/protocol/log_replication.md, openraft/src/raft_state/io_state/io_id.rs, openraft/src/raft_state/io_state/log_io_id.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/1195)
=> Doc: Add example explaining why `LogIOId` must be `(CommittedLeaderId, LogId)`

openraft/src/raft/impl_raft_blocking_write.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/1199)
=> Doc: "learners" in the `change_membership()` doc shoudl be "nodes", which represent both voters and learners

openraft/src/core/raft_core.rs, openraft/src/engine/handler/replication_handler/mod.rs, openraft/src/engine/handler/vote_handler/mod.rs, openraft/src/error.rs, openraft/src/metrics/mod.rs, openraft/src/metrics/raft_metrics.rs, openraft/src/metrics/serde_instant.rs, openraft/src/metrics/wait_test.rs, openraft/src/proposer/leader.rs, openraft/src/replication/mod.rs, scripts/check.kdl, tests/tests/fixtures/mod.rs, tests/tests/metrics/t10_leader_last_ack.rs
`RaftMetrics::last_quorum_acked` is the absolute timestamp of the most
recent time point that is accepted by a quorum via `AppendEntries` RPC.
This field is a wrapped `Instant` type: `SerdeInstant` which support
serde for `Instant`. This field is added as a replacement of
`millis_since_quorum_ack`, which is a relative time.
`SerdeInstant` serialize `Instant` into a string formatted as
"%Y-%m-%dT%H:%M:%S%.9f%z", e.g., "2024-07-24T04:07:32.567025000+0000".
Note: Serialization and deserialization are not perfectly accurate and
can be indeterministic, resulting in minor variations each time. These
deviations(could be smaller or greater) are typically less than a
microsecond (10^-6 seconds).
- - - …
=> Feature: add absolute timestamp `RaftMetrics::last_quorum_acked`

openraft/src/proposer/leader.rs
`Leader::assign_doc_ids()` no longer has a return value since #1143, so updates the doc.
**Checklist**
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/1201)
=> Doc: update doc of Leader::assign_doc_ids()

openraft/src/raft/responder/impls.rs, openraft/src/type_config.rs, openraft/src/type_config/async_runtime/impls/tokio_runtime.rs, openraft/src/type_config/async_runtime/mod.rs, openraft/src/type_config/async_runtime/oneshot.rs, openraft/src/type_config/util.rs
Exposes `Oneshot` via `trait Oneshot`.
Closes #1198 
**Checklist**
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/1200)
=> Refactor: expose AsyncRuntime Oneshot via trait

openraft/src/type_config/async_runtime/mod.rs
A tiny change, make module `oneshot` public, I forgot to do this in #1200 and just found it while trying to write `impl oneshot::Oneshot for Xxx` :<
**Checklist**
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/1203)
=> Chore: make module oneshot pub

openraft/src/core/raft_core.rs, openraft/src/engine/handler/replication_handler/mod.rs, openraft/src/metrics/mod.rs, openraft/src/metrics/raft_metrics.rs, openraft/src/metrics/serde_instant.rs, openraft/src/progress/bench/vec_progress_update.rs, openraft/src/progress/mod.rs, openraft/src/proposer/candidate.rs, openraft/src/proposer/leader.rs, openraft/src/raft/impl_raft_blocking_write.rs, openraft/src/type_config.rs, tests/tests/metrics/t10_server_metrics_and_data_metrics.rs
Other changes: Display human readable Instant in log
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/1202)
=> Refactor: `RaftMetrics::heartbeat` stores last-acked timestamp instead of duration since last ack

openraft/src/core/tick.rs, openraft/src/replication/mod.rs, openraft/src/storage/callback.rs
Replace the usage of `tokio::sync::oneshot` with the one configured in `RaftTypeConfig`.
**Checklist**
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/1204)
=> Refactor: replace tokio oneshot with the one configured

openraft/src/engine/engine_impl.rs, stores/memstore/src/lib.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/1210)
=> Refactor: remove unused client_serial_responses from memstore

openraft/src/raft/core_state.rs, openraft/src/raft/mod.rs, openraft/src/raft/raft_inner.rs
In this commit, when joining the `RaftCore` task, the `core_state` is
first switched from `Running` to `Joining`. The thread then blocks
while awaiting the completion of the `RaftCore` task. Any other threads
observing the `Joining` state will wait for the first thread to finish
by monitoring a `watch` channel created by the initial thread.
`RaftInner::tx_shutdown` has been changed to use a standard
(synchronous) Mutex instead of an asynchronous one. This change is made
because `tx_shutdown` does not span across `.await` points, making the
asynchronous capabilities unnecessary.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/1211)
=> Refactor: Replace async Mutex for `RaftInner.core_state` with standard Mutex and a watch channel

openraft/src/raft/mod.rs, openraft/src/raft/raft_inner.rs, openraft/src/replication/mod.rs, openraft/src/type_config.rs, openraft/src/type_config/async_runtime/impls/tokio_runtime.rs, openraft/src/type_config/async_runtime/mod.rs, openraft/src/type_config/async_runtime/mutex.rs, openraft/src/type_config/util.rs
As discussed in #1208, add the `Mutex` primitive to trait `AsyncRuntime`.
~~It is still a draft PR because I hit this issue [Unexpected higher-ranked lifetime error in GAT usage](https://github.com/rust-lang/rust/issues/100013) and am still trying to find a workaround that works for us:~~
```sh
$ cd openraft/openraft
$ cargo c
Checking openraft v0.10.0 (openraft/openraft)
error: lifetime bound not satisfied
--> openraft/src/replication/mod.rs:738:18
|
738 |         let jh = C::spawn(Self::send_snapshot(
|                  ^^^^^^^^
|
= note: this is a known limitation that will be removed in the future (see issue #100013 <https://github.com/rust-lang/rust/issues/100013> for more information)
error: could not compile `openraft` (lib) due to 1 previous error
```
**Checklist**
- - -
This …
=> Change: add Mutex to AsyncRuntime

openraft/src/core/raft_core.rs, openraft/src/engine/engine_impl.rs, openraft/src/engine/handler/vote_handler/mod.rs, openraft/src/utime.rs
This commit modifies the election process within the Raft algorithm to
consider the lease duration stored in `RaftState.vote` when determining
whether a follower or candidate should initiate an election to become
the new leader. Previously, this decision was based solely on a static
configuration value.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/1215)
=> Refactor: Use stored lease in `RaftState.vote` for election decisions

openraft/src/core/raft_core.rs, openraft/src/core/raft_msg/mod.rs, openraft/src/metrics/raft_metrics.rs, openraft/src/metrics/wait.rs, openraft/src/raft/mod.rs, openraft/src/utime.rs, tests/tests/client_api/main.rs, tests/tests/client_api/t14_transfer_leader.rs
This methods force a node to invalidate current Leader's lease and start
to elect for the next new Leader.
It wont do anything if the current Leader has changed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/1218)
=> Feature: Add `Raft::transfer_leader()`

openraft/src/core/raft_core.rs, openraft/src/engine/engine_impl.rs, openraft/src/engine/handler/vote_handler/accept_vote_test.rs, openraft/src/engine/handler/vote_handler/mod.rs, openraft/src/engine/tests/elect_test.rs, openraft/src/engine/tests/handle_vote_req_test.rs, openraft/src/engine/tests/handle_vote_resp_test.rs, openraft/src/raft/message/vote.rs
A node's `vote` may be updated when a leader observes a higher vote.
In such cases, the leader updates its local vote and steps down.
However, this vote update does not imply that the node accepts the
higher vote as valid for leadership, as it has not yet compared their
logs.
In this commit, re-enable `VoteResponse.vote_granted` to indicate a vote
is granted.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/1220)
=> Fix: (0.10) Clarify that receiving an equal vote does not grant leadership.

openraft/src/core/raft_core.rs, openraft/src/core/raft_msg/external_command.rs, openraft/src/core/raft_msg/mod.rs, openraft/src/engine/command.rs, openraft/src/engine/engine_impl.rs, openraft/src/engine/handler/leader_handler/mod.rs, openraft/src/engine/handler/leader_handler/transfer_leader_test.rs, openraft/src/engine/handler/vote_handler/mod.rs, openraft/src/error.rs, openraft/src/error/streaming_error.rs, openraft/src/network/rpc_type.rs, openraft/src/network/v2/network.rs, openraft/src/proposer/leader.rs, openraft/src/raft/message/mod.rs, openraft/src/raft/message/transfer_leader.rs, openraft/src/raft/mod.rs, openraft/src/raft/trigger.rs, openraft/src/raft_state/mod.rs, openraft/src/replication/mod.rs, openraft/src/utime.rs, tests/tests/append_entries/t10_conflict_with_empty_entries.rs, tests/tests/append_entries/t10_see_higher_vote.rs, tests/tests/append_entries/t11_append_entries_with_bigger_term.rs, tests/tests/client_api/t14_transfer_leader.rs, tests/tests/fixtures/mod.rs, tests/tests/snapshot_building/t10_build_snapshot.rs, tests/tests/snapshot_building/t35_building_snapshot_does_not_block_append.rs, tests/tests/snapshot_building/t35_building_snapshot_does_not_block_apply.rs, tests/tests/snapshot_streaming/t31_snapshot_overrides_membership.rs, tests/tests/snapshot_streaming/t33_snapshot_delete_conflict_logs.rs
Call `Raft.trigger().transfer_leader(to)` to inform the raft node to
transfer its leadership to Node `to`.
This feature is enabled only when: the application uses `RaftNetworkV2`
and implements the `RaftNetworkV2::transfer_leader()` methods. This method
provides a default implementation that returns an `Unreachable`, and
such an error will be just ignored.
Application upgrading Openraft from older version does not need to modify any
codes, unless TransferLeader is required.
Upgrade tip:
Implement `RaftNetworkV2::transfer_leader()` to send the
`TransferLeaderRequest` to the target node.
The target node that receives this request should then pass it to
`Raft::transfer_leader()`.
- - - …
=> Feature: Transfer Leader

cluster_benchmark/tests/benchmark/store/test.rs, examples/raft-kv-memstore/src/test.rs, openraft/src/docs/getting_started/getting-started.md, openraft/src/testing/suite.rs, stores/memstore/src/test.rs, stores/rocksstore/Cargo.toml, stores/rocksstore/src/lib.rs, stores/rocksstore/src/test.rs, stores/sledstore/Cargo.toml, stores/sledstore/src/test.rs
Based on the discussion in this [thread](https://github.com/datafuselabs/openraft/pull/113#discussion_r1703627343), turning `test_all()` and `test_store()` asynchronous to make the log tests runtime-agnostic.
**Checklist**
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/1227)
=> Test: make store/state machine tests rt-agnostic

openraft/src/lib.rs
Since the log test suite is rt-agnostic now, we should no longer gate it with feature `tokio-rt`. This tiny patch should be included in #1227, sorry for missing it.
**Checklist**
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/1228)
=> Chore: don't gate mod testing with feat tokio-rt

openraft/src/core/heartbeat/event.rs, openraft/src/core/heartbeat/handle.rs, openraft/src/core/heartbeat/mod.rs, openraft/src/core/heartbeat/worker.rs, openraft/src/core/mod.rs, openraft/src/core/notification.rs, openraft/src/core/raft_core.rs, openraft/src/engine/command.rs, openraft/src/engine/handler/leader_handler/mod.rs, openraft/src/engine/handler/leader_handler/send_heartbeat_test.rs, openraft/src/engine/handler/replication_handler/mod.rs, openraft/src/engine/handler/vote_handler/mod.rs, openraft/src/progress/inflight/mod.rs, openraft/src/raft/message/append_entries.rs, openraft/src/raft/mod.rs, openraft/src/replication/mod.rs, openraft/src/replication/replication_session_id.rs, openraft/src/replication/response.rs, openraft/src/storage/callback.rs, tests/tests/snapshot_streaming/t60_snapshot_chunk_size.rs
Heavy AppendEntries traffic can block heartbeat messages. For example,
future AppendEntries in stream RPC may not receive a response indicating
a follower is alive. In such cases, the leader might time out to extend
its lease, and be considered partitioned from the cluster.
This commit moves heartbeat broadcasting to separate tasks that won't be
blocked by AppendEntries. This ensures the leader can always be
acknowledged with the liveness of followers.
Separate log progress notification and clock progress notification:
When ReplicationCore successfully finished one RPC to Follower/Learner,
it informs the RaftCore to update log progress and clock(heartbeat) progress.
This commit split these two informations into two `Notification`
variants, in order to make progress handling more clear. …
=> Refactor: Send heartbeat with dedicated workers

openraft/src/testing/runtime/mod.rs, openraft/src/type_config.rs, openraft/src/type_config/async_runtime/mod.rs, openraft/src/type_config/async_runtime/mpsc/mod.rs, openraft/src/type_config/async_runtime/tokio_impls/tokio_runtime.rs, openraft/src/type_config/util.rs, rt-monoio/Cargo.toml, rt-monoio/src/lib.rs
`AsyncRuntime` trait defines the async-runtime such as tokio to run
Openraft. This commit add MPSC abstraction to `AsyncRuntime` and
MPSC implementations to tokio based runtime and monoio based runtime.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/1233)
=> Feature: Add MPSC channel to AsyncRuntime

examples/raft-kv-memstore-network-v2/src/store.rs, examples/raft-kv-memstore-opendal-snapshot-data/src/store.rs, examples/raft-kv-memstore-singlethreaded/src/store.rs, examples/raft-kv-memstore/src/store/mod.rs, openraft/src/docs/internal/architecture.md, openraft/src/error/streaming_error.rs, openraft/src/raft/raft_inner.rs
- Part of: #1225
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/1239)
=> Doc: update architecture: add heartbeat worker

openraft/src/type_config/async_runtime/watch/mod.rs
Add comprehensive documentation for the `Watch` trait and its associated traits
in the `AsyncRuntime` module. This improves code clarity and helps developers
understand the purpose and usage and behavior of these traits.
- Fix: #1238
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/1240)
=> Doc: Add documentation for `AsyncRuntime::Watch` traits

openraft/src/metrics/mod.rs, openraft/src/metrics/raft_metrics.rs
Updates the doc of the `heartbeat` field of `RaftMetrics` and `RaftDataMetrics` as we store the timestamp itself rather than the duration since the last acknowledged heartbeat/replication timestamp since #1202.
**Checklist**
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/1241)
=> Doc: update doc of heartbeat metric

openraft/src/membership/membership.rs, openraft/src/quorum/coherent_impl.rs, tests/tests/membership/main.rs, tests/tests/membership/t52_change_membership_on_uninitialized_node.rs
Previously, `change_membership()` assumed the current membership config was
always non-empty and used the last config entry. However, uninitialized
nodes lack a membership config, leading to panics.
This commit adds checks to prevent `change_membership()` from panicking
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/1243)
=> Fix: Prevent panic when calling `Raft::change_membership()` on uninitialized node

openraft/src/engine/engine_impl.rs, openraft/src/engine/handler/vote_handler/become_leader_test.rs, openraft/src/engine/handler/vote_handler/mod.rs, openraft/src/engine/tests/startup_test.rs, openraft/src/proposer/leader.rs, stores/memstore/src/lib.rs, tests/tests/fixtures/mod.rs, tests/tests/life_cycle/t50_single_leader_restart_re_apply_logs.rs
When a node starts up as the Leader, it now re-applies all logs at once.
Previously:
- New Leader only updated IO progress
- Committed log ID remained unchanged
Now:
- New Leader updates IO progress
- Triggers update of committed log ID
- Fix: #1246
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/1247)
=> Fix: When a Leader starts up, it should re-apply all logs

openraft/src/storage/helper.rs, stores/memstore/Cargo.toml, stores/rocksstore/Cargo.toml, stores/sledstore/Cargo.toml
- Implement chunk-based reading of committed log entries when
re-applying to state machine upon startup.
- Add validation for log entry indexes, to avoid applying wrong entries
to state machine.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/1248)
=> Refactor: Improve log entry processing on startup

openraft/src/core/heartbeat/worker.rs, openraft/src/core/notification.rs, openraft/src/core/raft_core.rs, openraft/src/engine/engine_impl.rs, openraft/src/engine/handler/establish_handler/mod.rs, openraft/src/engine/handler/leader_handler/mod.rs, openraft/src/engine/handler/vote_handler/mod.rs, openraft/src/proposer/leader.rs, openraft/src/raft_state/io_state/io_id.rs, openraft/src/raft_state/mod.rs, openraft/src/replication/mod.rs, openraft/src/replication/replication_session_id.rs, openraft/src/vote/committed.rs, openraft/src/vote/mod.rs, openraft/src/vote/non_committed.rs, openraft/src/vote/ref_vote.rs, openraft/src/vote/vote.rs, openraft/src/vote/vote_status.rs
- **Introduce Specialized Vote Types:**
- Added `CommittedVote` and `NonCommittedVote` to distinguish between votes that have been
accepted by a quorum and those that have not.
- Introduced `RefVote` to provide a reference-based representation of votes, facilitating safer
and more efficient comparisons.
- **Update Vote Management Logic:**
- Replaced direct usage of `Vote` with `CommittedVote` and `NonCommittedVote` across various
modules (`heartbeat/worker.rs`, `notification.rs`, `raft_core.rs`, etc.) to enhance type
safety and clarity.
- Modified comparison logic to leverage the new vote types, ensuring accurate and meaningful
ordering based on vote status.
- **Enhance Notification Mechanisms:**
- Updated notification structures to use the new vote types, improving the accuracy of …
=> Refactor: introducing CommittedVote, NonCommittedVote, and RefVote types

examples/raft-kv-memstore-network-v2/tests/cluster/test_cluster.rs, examples/raft-kv-memstore-opendal-snapshot-data/tests/cluster/test_cluster.rs, examples/raft-kv-memstore-singlethreaded/tests/cluster/test_cluster.rs, examples/raft-kv-memstore/tests/cluster/test_cluster.rs, examples/raft-kv-rocksdb/tests/cluster/test_cluster.rs, openraft/src/core/tick.rs, openraft/src/network/snapshot_transport.rs, openraft/src/network/v2/network.rs, openraft/src/vote/leader_id/leader_id_std.rs, tests/tests/fixtures/mod.rs
- Fix: #1256
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/openraft/1257)
=> Chore: fix feature specific lint warnings

openraft/src/core/raft_core.rs, openraft/src/core/raft_msg/external_command.rs, openraft/src/engine/handler/replication_handler/mod.rs, openraft/src/engine/tests/startup_test.rs, openraft/src/error.rs, openraft/src/error/allow_next_revert_error.rs, openraft/src/error/node_not_found.rs, openraft/src/error/operation.rs, openraft/src/progress/entry/mod.rs, openraft/src/raft/mod.rs, openraft/src/raft/trigger.rs, openraft/src/replication/mod.rs, tests/tests/replication/main.rs, tests/tests/replication/t61_allow_follower_log_revert.rs
This method requests the RaftCore to allow to reset replication for a
specific node when log revert is detected.
- `allow=true`: This method instructs the RaftCore to allow the target
node's log to revert to a previous state for one time.
- `allow=false`: This method instructs the RaftCore to panic if the
target node's log revert
This method returns `Fatal` error if failed to send the request to
RaftCore, e.g. when RaftCore is shut down.
Otherwise, it returns a `Ok(Result<_,_>)`, the inner result is:
- `Ok(())` if the request is successfully processed,
- or `Err(AllowNextRevertError)` explaining why the request is rejected.
- If this node is the Leader, it will attempt to replicate logs to the
target node from the beginning.
- If this node is not the Leader, the request is ignored.
- If …
=> Feature: `Raft::trigger()::allow_next_revert()` allow to reset replication for next detected follower log revert

openraft/src/engine/leader_log_ids.rs, openraft/src/engine/log_id_list.rs, openraft/src/engine/mod.rs, openraft/src/engine/tests/log_id_list_test.rs, openraft/src/proposer/candidate.rs, openraft/src/proposer/leader.rs, openraft/src/storage/helper.rs, openraft/src/storage/log_reader_ext.rs, openraft/src/storage/v2/raft_log_reader.rs, openraft/src/testing/log/suite.rs
Key log IDs represent the first log IDs proposed by each Leader. These
IDs enable Openraft to efficiently access log IDs at each index with
a succinct storage.
Previously, key log IDs were obtained using a binary-search-like
algorithm through `RaftLogReader`. This commit introduces the
`RaftLogReader::get_key_log_ids()` method, allowing implementations to
directly return a list of key log IDs if the `RaftLogStorage` can
provide them.
For backward compatibility, a default implementation using the original
binary-search method is provided. No application changes are required
when upgrading to this version.
Tests verifying the implementation are included in
`openraft::testing::log::suite::Suite`.
- Fixes: #1261
- - -
This change is [<img src="https://reviewable.io/review_button.svg" …
=> Feature: Retrieve Key Log IDs via `RaftLogReader::get_key_log_ids()`

openraft/src/base/mod.rs, openraft/src/node.rs
These two traits are used to simplify NodeId and Node constraints.
But with `Optional*` traits, these two are no longer needed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/openraft/1276)
=> Refactor: remove NodeIdEssential and NodeEssential traits

openraft/src/engine/testing.rs, openraft/src/membership/membership.rs, openraft/src/metrics/wait_test.rs, openraft/src/node.rs, openraft/src/testing/common.rs, openraft/src/testing/log/suite.rs
Openraft internally does not require `Node` to implement `Default`.
`Default for Node` is only required in tests. Therefore in this commit
the `Default` is removed from trait `Node` and the contraint is added to
test suite codes where `Default` is required to build a `node` for
testing.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/openraft/1277)
=> Refactor: `Node` no longer requires `Default`

examples/raft-kv-memstore-grpc/src/lib.rs, openraft/src/engine/log_id_list.rs, openraft/src/log_id/mod.rs, openraft/src/log_id/raft_log_id.rs, openraft/src/proposer/leader.rs, openraft/src/type_config.rs, openraft/src/vote/committed.rs, openraft/src/vote/leader_id/impl_into_leader_id.rs, openraft/src/vote/leader_id/leader_id_adv.rs, openraft/src/vote/leader_id/leader_id_std.rs, openraft/src/vote/ref_vote.rs, openraft/src/vote/vote.rs
This refactoring moves LeaderId from a per-NodeId type to a per-TypeConfig type,
to make it consistent with `RaftTypeConfig` usage across the codebase.
- Part of: #1278
Upgrade tip:
LeaderId is now parameterized by `RaftTypeConfig` instead of `NodeId`
- Change `LeaderId<NodeId>` to `LeaderId<C> where C: RaftTypeConfig`, for
example, change `LeaderId<u64>` to `LeaderId<YourTypeConfig>`.
- Change `CommittedLeaderId<NodeId>` to `CommittedLeaderId<RaftTypeConfig>`.
This refactoring moves LogId from a per-NodeId type to a per-TypeConfig type,
to make it consistent with `RaftTypeConfig` usage across the codebase.
- Part of: #1278
Upgrade tip:
LogId is now parameterized by `RaftTypeConfig` instead of `NodeId`
- Change `LogId<NodeId>` to `LogId<C> where C: RaftTypeConfig`, for
example, change …
=> Change: change `LeaderId<NID:NodeId>` to `LeaderId<C:RaftTypeConfig>`

openraft/src/core/tick.rs, openraft/src/engine/engine_impl.rs, openraft/src/engine/testing.rs, openraft/src/lib.rs, openraft/src/metrics/metric.rs, openraft/src/metrics/raft_metrics.rs, openraft/src/metrics/wait_test.rs, openraft/src/raft/mod.rs, openraft/src/testing/common.rs, openraft/src/testing/log/suite.rs, openraft/src/type_config.rs, openraft/src/vote/leader_id/leader_id_adv.rs, openraft/src/vote/leader_id/leader_id_std.rs, openraft/src/vote/mod.rs, openraft/src/vote/raft_term/mod.rs, openraft/src/vote/raft_term/raft_term_impls.rs, openraft/src/vote/vote.rs
Add associated type `Term: RaftTerm` to `RaftTypeConfig` so that
application can customize the data type for Raft `term`.
By default `Term` is `u64` and user application does not need to modify
to upgrade.
- Part of #1278
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/openraft/1284)
=> Feature: Abstract Term

examples/raft-kv-rocksdb/Cargo.toml, examples/raft-kv-rocksdb/src/store.rs, examples/rocksstore/Cargo.toml, examples/rocksstore/src/lib.rs, examples/rocksstore/src/log_store.rs, examples/rocksstore/src/test.rs, openraft/src/vote/raft_term/mod.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/openraft/1286)
=> Refactor: example raft-kv-rocksdb reuses example/rocksstore

examples/raft-kv-memstore-grpc/src/pb_impl/impl_vote.rs
If we do not add a default, I am getting a runtime panic because leader-id could be None?
```
thread 'main' panicked at src/pb_impl/impl_vote.rs:30:37:
called `Option::unwrap()` on a `None` value
stack backtrace:
```
**Checklist**
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/openraft/1294)
=> Chore: add default for unwrap

cluster_benchmark/tests/benchmark/store.rs, examples/raft-kv-memstore-grpc/src/lib.rs, examples/raft-kv-memstore-grpc/src/store/mod.rs, examples/raft-kv-memstore-network-v2/src/store.rs, examples/raft-kv-memstore-opendal-snapshot-data/src/store.rs, examples/raft-kv-memstore-singlethreaded/src/store.rs, examples/raft-kv-memstore/src/store/mod.rs, examples/raft-kv-rocksdb/src/store.rs, examples/rocksstore/src/lib.rs, openraft/src/core/raft_core.rs, openraft/src/engine/log_id_list.rs, openraft/src/log_id/mod.rs, stores/memstore/src/lib.rs, tests/tests/append_entries/t11_append_inconsistent_log.rs, tests/tests/fixtures/mod.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/openraft/1297)
=> Chore: replace usage of `LogId.leader_id` with `LogId.leader_id()`

openraft/src/core/raft_core.rs, openraft/src/engine/handler/replication_handler/append_membership_test.rs, openraft/src/engine/handler/replication_handler/mod.rs, openraft/src/progress/entry/mod.rs, openraft/src/progress/entry/tests.rs, openraft/src/progress/entry/update.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/openraft/1298)
=> Chore: replace usage of `ProgressEntry::matching` with `ProgressEntry::matching()`

openraft/src/raft/mod.rs
Add missing trait constrain `SM: RaftStateMachine<C>` to
`external_state_machine_request<SM>()`.
- Mentioned in https://github.com/databendlabs/openraft/pull/1206#discussion_r1909951691
Thanks to @SteveLauC
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/openraft/1300)
=> Chore: fix trait constrain for `external_state_machine_request<SM>()`

openraft/src/core/sm/worker.rs, openraft/src/engine/engine_impl.rs, openraft/src/engine/handler/following_handler/mod.rs, openraft/src/engine/handler/leader_handler/mod.rs, openraft/src/entry/mod.rs, openraft/src/entry/payload.rs, openraft/src/entry/traits.rs, openraft/src/storage/helper.rs
Reason for the change:
Log entries may use different data types to store a membership config,
and it might not always be possible for an application to return a
reference to an `openraft::Membership`. For instance, a log entry
implementation might store a membership config in a serialized format
internally.
To address this, `RaftPayload::get_membership()` has been updated to
return an owned instance of `Membership`. This allows the implementation
to construct a `Membership` instance on demand when the method is
called.
Performance considerations:
Membership configurations in log entries are rare in most real-world
applications. As a result, this change is unlikely to have any
measurable performance impact.
Upgrade tip:
To adapt to this change, modify your implementation of …
=> Change: `RaftPayload::get_membership()` now returns an owned `Membership`

macros/src/since.rs, macros/tests/since/expand/multi_since.expanded.rs, macros/tests/since/expand/multi_since.rs, macros/tests/since/expand/with_change.expanded.rs, macros/tests/since/expand/with_change.rs, macros/tests/since/expand/with_date_change.expanded.rs, macros/tests/since/expand/with_date_change.rs, macros/tests/since/expand/with_date_many_change.expanded.rs, macros/tests/since/expand/with_date_many_change.rs
This commit introduces the ability to include changelogs directly in the
`#[since()]` macro. For example:
```rust
#[since(version = "0.1.0", change = "add new argument `a: u64`", change = "add T")]
```
Generates the following documentation line:
```rust
/// Since: 0.1.0: add new argument `a: u64`; add T
```
Key updates:
- Multiple `change` attributes are supported within the same `#[since()]` macro.
- Changelogs are concatenated into a single documentation line.
This enhancement makes it easier to document changes alongside version annotations.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/openraft/1309)
=> Feature: Add changelog support in the `#[since()]` macro

cluster_benchmark/tests/benchmark/store.rs, examples/raft-kv-memstore-grpc/src/lib.rs, examples/raft-kv-memstore-grpc/src/store/mod.rs, examples/raft-kv-memstore-network-v2/src/store.rs, examples/raft-kv-memstore-opendal-snapshot-data/src/store.rs, examples/raft-kv-memstore-singlethreaded/src/store.rs, examples/raft-kv-memstore/src/store/mod.rs, examples/raft-kv-rocksdb/src/store.rs, examples/rocksstore/src/lib.rs, openraft/src/engine/log_id_list.rs, openraft/src/log_id/mod.rs, openraft/src/storage/helper.rs, stores/memstore/src/lib.rs, tests/tests/append_entries/t11_append_inconsistent_log.rs, tests/tests/fixtures/mod.rs
The method `LogId::leader_id()` returns a `&CommittedLeaderId` instead
of a `LeaderId`, which can be misleading.
This commit deprecates `leader_id()` and recommends using the more
descriptive `LogId::committed_leader_id()` method instead.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/openraft/1312)
=> Refactor: Deprecate `LogId::leader_id()`

cluster_benchmark/tests/benchmark/store.rs, examples/memstore/src/log_store.rs, examples/rocksstore/src/lib.rs, examples/rocksstore/src/log_store.rs, openraft/src/base/finalized.rs, openraft/src/base/mod.rs, openraft/src/core/sm/worker.rs, openraft/src/engine/handler/following_handler/mod.rs, openraft/src/engine/handler/leader_handler/mod.rs, openraft/src/entry/traits.rs, openraft/src/proposer/leader.rs, openraft/src/replication/mod.rs, openraft/src/storage/helper.rs, openraft/src/storage/log_reader_ext.rs, openraft/src/storage/v2/raft_log_storage_ext.rs, openraft/src/testing/log/suite.rs, stores/memstore/src/lib.rs, tests/tests/fixtures/mod.rs
This commit adds two auto-implemented method to `RaftEntry`
implementation:
- `RaftEntry::log_id()` returns an owned `LogId<C>` instance.
- `RaftEntry::index()` returns the log index of this entry.
And populate these two method to the codebase for simplicity.
`Final` is a marker trait used to prevent specific already
auto-implemented trait methods from being re-implemented outside their
defining crate.
For example, the following code demonstrates how `Final` prevents
external implementation:
```rust
pub trait Trait {
// This method cannot be implemented by users because it requires
// the private `Final` trait in its bounds
fn unimplementable(&self) where Self: Final {
self.user_impl_this();
}
// This method can be implemented by users
fn user_impl_this(&self);
}
pub struct MyType;
impl …
```
=> Feature: New `RaftEntry` methods: `log_id()` and `index()`

openraft/src/entry/mod.rs, openraft/src/entry/payload.rs, openraft/src/entry/traits.rs
OpenRaft does not need to know whether a log entry is blank or not.
Upgrade tip:
Remove implementation of `RaftPayload::is_blank()`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/openraft/1316)
=> Change: remove unused RaftPayload::is_blank()

examples/raft-kv-memstore-singlethreaded/src/store.rs, openraft/src/raft_state/tests/log_state_reader_test.rs, openraft/src/replication/mod.rs, openraft/src/testing/common.rs, openraft/src/testing/log/suite.rs, stores/memstore/src/lib.rs, tests/tests/snapshot_streaming/t30_purge_in_snapshot_logs.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/openraft/1317)
=> Chore: adjust code format

openraft/src/raft_state/tests/forward_to_leader_test.rs, openraft/src/testing/log/suite.rs
Because it use type config `UTConfig<u64>` instead of the default `UTConfig`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/openraft/1318)
=> Chore adjust code format

examples/raft-kv-memstore/src/app.rs, examples/raft-kv-memstore/src/client.rs, examples/raft-kv-memstore/src/lib.rs, examples/raft-kv-memstore/src/network/api.rs, examples/raft-kv-memstore/tests/cluster/test_cluster.rs, examples/raft-kv-rocksdb/src/client.rs, examples/raft-kv-rocksdb/src/network/api.rs, examples/raft-kv-rocksdb/tests/cluster/test_cluster.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/openraft/1323)
=> Chore: rename consistent_read() to linearizable_read() for examples

openraft/src/error/decompose.rs, openraft/src/error/streaming_error.rs, openraft/src/network/snapshot_transport.rs, openraft/src/network/v2/adapt_v1.rs
`StreamingError` is intended to represent non-logic errors that occur
while streaming data to a remote peer. A `RemoteError` does not belong
in a stream RPC error and should instead be included as part of a
non-error response.
Upgrade tip:
No modifications are required for this change, as no related API
utilized the `RemoteError` variant.
The return error type of
`openraft::network::snapshot_transport::Chunked::send_snapshot()` is
simplified from `StreamingError<_, Fatal>` to `StreamingError<_>`. This
change is made because the remote `Fatal` error cannot be handled by the
sending end and should not be produced at all.
Upgrade Tip:
If `Chunked` is used in a `RaftNetworkV2` implementation to adapt the v1
`RaftNetwork`, simply remove the error handling for `Fatal`. Otherwise,
no changes are …
=> Change: Remove `RemoteError` variant from `StreamingError`

openraft/src/docs/data/mod.rs, openraft/src/docs/data/replication-session.md, openraft/src/replication/replication_session_id.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/openraft/1326)
=> Doc: explain ReplicationSessionId in detail

cluster_benchmark/tests/benchmark/store.rs, examples/raft-kv-memstore-grpc/src/grpc/raft_service.rs, examples/raft-kv-memstore-grpc/src/network/mod.rs, examples/raft-kv-memstore-grpc/src/store/mod.rs, examples/raft-kv-memstore-network-v2/src/api.rs, examples/raft-kv-memstore-network-v2/src/store.rs, examples/raft-kv-memstore-opendal-snapshot-data/src/api.rs, examples/raft-kv-memstore-opendal-snapshot-data/src/store.rs, examples/raft-kv-memstore-singlethreaded/src/store.rs, examples/raft-kv-memstore/src/store/mod.rs, examples/raft-kv-rocksdb/src/store.rs, examples/rocksstore/src/lib.rs, openraft/src/core/raft_msg/mod.rs, openraft/src/core/sm/command.rs, openraft/src/engine/engine_impl.rs, openraft/src/engine/handler/following_handler/install_snapshot_test.rs, openraft/src/engine/tests/install_full_snapshot_test.rs, openraft/src/network/snapshot_transport.rs, openraft/src/raft/mod.rs, openraft/src/storage/snapshot.rs, openraft/src/storage/v2/raft_state_machine.rs, openraft/src/testing/log/suite.rs, stores/memstore/src/lib.rs, tests/tests/client_api/t16_with_state_machine.rs, tests/tests/snapshot_streaming/t10_api_install_snapshot_with_lower_vote.rs
Currently, `Snapshot` is defined as:
```
struct Snapshot<C> {
pub meta: SnapshotMeta<C>,
pub snapshot: Box<C::SnapshotData>,
}
```
The `Box` wrapping `snapshot` should be removed because:
1. Memory management of large `SnapshotData` should be handled by the
application.
2. If needed, applications can still implement `C::SnapshotData` using
`Box` or other pointer types.
3. OpenRaft should not make assumptions about the size of `SnapshotData`.
This commit change `Snapshot` to:
```rust
struct Snapshot<C> {
pub meta: SnapshotMeta<C>,
pub snapshot: C::SnapshotData,
}
```
By removing the `Box`, it also saves troubles converting the `inner` to
`Box` and vice versa.
- Fix: #1322
Upgrade tip:
Remove `Box<>` when using `Snapshot::snapshot`.
- - - …
=> Change: Remove Box from `Snapshot::snapshot`

examples/raft-kv-memstore-grpc/src/pb_impl/impl_vote.rs, openraft/src/storage/snapshot_meta.rs, openraft/src/storage/snapshot_signature.rs, openraft/src/storage_error.rs
This commit addressed an issue of implementing trait for associated
types, by replacing implementation for associated type with concrete
type `pb::Vote`.
- Related issues: https://github.com/rust-lang/rust/issues/51445
- The minimized reproduce repo is:
https://github.com/drmingdrmer/conflict-trait-in-main
Explanation:
If one crate `lib.rs` implements a trait(`Default`) for an associated
type(`<() as Container>::Item`, which is `Foo`), in another crate
`main.rs`, it seems the compiler treats the associated type(`<() as
Container>::Item`) as a generic type `T` and assumes `T` would
be any type and results in the conflict with a local type that tries to
implement `Default`, while actually `Foo` and `Wow` are actually
different types.
```
▾ src/
lib.rs
main.rs
```
`lib.rs`:
```rust
pub trait …
```
=> Refactor: Fix: impl XX for associated type conflict in another crate

tests/tests/client_api/t11_client_reads.rs
This ensures the `last-applied` log id is updated.
Since `last-applied` may not be updated when the client-write response
is received, the following `get_read_log_id()` may return a stale
`last-applied` value.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/openraft/1338)
=> Test: Wait until `last-applied` is updated before proceeding with the following read-log-id test

openraft/src/core/raft_core.rs, openraft/src/core/sm/command.rs, openraft/src/engine/handler/following_handler/commit_entries_test.rs, openraft/src/engine/handler/following_handler/install_snapshot_test.rs, openraft/src/engine/handler/following_handler/mod.rs, openraft/src/engine/handler/leader_handler/append_entries_test.rs, openraft/src/engine/handler/leader_handler/get_read_log_id_test.rs, openraft/src/engine/handler/leader_handler/mod.rs, openraft/src/engine/handler/leader_handler/send_heartbeat_test.rs, openraft/src/engine/handler/replication_handler/update_matching_test.rs, openraft/src/engine/tests/append_entries_test.rs, openraft/src/engine/tests/install_full_snapshot_test.rs, openraft/src/raft_state/io_state.rs, openraft/src/raft_state/io_state/io_progress.rs, openraft/src/raft_state/mod.rs, openraft/src/raft_state/tests/log_state_reader_test.rs, openraft/src/raft_state/tests/validate_test.rs, openraft/src/storage/helper.rs, openraft/src/testing/log/suite.rs, tests/tests/client_api/t16_with_raft_state.rs
This commit updates `RaftState` to track the committed and applied log
IDs using `io_state.apply_progress`, which is now an
`IOProgress<LogId>`. This approach aligns the apply progress tracking
with the log I/O progress mechanism.
- `apply_progress.accepted()`: Represents the committed log ID (the log
ID accepted for applying).
- `apply_progress.submitted()`: Represents the log ID that has been
submitted to the state machine for application, or the last log ID of
a snapshot being installed.
- `apply_progress.flushed()`: Represents the log ID that has already
been applied to the state machine.
- Refactor: rename `io_progress` to `log_progress` to distinguish it
from the `apply_progress`.
Upgrade tip:
Replace usages of the `RaftState.committed` field with the `RaftState::committed()` …
=> Change: Track commit and apply progress with `io_state.apply_progress`

.github/workflows/coverage.yml, tests/tests/client_api/t11_client_reads.rs
- Improvement
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/openraft/1344)
=> ci: use llvm-cov to report test coverage

openraft/src/membership/into_nodes.rs
EmptyNode can be created directly thus a BTreeSet can be used to build a
nodes map
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/openraft/1346)
=> feat: Add impl `IntoNodes<NID, EmptyNode>` for `BTreeSet<NID>`

openraft/src/vote/leader_id/raft_committed_leader_id.rs, openraft/src/vote/leader_id/raft_leader_id.rs
`RaftCommittedLeaderId` does not need a `RaftTypeConfig` parameter.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/openraft/1347)
=> Change: Remove type parameter from `RaftCommittedLeaderId`(added in 0.10)

openraft/src/change_members.rs, openraft/src/core/sm/worker.rs, openraft/src/membership/membership.rs, openraft/src/membership/membership_test.rs
This commit introduces the `ChangeMembers::Batch(Vec<ChangeMembers>)`
variant, allowing `Raft::change_membership()` to accept an arbitrary
series of membership configuration changes as a single input command.
This enables users to define complex membership changes by combining
multiple `ChangeMembers` operations.
The following example demonstrates removing nodes 1 and 2, and adding
node 3 in a two-step joint membership configuration change:
```rust
my_raft.change_membership(ChangeMembers::Batch(vec![
ChangeMembers::RemoveVoters(btreeset! {1, 2}),
ChangeMembers::AddVoters(btreemap! {3 => ()}),
]));
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/openraft/1349)
=> feat: add `ChangeMembers::Batch(Vec<ChangeMembers>)` for batched membership changes

openraft/src/engine/time_state.rs, openraft/src/proposer/leader.rs
Improve documentation explaining two critical timing mechanisms:
- `leader_lease`: Defines the period during which a follower will not
initiate an election, preventing unnecessary leadership challenges
- `clock_progress`: Tracks the latest timestamp when a heartbeat sending
time was acknowledged by a quorum of nodes, allowing the leader to
maintain its authority
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/openraft/1363)
=> docs: clarify `leader_lease` and `clock_progress` mechanisms

.gitignore, examples/raft-kv-memstore-network-v2/src/api.rs, examples/raft-kv-memstore-opendal-snapshot-data/src/api.rs, examples/raft-kv-memstore-singlethreaded/src/api.rs, examples/raft-kv-memstore/src/network/api.rs, examples/raft-kv-rocksdb/src/network/api.rs, openraft/src/core/raft_core.rs, openraft/src/core/raft_msg/mod.rs, openraft/src/docs/protocol/read.md, openraft/src/lib.rs, openraft/src/raft/mod.rs, tests/tests/client_api/t11_client_reads.rs, tests/tests/fixtures/mod.rs, tests/tests/membership/t10_single_node.rs
**Checklist**
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/openraft/1362)
=> feat: introduction to LeaseRead

.github/workflows/ci.yaml, Cargo.toml, openraft/src/instant.rs, rt-compio/Cargo.toml, rt-compio/README.md, rt-compio/src/lib.rs, rt-compio/src/mpsc.rs, rt-compio/src/mpsc_unbounded.rs, rt-compio/src/mutex.rs, rt-compio/src/oneshot.rs, rt-compio/src/watch.rs
- **feat: add compio support**
- **feat: add unit test**
**Checklist**
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/openraft/1364)
=> feat: add support for compio runtime

examples/raft-kv-memstore/README.md, examples/raft-kv-memstore/src/client.rs, examples/raft-kv-memstore/src/network/api.rs, examples/raft-kv-memstore/src/network/management.rs, examples/raft-kv-memstore/tests/cluster/test_cluster.rs, openraft/src/core/raft_core.rs, openraft/src/core/raft_msg/external_command.rs, openraft/src/core/raft_msg/mod.rs, openraft/src/core/sm/command.rs, openraft/src/core/sm/handle.rs, openraft/src/core/sm/worker.rs, openraft/src/engine/command.rs, openraft/src/engine/engine_impl.rs, openraft/src/engine/handler/vote_handler/accept_vote_test.rs, openraft/src/engine/handler/vote_handler/mod.rs, openraft/src/engine/tests/install_full_snapshot_test.rs, openraft/src/error.rs, openraft/src/error/into_raft_result.rs, openraft/src/network/snapshot_transport.rs, openraft/src/raft/api/app.rs, openraft/src/raft/api/management.rs, openraft/src/raft/api/mod.rs, openraft/src/raft/api/protocol.rs, openraft/src/raft/impl_raft_blocking_write.rs, openraft/src/raft/mod.rs, openraft/src/raft/raft_inner.rs, openraft/src/raft/trigger.rs
For development concerns, we've separated the API interface from its implementation.
During this refactoring, we maintained backward compatibility - the user-facing API
remains unchanged. We kept the Raft struct as an API layer providing consistent methods,
while moving all implementation details into several other structures. These implementation
structures focus solely on core functionality, with the Raft API methods calling them and
handling any necessary type conversions. This separation creates a clearer view of the
implementation with a one-way contract, ensuring the user API remains stable and unaffected.
- Improvement
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/ …
=> refactor: separate Raft API and impl

openraft/src/core/raft_core.rs, openraft/src/core/raft_msg/mod.rs, openraft/src/core/sm/command.rs, openraft/src/core/sm/worker.rs, openraft/src/engine/engine_impl.rs, openraft/src/raft/api/app.rs, openraft/src/raft/api/management.rs, openraft/src/raft/impl_raft_blocking_write.rs, openraft/src/raft/responder/either.rs, openraft/src/raft/responder/mod.rs
Before this commit, calling `change_membership()` required the
`RaftTypeConfig::Responder` to be configured with `OneshotResponder`.
This unnecessarily limited applications from using alternative
`Responder` types.
In this commit, we've removed this restriction from the
`change_membership()` method, allowing applications to use any responder
type they prefer. Internally, we now store different types of responders
for `change_membership()` and `client_write()` operations in an enum.
- Improvement
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/openraft/1368)
=> refactor: no more `C::Responder = OneshotResponder` for `change_membership()`

openraft/src/core/raft_core.rs, openraft/src/core/raft_msg/mod.rs, openraft/src/engine/handler/leader_handler/get_read_log_id_test.rs, openraft/src/engine/handler/leader_handler/mod.rs, openraft/src/engine/handler/vote_handler/become_leader_test.rs, openraft/src/engine/handler/vote_handler/mod.rs, openraft/src/engine/tests/handle_vote_resp_test.rs, openraft/src/engine/tests/startup_test.rs, openraft/src/proposer/leader.rs, openraft/src/raft/api/app.rs, openraft/src/raft/linearizable_read/linearize_state.rs, openraft/src/raft/linearizable_read/linearizer.rs, openraft/src/raft/linearizable_read/mod.rs, openraft/src/raft/mod.rs
Add new API `Raft::get_read_linearizer()` to implement linearizable
reads. It provides a clearer API and gives users intuitive guidance
on how to perform local linearizable reads or follower reads, i.e.,
get `read_log_id` from a remote leader but read the local state machine.
`Raft::get_read_linearizer()` ensures leadership and returns a
`Linearizer` instance containing `read_log_id` and the last `applied`
log ID in the state machine. The caller, either on the local node or on
a remote follower, calls `Linearizer::await_applied()` to block until
the state machine applies up to `read_log_id` to assert linearizability.
A typical usage of follower read:
```rust,ignore
// Application defined RPC to get the `read_log_id` from the remote leader
let leader_id = …
```
=> feat: add `Raft::get_read_linearizer()`

openraft/src/node.rs
`NodeId` does not require `Copy` in release 0.10 . But the auto `NodeId`
trait implementation still require `T` to be `Copy`, i.e.:
`impl NodeId for T where T: Copy + ..`.
This `Copy` trait bound should be removed according to the `NodeId`
trait definition change.
- Fix: ##1382
Thanks to @tvsfx !
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/openraft/1383)
=> Fix: in 0.10, auto `NodeId` impl should not include `Copy`

openraft/src/core/raft_core.rs, openraft/src/engine/engine_impl.rs, tests/tests/fixtures/mod.rs
When a leader restarted and its log reverted, and tried to re-elect
itself as leader:
And when vote request is rejected and see a greater vote,
it should only update to the non-committed version of the responded vote
to its local state:
This prevents a dangerous scenario when state reversion is allowed:
1. A node was a leader but its state reverted to a previous version;
2. The node restarts and begins election;
3. It receives a vote response containing its own previous leader vote;
4. Without this protection, it would update to that committed vote and
become leader again;
5. However, it lacks the necessary logs, causing committed entries to be
lost or inconsistent;
By using the non-committed version, we prevent this reverted node from
becoming leader while still allowing proper vote …
=> refactor: tolerate leader state reversion upon restart

tests/tests/life_cycle/t50_leader_restart_clears_state.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/openraft/1387)
=> fixup: initializing already trigger elect automatically in leader_restart_clears_state

.github/workflows/ci.yaml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/openraft/1396)
=> CI: add API key to increase rate limit of installing protoc

openraft/src/docs/faq/faq-toc.md, openraft/src/docs/faq/faq.md
Covers two detection methods:
- Monitoring replication lag via RaftMetrics::replication
- Monitoring heartbeat timestamps via RaftMetrics::heartbeat
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/openraft/1400)
=> docs: add FAQ entry for detecting unreachable nodes

openraft/src/error.rs, openraft/src/error/into_ok.rs, openraft/src/error/streaming_error.rs, rt-monoio/src/lib.rs
uninhabited types should be dealt with at compile time, not through the runtime panic that `unreachable!` throws
since rust 1.82, Rust has better ergonomics for matching on uninhabited enum variants, which makes this easier for owned types (https://github.com/rust-lang/rust/pull/122792)
**Checklist**
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/openraft/1401)
=> fix: match on uninhabited types at compile time

openraft/src/docs/docs.md, openraft/src/docs/protocol/io_ordering.md, openraft/src/docs/protocol/mod.rs
Re-ordering IO to persisting Vote and persisting Log Entries are
disallowed. This doc gives an example of data loss when re-order is
enabled.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/openraft/1410)
=> docs: Explain io re-order about vote and log

Makefile, openraft/src/config/config.rs, openraft/src/core/core_state.rs, openraft/src/core/mod.rs, openraft/src/core/raft_core.rs, openraft/src/core/sm/response.rs, openraft/src/core/sm/worker.rs, openraft/src/engine/engine_impl.rs, openraft/src/raft/mod.rs, openraft/src/storage/helper.rs, openraft/src/storage/v2/raft_state_machine.rs, openraft/src/testing/log/suite.rs, stores/memstore/src/lib.rs, tests/tests/snapshot_building/main.rs, tests/tests/snapshot_building/t11_snapshot_builder_control.rs
Add `try_create_snapshot_builder(force: bool) -> Option<Builder>` to
allow applications to defer snapshot creation when OpenRaft requests it.
This enables implementations to choose optimal timing for snapshot
building based on I/O load and other factors.
When `force=false`, returning `None` defers the snapshot creation.
When `force=true`, a builder must be returned.
The default implementation calls `get_snapshot_builder()` for backward
compatibility. `get_snapshot_builder` is marked for deprecation.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/openraft/1412)
=> feat: add `RaftStateMachine::try_create_snapshot_builder`
