.github/workflows/issue-cmds.yml
.github/workflows/issue-welcome.yml
.mergify.yml

ci: replace comment command actions with simpler ones

---

async-raft/src/docs/mod.rs
fixes.md
guide/src/SUMMARY.md

doc: update docs: list of fixed bug by openraft that are found in async-raft

---

CHANGELOG.md

doc: change-log: 0.6.2-alpha.5

---

async-raft/tests/total_order_apply.rs

test of out-of-order apply

---

guide/src/SUMMARY.md
guide/src/threading.md

---
- Documentation
---
- fix: #41

doc: explain threads(tasks) that are used in openraft

---

openraft/tests/add_remove_voter.rs
openraft/tests/api_install_snapshot.rs
openraft/tests/client_reads.rs
openraft/tests/client_writes.rs
openraft/tests/concurrent_write_and_add_non_voter.rs
openraft/tests/current_leader.rs
openraft/tests/fixtures/mod.rs
openraft/tests/initialization.rs
openraft/tests/lagging_network_write.rs
openraft/tests/leader_metrics.rs
openraft/tests/membership/t00_learner_restart.rs
openraft/tests/membership/t25_elect_with_new_config.rs
openraft/tests/membership/t30_commit_joint_config.rs
openraft/tests/membership/t99_new_leader_auto_commit_uniform_config.rs
openraft/tests/metrics_state_machine_consistency.rs
openraft/tests/shutdown.rs
openraft/tests/singlenode.rs
openraft/tests/snapshot_chunk_size.rs
openraft/tests/snapshot_ge_half_threshold.rs
openraft/tests/snapshot_overrides_membership.rs
openraft/tests/snapshot_uses_prev_snap_membership.rs
openraft/tests/state_machien_apply_membership.rs
openraft/tests/stepdown.rs

test: refine var name: n_logs for N.O. logs

---

openraft/tests/add_remove_voter.rs
openraft/tests/fixtures/mod.rs

refactor: simplify test: add_remove_voter

---

openraft/tests/membership/main.rs
openraft/tests/membership/t15_add_remove_follower.rs

test: move test add_remove_voter into tests/membershp

---

openraft/tests/snapshot/main.rs
openraft/tests/snapshot/snapshot_chunk_size.rs
openraft/tests/snapshot/snapshot_ge_half_threshold.rs
openraft/tests/snapshot/snapshot_line_rate_to_snapshot.rs
openraft/tests/snapshot/snapshot_overrides_membership.rs
openraft/tests/snapshot/snapshot_uses_prev_snap_membership.rs

refactor:move snapshot related test into test/snapshot dir

refactor:move snapshot related test into test/snapshot dir

---

CONTRIBUTING.md

doc: CONTRIBUTING.md: add git guide

---

.github/workflows/commit-message-check.yml

CI: add git commit message check

---

openraft/tests/append_entries/main.rs
openraft/tests/append_entries/t10_conflict_with_empty_entries.rs
openraft/tests/append_entries/t20_append_conflicts.rs
openraft/tests/append_entries/t30_append_inconsistent_log.rs
openraft/tests/append_entries/t40_append_updates_membership.rs

Refactor: put append-entries tests into tests/append_entries

---

openraft/tests/log-compaction/compaction.rs
openraft/tests/log-compaction/main.rs

Refactor: put integration test related to log-compaction into folder tests/log-compaction

Refactor: put integration test related to log-compaction into folder tests/log-compaction

---

.github/workflows/ci.yaml
.mergify.yml
CONTRIBUTING.md
Makefile
memstore/src/lib.rs
memstore/src/test.rs
openraft/src/core/mod.rs
openraft/tests/snapshot/main.rs

CI: PR has to pass fmt check to merge

---

openraft/tests/metrics/main.rs
openraft/tests/metrics/t10_current_leader.rs
openraft/tests/metrics/t20_metrics_state_machine_consistency.rs
openraft/tests/metrics/t30_leader_metrics.rs
openraft/tests/metrics/t40_metrics_wait.rs

Refactor: move metrics tests into tests/metrics

---

openraft/src/config.rs
openraft/src/config_test.rs
openraft/src/error.rs

Refactor: ConfigError should provide more info about the wrong config

---

Makefile

CI: "make" run unittest with defensive check too

---

openraft/src/config/config.rs
openraft/src/config/config_test.rs
openraft/src/config/error.rs
openraft/src/config/mod.rs
openraft/src/core/client.rs
openraft/src/error.rs
openraft/src/lib.rs

Refactor: move config and config errors into sub mod "config"

---

openraft/src/membership/membership.rs
openraft/src/membership/membership_test.rs

Feature: Membership::next_safe() returns next safe membership to change to

---

openraft/src/core/client.rs
openraft/src/core/mod.rs
openraft/src/error.rs
openraft/src/raft.rs

Refactor: replace quorum check with Membership methods

---

memstore/src/lib.rs
memstore/src/test.rs
openraft/src/defensive.rs
openraft/src/storage.rs
openraft/src/store_ext.rs

Feature: add default impl for RaftStorage::get_log_entries and try_get_log_entry

---

memstore/src/lib.rs
memstore/src/test.rs
openraft/src/storage.rs
openraft/tests/elect_compare_last_log.rs
openraft/tests/fixtures/mod.rs
openraft/tests/log_compaction/compaction.rs

Refactor: remove unused codes in memstore

---

memstore/src/lib.rs
openraft/src/defensive.rs
openraft/src/storage.rs
openraft/src/store_ext.rs

Refactor: rename RNG to RB for RnageBound

---

openraft/src/storage.rs
openraft/tests/append_entries/main.rs
openraft/tests/append_entries/t40_append_updates_membership.rs
openraft/tests/append_entries/t60_large_heartbeat.rs

---
- This is a  supplementary test to #53
- Fix: #56

Test: large_heartbeat should not affect replication

---

openraft/Cargo.toml
openraft/src/config/config.rs

Signed-off-by: Chojan Shang <psiace@outlook.com>
Refactor: use clap to impl config default values

Refactor: use clap to impl config default values

---

memstore/src/lib.rs
openraft/src/core/append_entries.rs
openraft/src/core/mod.rs
openraft/src/storage.rs
openraft/src/store_ext.rs
openraft/src/testing/suite.rs

Change: rename RaftStorage methods do_log_compaction: build_snapshot, delete_logs_from: delete_log

---

guide/src/getting-started.md

Doc: refine methods syntax in guides/getting-started

---

openraft/src/core/admin.rs
openraft/src/error.rs
openraft/tests/membership/t20_change_membership.rs

Change: add ChangeMembershipError sub error for reuse

---

memstore/src/lib.rs
openraft/src/core/install_snapshot.rs
openraft/src/raft_types.rs

Refactor: StateMachineChanges.last_applied does not need to be an Option

---

openraft/src/core/replication.rs
openraft/src/error.rs
openraft/src/replication/mod.rs
openraft/tests/snapshot/after_snapshot_add_learner_and_request_a_log.rs
openraft/tests/snapshot/main.rs

Fix: when lack entry, the snapshot has to include the lacking entries

---

openraft/tests/snapshot/after_snapshot_add_learner_and_request_a_log.rs

Fix: fix send_append_entries bug

Fix: fix send_append_entries bug, add unit test

---

openraft/tests/client_api/main.rs
openraft/tests/membership/main.rs
openraft/tests/membership/t30_step_down.rs

Test: move step_down() test from client_api/ to membership/; simplify it slightly

---

guide/src/dynamic-membership.md

Doc: explain extended membership change algo, add proof of correctness

---

openraft/src/core/admin.rs
openraft/src/core/client.rs
openraft/src/core/mod.rs
openraft/src/core/replication.rs
openraft/src/core/vote.rs
openraft/src/membership/membership.rs
openraft/src/membership/membership_test.rs

Refactor: pick changes from #129 rename Membership::all_nodes() to all_members()

---

openraft/src/raft.rs
openraft/src/raft_types.rs

Refactor: make AppendEntriesRequest::summary() shorter

---

memstore/Cargo.toml
memstore/src/test.rs
openraft/Cargo.toml
openraft/src/config/config.rs
openraft/src/config/error.rs
openraft/src/error.rs
openraft/src/raft.rs
openraft/src/testing/suite.rs
openraft/tests/fixtures/mod.rs

Change: add ConfigError sub error; remove anyhow

---

guide/src/getting-started.md

Doc: update guide/getting-started.md use example-raft-kv to explain how to use openraft

---

openraft/Cargo.toml
openraft/tests/client_api/t50_lagging_network_write.rs
openraft/tests/concurrent_write_and_add_learner.rs
openraft/tests/fixtures/mod.rs
openraft/tests/initialization.rs
openraft/tests/log_compaction/compaction.rs
openraft/tests/membership/t10_add_learner.rs
openraft/tests/membership/t15_add_remove_follower.rs
openraft/tests/membership/t16_change_membership_cases.rs
openraft/tests/membership/t20_change_membership.rs
openraft/tests/membership/t25_elect_with_new_config.rs
openraft/tests/membership/t30_commit_joint_config.rs
openraft/tests/membership/t30_step_down.rs
openraft/tests/membership/t40_removed_follower.rs
openraft/tests/membership/t99_new_leader_auto_commit_uniform_config.rs
openraft/tests/metrics/t20_metrics_state_machine_consistency.rs
openraft/tests/metrics/t30_leader_metrics.rs
openraft/tests/snapshot/snapshot_overrides_membership.rs
openraft/tests/snapshot/snapshot_uses_prev_snap_membership.rs
openraft/tests/state_machine/t10_total_order_apply.rs
openraft/tests/state_machine/t20_state_machine_apply_membership.rs
openraft/tests/state_machine/t40_clean_applied_logs.rs

- fixtures: change some async method to sync.
- Remove some redundant testing method.
---

Refactor: add get_raft_handle() to fixtures::RaftRouter.

---

.github/workflows/ci.yaml
example-raft-kv/src/network/management.rs
example-raft-kv/src/network/node_manager.rs
example-raft-kv/tests/cluster/test_cluster.rs

CI: test example-raft-kv

---

.github/workflows/pages.yaml
book.toml
guide/src/architecture.md
guide/src/custom.css

Doc: guide/: render diagram into svg

---

.github/workflows/ci.yaml
.github/workflows/release-memstore.yaml
.github/workflows/release-raft.yaml
rust-toolchain.toml

CI: remove rust-toolchain.toml

---

openraft/tests/benchmark/bench_cluster.rs
openraft/tests/benchmark/main.rs
openraft/tests/fixtures/mod.rs

---
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/196)

Test: add ignored benchmark on a cluster of 3 nodes

---

example-raft-kv/src/bin/main.rs
example-raft-kv/src/client.rs
example-raft-kv/src/lib.rs
example-raft-kv/src/network/raft.rs
example-raft-kv/src/network/raft_network_impl.rs
example-raft-kv/src/store/mod.rs
memstore/src/lib.rs
openraft/src/core/admin.rs
openraft/src/core/append_entries.rs
openraft/src/core/client.rs
openraft/src/core/install_snapshot.rs
openraft/src/core/mod.rs
openraft/src/core/replication.rs
openraft/src/core/vote.rs
openraft/src/defensive.rs
openraft/src/lib.rs
openraft/src/network.rs
openraft/src/raft.rs
openraft/src/replication/mod.rs
openraft/src/storage.rs
openraft/src/store_ext.rs
openraft/src/store_wrapper.rs
openraft/src/testing/store_builder.rs
openraft/src/testing/suite.rs
openraft/tests/append_entries/t20_append_conflicts.rs
openraft/tests/fixtures/mod.rs

This is a follow-up to https://github.com/datafuselabs/openraft/pull/211.
It completes https://github.com/datafuselabs/openraft/issues/204.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/212)

Fix: Update `RaftConfig` to `RaftTypeConfig`

---

openraft/src/core/append_entries.rs
openraft/src/core/client.rs
openraft/src/raft.rs
openraft/src/replication/mod.rs
openraft/tests/append_entries/t10_conflict_with_empty_entries.rs
openraft/tests/append_entries/t20_append_conflicts.rs
openraft/tests/append_entries/t40_append_updates_membership.rs
openraft/tests/append_entries/t50_append_entries_with_bigger_term.rs
openraft/tests/log_compaction/compaction.rs

It completes #197.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/219)

Refactor: make AppendEntriesResponse be an enum

---

openraft/src/raft.rs

---
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/263)

Refactor: simplify `derive` for entry related data types

---

openraft/src/core/admin.rs
openraft/src/core/mod.rs
openraft/src/core/replication.rs

---
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/271)

Refactor: remove set_replication_metrics_changed()

---

openraft/src/core/mod.rs
openraft/src/storage.rs
openraft/src/testing/suite.rs

---
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/272)

Change: InitialState: from `last_membership: EffectiveMembership` to effective_membership: Arc<EffectiveMemebership>`

---

openraft/src/entry.rs

When openraft needs to use entry but does not really consume the
payload, use EntryRef instead of Entry if possible.
---
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/281)

Feature: add EntryRef for internal usage

---

openraft/src/core/mod.rs

---
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/288)

Refactor:  use const to replace literal string

---

openraft/src/core/admin.rs
openraft/tests/initialize/main.rs
openraft/tests/initialize/t20_initialization.rs

---
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/290)

Test: add initialize test with invalid input

---

openraft/src/core/admin.rs
openraft/src/engine.rs

Move input config checking into Engine.
Minor refactor for Engine: move common codes to a standalone method.
- part of #292 
---
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/294)

Refactor: impl initialize() in Engine

---

openraft/src/core/admin.rs
openraft/src/core/candidate_state.rs
openraft/src/core/follower_state.rs
openraft/src/core/leader_state.rs
openraft/src/core/learner_state.rs
openraft/src/core/mod.rs

Refactor: move {Leader|Follower|Candidate|Learner}State to {leader|follower|candidate|learner}_state.rs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/302)

Refactor: move *State to *_state.rs

---

openraft/src/core/admin.rs
openraft/src/core/raft_core.rs
openraft/src/engine/elect_test.rs
openraft/src/engine/engine.rs
openraft/src/engine/handle_vote_req_test.rs
openraft/src/engine/handle_vote_resp_test.rs
openraft/src/engine/initialize_test.rs

---
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/322)

Refactor: when pushing command, update the metrics flags

---

openraft/src/engine/command.rs
openraft/src/engine/engine.rs
openraft/src/engine/mod.rs

---
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/325)

Refactor: move engine::Command to standalone file

---

openraft/src/engine/log_id_list.rs
openraft/src/engine/log_id_list_test.rs

---
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/326)

Feature: LogIdList: add method purge() to delete log ids

---

openraft/src/core/raft_core.rs
openraft/src/engine/command.rs
openraft/src/engine/engine.rs
openraft/src/engine/mod.rs
openraft/src/engine/purge_log_test.rs

---
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/327)

Feature: Engine: add method: purge_log()

---

openraft/src/core/append_entries.rs
openraft/src/core/client.rs
openraft/src/core/raft_core.rs

---
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/329)

Refactor: applyt_to_statemachien() updates last_applied

---

.github/workflows/ci.yaml
Makefile
README.md

---
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/341)

CI: check doc building

---

example-raft-kv/Cargo.toml
memstore/Cargo.toml
openraft/Cargo.toml
openraft/src/config/config.rs
openraft/src/core/server_state.rs
openraft/src/engine/testing.rs
openraft/src/entry.rs
openraft/src/error.rs
openraft/src/lib.rs
openraft/src/membership/effective_membership.rs
openraft/src/membership/membership.rs
openraft/src/membership/membership_state.rs
openraft/src/metrics/raft_metrics.rs
openraft/src/metrics/replication_metrics.rs
openraft/src/network.rs
openraft/src/node.rs
openraft/src/raft.rs
openraft/src/raft_types.rs
openraft/src/storage.rs
openraft/src/storage_error.rs
openraft/src/versioned/versioned.rs
openraft/src/vote/leader_id.rs
openraft/src/vote/vote.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/342)

Change: Make serde optional

---

openraft/Cargo.toml

---
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/345)

Dep: udpate async-entry to 0.3.1

---

openraft/src/node.rs

---
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/348)

Refactor: simplify NodeId definition

---

openraft/src/engine/log_id_list.rs
openraft/src/engine/log_id_list_test.rs

---
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/353)

Refactor: add LogIdList::extend() to add log ids.

---

openraft/src/lib.rs
openraft/src/raft_state.rs
openraft/src/raft_state_test.rs

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/359)

Refactor: add method RaftState::has_log_id()

---

openraft/src/core/leader_state.rs
openraft/src/core/raft_core.rs
openraft/src/runtime/mod.rs

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/365)

Refactor: generalize Runtime::run_command() to accept any T that is `Into<Entry>`

---

openraft/src/core/append_entries.rs
openraft/src/core/install_snapshot.rs
openraft/src/core/raft_core.rs

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/366)

Refactor: rename update_election_timeout() update_last_heartbeat() to express what exactly they do

---

openraft/src/engine/engine_impl.rs
openraft/src/engine/internal_handle_vote_req_test.rs
openraft/src/engine/mod.rs

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/368)

Test: add test to internal_handle_vote_req()

---

openraft/src/entry.rs
openraft/src/summary.rs

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/369)

Refactor: generalize MessageSummary impl for slice and option

---

openraft/src/core/admin.rs
openraft/src/core/raft_core.rs

- Fix: #390
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/392)

Refactor: skip debug logging of commands at all if possible

---

example-raft-kv/test-cluster.sh

Fix some typos in example-raft-kv/test-cluster.sh
**Checklist**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/315)

Change: fix typos in test-cluster.sh

---

openraft/src/quorum/joint.rs
openraft/src/quorum/joint_impl.rs
openraft/src/quorum/quorum_set_test.rs

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/401)

Refactor: allow building a Joint quorum set from slice or vec

---

Makefile
openraft/src/progress/mod.rs

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/403)

Refactor: Makefile: add bench_cluster_of_[135]

---

openraft/src/membership/membership.rs
openraft/src/quorum/joint.rs
openraft/src/quorum/quorum_set.rs
openraft/src/quorum/quorum_set_impl.rs
openraft/src/quorum/quorum_set_test.rs

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/405)

Refactor: add QuorumSet::ids() to return all ids

---

openraft/src/progress/mod.rs

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/409)

Refactor: simpplify vector building with iter()

---

openraft/src/progress/mod.rs

`upgrade_quorum_set()` when a new quorum-set takes place.
`upgrade_quorum_set()` should re-calculate the committed value.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/423)

Refactor: add trait method `Progress::upgrade_quorum_set()`

---

memstore/Cargo.toml
openraft/Cargo.toml
openraft/tests/append_entries/t10_conflict_with_empty_entries.rs
openraft/tests/append_entries/t20_append_conflicts.rs
openraft/tests/append_entries/t50_append_entries_with_bigger_term.rs
openraft/tests/fixtures/mod.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/430)

CI: publish memstore as openraft-memstore.

---

guide/src/SUMMARY.md
guide/src/upgrade-tips.md

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/431)

Doc: add upgrade tip for v0.6.5 to v0.6.6 upgrade

---

openraft/src/engine/engine_impl.rs
openraft/src/metrics/wait.rs
openraft/src/progress/bench/vec_progress_update.rs
openraft/src/progress/mod.rs
openraft/tests/append_entries/t30_append_inconsistent_log.rs
openraft/tests/snapshot/t40_after_snapshot_add_learner_and_request_a_log.rs

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/444)

Refactor: Progress::update() returns an Result to indicate if the input id exists

---

openraft/src/core/mod.rs

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/455)

Doc: fix link to private types

---

openraft/src/core/raft_core.rs
openraft/src/core/tick.rs
openraft/src/raft.rs
openraft/src/replication/mod.rs

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/459)

Refactor: remove span embedded in tx_api channel. They help little on debug

---

openraft/src/core/mod.rs
openraft/src/core/tick.rs
openraft/src/raft.rs
openraft/tests/membership/t30_step_down.rs

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/482)

Feature: Raft::enable_tick() to enable or disable election timeout

---

openraft/src/core/raft_core.rs

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/490)

Refactor: vote request timeout should be election timeout instead of heartbeat interval

---

memstore/Cargo.toml
openraft/Cargo.toml
openraft/src/store_ext.rs

**Checklist**
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/514)

Refactor: let StoreExt deref to inner storage implementation

---

memstore/src/lib.rs
openraft/src/core/install_snapshot.rs
openraft/src/core/mod.rs
openraft/src/core/replication.rs
openraft/src/raft.rs
openraft/src/replication/mod.rs
openraft/src/types/v070/snapshot.rs
openraft/src/types/v070/state_machine.rs
openraft/tests/api_install_snapshot.rs
openraft/tests/fixtures/mod.rs

**Checklist**
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/516)

Change: SnapshotMeta.last_log_id from LogId to Option of LogId

---

guide/src/SUMMARY.md
guide/src/upgrade-tips.md
guide/src/upgrade-v06-v07.md

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/518)

Doc: add guide for upgrading from 0.6 to 0.7

---

openraft/Cargo.toml

**Checklist**
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/520)

CI: no need to depend on a specific version of memstore

---

README.md

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/523)

Doc: update readme

---

rocksstore/src/lib.rs

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/524)

Refactor: rocksstore: add generalized put/get methods for accessing raft-store metadata

---

.github/actions-rs/grcov.yml
.github/workflows/coverage.yml

Ignore a test that fails when running coverage test
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/530)

CI: add coversalls

---

openraft/src/core/mod.rs
openraft/src/error.rs
openraft/src/raft.rs
openraft/src/replication/mod.rs
openraft/tests/fixtures/mod.rs
openraft/tests/snapshot/main.rs
openraft/tests/snapshot/trigger_snapshot.rs

**Checklist**
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/532)

### Feature: add Raft::trigger_snapshot() to force the leader to send a snapshot

---

README.md

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/533)

Doc: explain status for every version

---

openraft/src/core/raft_core.rs
openraft/src/engine/engine_impl.rs

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/542)

Refactor: simplify server state detection when starting up

---

change-log.md
change-log/v0.6.9.md
memstore/Cargo.toml
openraft/Cargo.toml

Prepare release 0.6.9
**Checklist**
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/545)

Release 0.6.9

---

openraft/src/core/admin.rs
openraft/src/core/mod.rs
openraft/src/error.rs
openraft/src/raft.rs
openraft/tests/membership/main.rs
openraft/tests/membership/t10_add_learner.rs
openraft/tests/membership/t10_remove_learner.rs
openraft/tests/membership/t20_change_membership.rs

**Checklist**
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/547)

Feature: add Raft::remove_learner()

---

.github/workflows/ci.yaml
.mergify.yml

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/548)

CI: simplify actions

---

README.md

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/549)

Doc: add discord channel to readme

---

examples/raft-kv-memstore/Cargo.toml
examples/raft-kv-memstore/src/bin/main.rs
examples/raft-kv-rocksdb/Cargo.toml
examples/raft-kv-rocksdb/src/bin/main.rs
examples/raft-kv-rocksdb/test-cluster.sh
openraft/src/core/raft_core.rs

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/552)

Refactor: example/memstore uses tracing to print log

---

.github/workflows/ci.yaml

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/553)

CI: run test-cluster.sh for examples

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/doc-request.md
README.md
guide/src/SUMMARY.md
guide/src/faq.md
guide/src/heartbeat.md

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/554)

Doc: add faq to guide, add doc-request issue template

---

examples/raft-kv-memstore/src/bin/main.rs
examples/raft-kv-memstore/test-cluster.sh
examples/raft-kv-rocksdb/src/bin/main.rs
examples/raft-kv-rocksdb/test-cluster.sh

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/556)

Test: enable logging target crate and increase log level to "trace" for examples/*/test-cluster.sh

---

guide/src/heartbeat.md

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/557)

Doc: explain why blank-log heartbeat wont affect performance

---

.github/workflows/chaos.yml
.github/workflows/ci.yaml
openraft/tests/fixtures/mod.rs
openraft/tests/membership/t10_add_learner.rs

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/562)

CI: WIP: add workflow triggered chaos-test.

---

.github/workflows/commit-message-check.yml
scripts/build_change_log.py

To make dependabot happy:)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/568)

CI: allow message type: "Build(deps):"

---

openraft/src/core/tick.rs
openraft/src/raft.rs

To enable more lightweight in-process "integration" testing of our raft cluster we intend to start and shutdown many raft nodes. The tick task of each instance was leaking when shut down. This PR is shutting down the tick task as well.
**Checklist**
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/563)

Fix: stop tick task when shutting down Raft

---

Cargo.toml
examples/raft-kv-memstore/Cargo.toml
examples/raft-kv-memstore/src/bin/main.rs
examples/raft-kv-memstore/tests/cluster/test_cluster.rs
examples/raft-kv-rocksdb/Cargo.toml
examples/raft-kv-rocksdb/src/bin/main.rs
examples/raft-kv-rocksdb/tests/cluster/test_cluster.rs
memstore/Cargo.toml
openraft/Cargo.toml
rocksstore/Cargo.toml
sledstore/Cargo.toml

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/576)

Refactor: extends package and dependencies from workspace

---

Makefile
memstore/Cargo.toml
openraft/Cargo.toml
rocksstore/Cargo.toml
sledstore/Cargo.toml

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/577)

Refactor: cleanup dependencies

---

openraft/src/core/raft_core.rs
openraft/src/replication/mod.rs

In future the Engine should inform the replication stream exactly what
logs to replicate, instead of just the last log id.
This way, the replication stream does not need a retry loop to load
entries from `RaftStorage` any more.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/578)

Refactor: split event UpdateReplication into two enum variants

---

Cargo.toml
openraft/Cargo.toml
openraft/src/core/raft_core.rs

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/583)

Refactor: replace `tokio::select!` with `future::select()`

---

Makefile
guide/src/dynamic-membership.md
guide/src/node-lifecycle.md

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/587)

Refactor: add "make guide" to build guide

---

openraft/src/membership/membership.rs
openraft/src/membership/mod.rs
openraft/src/raft.rs

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/591)

Change: rename `IntoOptionNodes` to `IntoNodes`

---

examples/raft-kv-memstore/test-cluster.sh
examples/raft-kv-memstore/tests/cluster/test_cluster.rs

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/599)

Refactor: add example of removing nodes

---

examples/raft-kv-rocksdb/src/store.rs

- Fix: #618
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/619)

Refactor: flush after every write in rocksdb example

---

openraft/src/engine/engine_impl.rs

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/622)

Refactor: add comment explaining install-snapshot

---

openraft/src/engine/engine_impl.rs
openraft/src/progress/mod.rs

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/626)

Refactor: add Progress::try_get()

---

guide/src/SUMMARY.md
guide/src/log-data-layout.md

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/629)

Doc: explain log data layout

---

openraft/src/core/raft_core.rs
openraft/src/engine/engine_impl.rs

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/631)

Refactor: EngineConfig adds field max_payload_entries

---

openraft/src/engine/engine_impl.rs

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/642)

Refactor: remove Engine::push_command, use Engine.output.push_command instead

---

.github/workflows/commit-message-check.yml
openraft/src/log_id_range.rs
openraft/src/progress/inflight.rs
openraft/src/validate/validate.rs
scripts/build_change_log.py
scripts/change-types.yaml

So that when needed, Inflight could assert its state being valid.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/647)

Improve: impl Validate for LogIdRange and Inflight

---

openraft/src/core/install_snapshot.rs
openraft/src/core/raft_core.rs
openraft/src/engine/elect_test.rs
openraft/src/engine/engine_impl.rs
openraft/src/engine/handle_append_entries_req_test.rs
openraft/src/engine/handle_vote_req_test.rs
openraft/src/engine/handle_vote_resp_test.rs
openraft/src/engine/handler/mod.rs
openraft/src/engine/handler/replication_handler.rs
openraft/src/engine/handler/server_state_handler.rs
openraft/src/engine/internal_handle_vote_req_test.rs
openraft/src/engine/leader_append_entries_test.rs
openraft/src/engine/leader_append_membership_test.rs
openraft/tests/append_entries/t20_append_conflicts.rs
openraft/tests/append_entries/t40_append_updates_membership.rs

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/654)

Improve: add ServerStateHandler to deal with server-state changes

---

openraft/src/engine/handle_append_entries_req_test.rs
openraft/src/engine/handler/following_handler.rs
openraft/src/engine/handler/vote_handler.rs

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/665)

Refactor: rename FollowingHandler methods

---

openraft/src/engine/elect_test.rs
openraft/src/engine/handle_append_entries_req_test.rs
openraft/src/engine/handle_vote_req_test.rs
openraft/src/engine/handle_vote_resp_test.rs
openraft/src/engine/handler/following_handler.rs
openraft/src/engine/handler/log_handler.rs
openraft/src/engine/handler/replication_handler.rs
openraft/src/engine/handler/server_state_handler.rs
openraft/src/engine/handler/snapshot_handler.rs
openraft/src/engine/handler/vote_handler.rs
openraft/src/engine/leader_append_entries_test.rs
openraft/src/engine/log_id_list_test.rs
openraft/src/engine/startup_test.rs
openraft/src/membership/membership_state_test.rs
openraft/src/testing/mod.rs

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/674)

Refactor: remove duplicated log_id()

---

examples/raft-kv-rocksdb/Cargo.toml
examples/raft-kv-rocksdb/src/network/raft.rs
examples/raft-kv-rocksdb/src/network/raft_network_impl.rs
examples/raft-kv-rocksdb/src/store.rs
examples/raft-kv-rocksdb/tests/cluster/test_cluster.rs

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/676)

Refactor: add tracing to examples/raft-kv-rocksdb; upgrade rocksdb

---

.github/workflows/ci.yaml

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/678)

Refactor: disable examples/raft-kv-rocksdb CI : #677

---

openraft/src/membership/membership.rs
openraft/src/membership/membership_state.rs
openraft/src/membership/membership_test.rs

`trait IntoNodes` converts types `T` such as `Vec` or `BTreeSet` into
`BTreeMap<NID, Node>`. In this patch it provides two methods
`has_nodes() -> bool` to return `true` if `T` contains any `Node`, e.g.,
a `BTreeMap<NID, N>`, or a `T` that contains only `NodeId`, e.g., a
`BTreeSet<NID>`.
Refactor:
`Membership::next_safe()` now returns `Err(LearnerNotFound)` if it
attempts to build a `Membership` containing a `voter_id` that has no
corresponding `Node`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/683)

Change: trait IntoNodes adds two new method has_nodes() and node_ids()

---

rocksstore/src/lib.rs

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/689)

Refactor: reduce some duplicated codes in rocksstore

---

examples/raft-kv-memstore/src/store/mod.rs
examples/raft-kv-rocksdb/src/store.rs
rocksstore/src/lib.rs
sledstore/src/lib.rs

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/693)

Refactor: remove obsolete TODO

---

Makefile
change-log.md
change-log/v0.6.2-alpha.10.md
change-log/v0.6.2-alpha.16.md
change-log/v0.6.2-alpha.5.md
change-log/v0.6.2-alpha.8.md
change-log/v0.6.2-alpha.md
change-log/v0.8.0.md
examples/raft-kv-memstore/src/client.rs
examples/raft-kv-memstore/src/store/mod.rs
examples/raft-kv-rocksdb/src/client.rs
examples/raft-kv-rocksdb/src/store.rs
guide/src/faq.md
guide/src/getting-started.md
guide/src/upgrade-v07-v08.md
openraft/Cargo.toml
openraft/src/defensive.rs
openraft/src/engine/handler/leader_handler.rs
openraft/src/membership/membership_state.rs
openraft/src/raft.rs
openraft/src/testing/suite.rs
openraft/src/vote/leader_id/leader_id_adv.rs
openraft/src/vote/leader_id/leader_id_std.rs
rocksstore/src/lib.rs
sledstore/src/lib.rs

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/700)

Doc: fix typos

---

openraft/src/storage/mod.rs

- Answer questions mentioned in #702
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/706)

Doc: explain state-machine/append-log etc

---

openraft/src/testing/suite.rs

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/717)

Refactor: replace entry creation with short function call in RaftStorage test suites

---

.github/workflows/ci.yaml

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/719)

CI: fail-fast: false

---

Cargo.toml
Makefile
examples/raft-kv-memstore/Cargo.toml
examples/raft-kv-memstore/src/lib.rs
examples/raft-kv-rocksdb/Cargo.toml
examples/raft-kv-rocksdb/src/lib.rs
examples/raft-kv-rocksdb/src/network/raft_network_impl.rs
examples/raft-kv-rocksdb/src/store.rs
memstore/Cargo.toml
memstore/src/lib.rs
openraft/Cargo.toml
openraft/src/compat/compat07.rs
openraft/src/error.rs
openraft/src/lib.rs
openraft/src/vote/vote.rs
rocksstore-compat07/Cargo.toml
rocksstore-compat07/src/lib.rs
rocksstore/Cargo.toml
rocksstore/src/lib.rs
sledstore/Cargo.toml
sledstore/src/lib.rs
tests/Cargo.toml

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/723)

Refactor: add stricter lint rules: deny: unused_crate_dependencies unused_qualifications

---

Makefile
openraft/Cargo.toml
openraft/src/change_members.rs
openraft/src/config/config.rs
openraft/src/config/error.rs
openraft/src/entry/traits.rs
openraft/src/lib.rs
openraft/src/log_id/log_id_option_ext.rs
openraft/src/log_id/log_index_option_ext.rs
openraft/src/log_id/mod.rs
openraft/src/node.rs
openraft/src/raft_state/membership_state/mod.rs
openraft/src/raft_state/mod.rs
openraft/src/raft_types.rs
openraft/src/storage/helper.rs
openraft/src/testing/mod.rs
openraft/src/try_as_ref.rs
openraft/src/validate/validate.rs

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/727)

Doc: add missing docs for public APIs

---

openraft/src/core/raft_core.rs
openraft/src/engine/elect_test.rs
openraft/src/engine/engine_impl.rs
openraft/src/engine/handle_append_entries_req_test.rs
openraft/src/engine/handle_vote_req_test.rs
openraft/src/engine/handle_vote_resp_test.rs
openraft/src/engine/handler/following_handler/commit_entries_test.rs
openraft/src/engine/handler/following_handler/do_append_entries_test.rs
openraft/src/engine/handler/following_handler/install_snapshot_test.rs
openraft/src/engine/handler/following_handler/mod.rs
openraft/src/engine/handler/following_handler/truncate_logs_test.rs
openraft/src/engine/handler/following_handler/update_committed_membership_test.rs
openraft/src/engine/handler/leader_handler/append_entries_test.rs
openraft/src/engine/handler/leader_handler/mod.rs
openraft/src/engine/handler/leader_handler/send_heartbeat_test.rs
openraft/src/engine/handler/log_handler/calc_purge_upto_test.rs
openraft/src/engine/handler/log_handler/purge_log_test.rs
openraft/src/engine/handler/replication_handler/append_membership_test.rs
openraft/src/engine/handler/replication_handler/update_matching_test.rs
openraft/src/engine/handler/server_state_handler/update_server_state_test.rs
openraft/src/engine/handler/snapshot_handler/update_snapshot_test.rs
openraft/src/engine/handler/vote_handler/handle_message_vote_test.rs
openraft/src/engine/initialize_test.rs
openraft/src/engine/mod.rs
openraft/src/engine/startup_test.rs
openraft/src/engine/testing.rs
openraft/src/lib.rs

- Fix: #728
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/729)

Refactor: add generic parameter "Ent: RaftEntry" to Engine

---

openraft/src/testing/suite.rs

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/732)

Refactor: improve function names in suite.rs

---

Cargo.toml
examples/raft-kv-memstore/src/store/mod.rs
examples/raft-kv-rocksdb/src/store.rs
memstore/src/lib.rs
openraft/src/core/install_snapshot.rs
openraft/src/storage_error.rs
rocksstore-compat07/src/lib.rs
rocksstore/src/lib.rs
sledstore/src/lib.rs

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/738)

Feature: add methods to StorageIOError to simplify error creation

---

openraft/src/engine/engine_config.rs
openraft/src/engine/engine_impl.rs
openraft/src/engine/engine_output.rs
openraft/src/engine/handler/following_handler/mod.rs
openraft/src/engine/handler/leader_handler/mod.rs
openraft/src/engine/handler/log_handler/mod.rs
openraft/src/engine/handler/replication_handler/mod.rs
openraft/src/engine/handler/server_state_handler/mod.rs
openraft/src/engine/handler/snapshot_handler/mod.rs
openraft/src/engine/handler/vote_handler/mod.rs
openraft/src/engine/mod.rs
openraft/src/raft.rs
openraft/src/replication/replication_session_id.rs

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/744)

Chore: clean up comments

---

openraft/src/engine/handler/following_handler/commit_entries_test.rs
openraft/src/engine/handler/following_handler/mod.rs

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/745)

Refactor: simplify FollowerHandler::commit_entries()

---

change-log.md
change-log/v0.7.6.md

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/754)

Doc: update change-log for 0.7.6

---

README.md

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/755)

Chore: update README: latest versions for 0.7 and 0.8

---

openraft/src/core/install_snapshot.rs
openraft/src/core/raft_core.rs
openraft/src/core/snapshot_state.rs
openraft/src/core/streaming_state.rs

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/756)

Refactor: remove unnecessary type param from `Streaming`

---

openraft/src/core/raft_core.rs
openraft/src/engine/command.rs
openraft/src/engine/engine_impl.rs
openraft/src/engine/handler/following_handler/do_append_entries_test.rs
openraft/src/engine/handler/following_handler/install_snapshot_test.rs
openraft/src/engine/handler/following_handler/mod.rs
openraft/src/engine/handler/following_handler/truncate_logs_test.rs
openraft/src/engine/handler/following_handler/update_committed_membership_test.rs
openraft/src/engine/handler/leader_handler/append_entries_test.rs
openraft/src/engine/handler/replication_handler/append_membership_test.rs
openraft/src/engine/handler/replication_handler/mod.rs
openraft/src/engine/tests/append_entries_test.rs
openraft/src/engine/tests/command_test.rs
openraft/src/engine/tests/initialize_test.rs

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/758)

Chore: remove unused Command::UpdateMembership

---

openraft/src/core/raft_core.rs

To deal with command with callback in future, `run_engine_commands()`
can not be called in a handler method. Instead, it should only be called
in the RaftCore main loop.
In this commit it refactors `handle_check_is_leader_request` by moving
logic into another tokio task, and responses are sent to RaftCore via
`RaftCore.tx_api`. In this way, only RaftCore main loop needs to run
command.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/760)

Refactor: move `run_engine_commands()` out of `RaftCore::handle_check_is_leader_request()`

---

.github/workflows/ci.yaml

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/765)

CI: upload artifacts with specified names

---

openraft/src/raft.rs

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/766)

Chore: add logging to change-membership

---

memstore/src/lib.rs
openraft/src/config/config.rs
openraft/src/core/raft_core.rs
openraft/src/progress/entry.rs
openraft/src/raft_state/log_state_reader.rs
openraft/src/raft_state/mod.rs
tests/tests/snapshot/t20_startup_snapshot.rs

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/770)

Refactor: add should_snapshot() to SnapshotPolicy

---

openraft/src/core/raft_core.rs
openraft/src/core/sm/command.rs
openraft/src/core/sm/mod.rs
openraft/src/engine/command.rs

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/774)

Refactor:  add condition StateMachineCommand for waiting for a sm::Command to complete

---

openraft/src/raft.rs

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/780)

Fix: debug level check

---

openraft/src/core/raft_core.rs
openraft/src/error.rs

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/783)

Refactor: use `select!` to simplify multiple channels receiving

---

guide/src/getting-started.md
scripts/build_change_log.py

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/793)

Doc: update getting-started to incorporate latest changes

---

guide/src/getting-started.md
guide/src/upgrade-v07-v08.md
openraft/src/core/raft_core.rs
openraft/src/engine/engine_impl.rs
openraft/src/engine/handler/vote_handler/handle_message_vote_test.rs
openraft/src/engine/handler/vote_handler/mod.rs

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/800)

Doc: add Snapshot to guide/

---

openraft/src/core/raft_core.rs
openraft/src/core/sm/command.rs
openraft/src/core/sm/mod.rs
openraft/src/engine/command.rs
openraft/src/engine/handler/following_handler/install_snapshot_test.rs
openraft/src/engine/handler/following_handler/mod.rs
openraft/src/engine/handler/snapshot_handler/mod.rs
openraft/src/engine/handler/snapshot_handler/trigger_snapshot_test.rs
openraft/src/raft.rs

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/801)

Refactor: collect state-machine command into Command::StateMachine{}

---

openraft/src/engine/handler/following_handler/mod.rs
openraft/src/engine/handler/following_handler/receive_snapshot_chunk_test.rs
openraft/src/lib.rs
openraft/src/raft_state/mod.rs

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/807)

Refactor: add test for FollowingHandler::receive_snapshot_chunk

---

memstore/src/lib.rs
openraft/src/core/raft_core.rs
openraft/src/metrics/raft_metrics.rs
openraft/src/metrics/wait_test.rs
openraft/src/progress/entry/tests.rs
openraft/src/raft_state/io_state.rs
openraft/src/raft_state/log_state_reader.rs
openraft/src/raft_state/mod.rs
openraft/src/storage/helper.rs
tests/tests/metrics/main.rs
tests/tests/metrics/t10_purged.rs

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/809)

Feature: add RaftMetrics::purged to report the last purged log id

---

openraft/src/metrics/wait.rs
openraft/src/metrics/wait_test.rs

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/810)

Feature: add Wait::purged() to wait for purged to become the expected

---

Cargo.toml
examples/raft-kv-memstore/Cargo.toml
examples/raft-kv-rocksdb/Cargo.toml
openraft/src/config/config.rs
openraft/src/error.rs

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/818)

Dep: upgrade clap to 4.1.11

---

.github/workflows/gtp-translate.yml

Usage:
Add a comment to an issue with the following content.
A pull request will be created when the refinement is finished.
```
/gpt-translate <src-fn>.md     <output-fn>.md     <language>
E.g.:
/gpt-translate openraft/src/docs/cluster_control/node-lifecycle.md     openraft/src/docs/cluster_control/node-lifecycle.md     English
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/829)

CI: use gpt to refine docs: drmingdrmer/gpt-refine-md

---

memstore/Cargo.toml
memstore/src/test.rs
openraft/src/docs/getting_started/getting-started.md
openraft/src/testing/store_builder.rs
rocksstore/src/test.rs

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/830)

Doc: remove insignificant part from getting-started.md

---

.github/ISSUE_TEMPLATE/bug_report.md

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/835)

Doc: issue template: ask for version with the bug

---

openraft/src/core/raft_core.rs

RaftCore::handl_notify() should not be async
RaftCore::handle_check_is_leader_request() does not return error;
RaftCore::handle_api_msg() does not return error;
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/837)

Chore: remove unused async and return error

---

openraft/src/core/sm/mod.rs
openraft/src/storage/mod.rs

close #836
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/842)

Refactor : replace openraft::core::sm::Received with openraft::storage::Snapshot

---

openraft/src/engine/engine_impl.rs
openraft/src/engine/handler/vote_handler/mod.rs
openraft/src/engine/tests/elect_test.rs
openraft/src/engine/tests/handle_vote_resp_test.rs
openraft/src/internal_server_state.rs
openraft/src/leader/leader.rs
openraft/src/leader/mod.rs
openraft/src/leader/voting.rs
openraft/src/progress/mod.rs
openraft/src/utime.rs

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/844)

Refactor: move voting state into a new struct Voting

---

openraft/src/core/notify.rs
openraft/src/core/raft_core.rs
openraft/src/engine/engine_impl.rs
openraft/src/engine/handler/vote_handler/mod.rs
openraft/src/leader/leader.rs
openraft/src/leader/voting.rs

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/845)

Chore: add field last_log_id to Voting

---

openraft/src/storage/mod.rs

Doc: remove deprecated document reference
The link https://datafuselabs.github.io/openraft/storage.html no longer exists, and I can't find a similar document. I think it's OK to remove this part of the comment.
**Checklist**
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/849)

Doc: remove deprecated document reference

---

openraft/src/storage_error.rs

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/877)

Refactor: impl Display and Copy for ErrorVerb

---

openraft/src/engine/handler/following_handler/append_entries_test.rs
openraft/src/engine/handler/following_handler/commit_entries_test.rs
openraft/src/engine/handler/following_handler/do_append_entries_test.rs
openraft/src/engine/handler/following_handler/install_snapshot_test.rs
openraft/src/engine/handler/following_handler/receive_snapshot_chunk_test.rs
openraft/src/engine/handler/following_handler/truncate_logs_test.rs
openraft/src/engine/handler/following_handler/update_committed_membership_test.rs
openraft/src/engine/handler/leader_handler/append_entries_test.rs
openraft/src/engine/handler/leader_handler/send_heartbeat_test.rs
openraft/src/engine/handler/log_handler/purge_log_test.rs
openraft/src/engine/handler/replication_handler/append_membership_test.rs
openraft/src/engine/handler/replication_handler/update_matching_test.rs
openraft/src/engine/handler/server_state_handler/update_server_state_test.rs
openraft/src/engine/handler/snapshot_handler/update_snapshot_test.rs
openraft/src/engine/handler/vote_handler/accept_vote_test.rs
openraft/src/engine/handler/vote_handler/handle_message_vote_test.rs
openraft/src/engine/tests/append_entries_test.rs
openraft/src/engine/tests/elect_test.rs
openraft/src/engine/tests/handle_vote_req_test.rs
openraft/src/engine/tests/handle_vote_resp_test.rs
openraft/src/engine/tests/initialize_test.rs
openraft/src/engine/tests/log_id_list_test.rs
openraft/src/engine/tests/startup_test.rs
openraft/src/raft_state/membership_state/change_handler_test.rs
openraft/src/raft_state/membership_state/membership_state_test.rs
openraft/src/testing/mod.rs
tests/tests/append_entries/t61_heartbeat_reject_vote.rs

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/891)

Chore: replace log_id1() with log_id() for tests

---

.github/workflows/ci.yaml

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/901)

Chore: cleanup CI script

---

Cargo.toml
openraft/Cargo.toml
openraft/src/docs/feature_flags/feature-flags.md

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/908)

Feature: add feature flag "tracing-log" to emit log record for tracing event

---

openraft/src/docs/faq/faq.md

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/929)

Doc: add faq: "What will happen when data gets lost"

---

README.md

**Checklist**
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/932)

Doc: add License link

---

README.md

**Checklist**
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/933)

Doc: add a space

---

openraft/src/network/rpc_type.rs
tests/tests/append_entries/t11_append_inconsistent_log.rs
tests/tests/append_entries/t30_replication_1_voter_to_isolated_learner.rs
tests/tests/client_api/t11_client_reads.rs
tests/tests/fixtures/mod.rs
tests/tests/membership/t11_add_learner.rs
tests/tests/membership/t30_commit_joint_config.rs
tests/tests/membership/t30_elect_with_new_config.rs
tests/tests/membership/t51_remove_unreachable_follower.rs
tests/tests/replication/t50_append_entries_backoff.rs
tests/tests/snapshot_streaming/t30_purge_in_snapshot_logs.rs
tests/tests/snapshot_streaming/t34_replication_does_not_block_purge.rs
tests/tests/snapshot_streaming/t50_snapshot_line_rate_to_snapshot.rs
tests/tests/snapshot_streaming/t90_issue_808_snapshot_to_unreachable_node_should_not_block.rs

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/946)

Refactor: rpc error simulation in tests/

---

tests/tests/fixtures/mod.rs
tests/tests/replication/t50_append_entries_backoff.rs

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/948)

Refactor: testing fixture: add RPC pre-hook to let user define what to do before sending an RPC

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/953)

readme: fix dead link

---

openraft/src/docs/faq/faq.md

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/971)

Doc: faq: how to initalize a cluster

---

examples/raft-kv-memstore/Cargo.toml
examples/raft-kv-memstore/src/app.rs
examples/raft-kv-memstore/src/lib.rs
examples/raft-kv-memstore/src/network/api.rs
examples/raft-kv-memstore/src/store/mod.rs
openraft/src/storage/v2.rs

**Checklist**
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/977)

Refactor: update `raft-kv-memstore` example to use storage v2

---

openraft/src/docs/data/leader_id.md
openraft/src/docs/data/vote.md
openraft/src/docs/feature_flags/feature-flags.md

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/988)

Doc: explain LeaderId: partial order or total order

---

.github/workflows/commit-message-check.yml
scripts/build_change_log.py
tests/tests/metrics/t10_server_metrics_and_data_metrics.rs

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/997)

CI: add commit message type `Perf:`

---

examples/raft-kv-memstore-singlethreaded/Cargo.toml
examples/raft-kv-memstore/Cargo.toml
examples/raft-kv-rocksdb/Cargo.toml
examples/raft-kv-rocksdb/src/app.rs
examples/raft-kv-rocksdb/src/bin/main.rs
examples/raft-kv-rocksdb/src/lib.rs
examples/raft-kv-rocksdb/src/network/management.rs
examples/raft-kv-rocksdb/src/store.rs
examples/raft-kv-rocksdb/tests/cluster/test_cluster.rs

**Checklist**
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/998)

Refactor: delete async-trait, fix typo, use tokio to replace async_std

---

openraft/src/replication/mod.rs
openraft/src/replication/request.rs

Prior to this commit, the `ReplicationCore` being awakened without any
specific action in `ReplicationCore.next_action` implied a heartbeat was
to be sent. This approach was cryptic and the intent behind the action
was not clear.
In this commit, we have introduced explicitness to the process: if
`ReplicationCore` is intended to send a heartbeat, a distinct
`Data::Heartbeat` variant is now stored in `next_action`.
This change ensures clarity by explicitly representing heartbeat
actions, removing any ambiguity from the replication logic.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/1004)

Refactor: Explicitly store Heartbeat action

---

openraft/src/raft/mod.rs
openraft/src/raft/raft_inner.rs

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/1006)

Refactor: call_core() should be a method of RaftInner instead of a method of Raft

---

README.md

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/1017)

Doc: add contributors section to README

---

openraft/src/docs/getting_started/getting-started.md
openraft/src/storage/mod.rs
openraft/src/testing/suite.rs

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/1019)

Refactor: if `storage-v2` enabled, deprecated `RaftStorage`

---

examples/raft-kv-memstore-opendal-snapshot-data/Cargo.toml
examples/raft-kv-memstore-opendal-snapshot-data/src/lib.rs
examples/raft-kv-memstore-opendal-snapshot-data/src/store.rs

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/1027)

Refactor: opendal example reuse memstore::LogStore

---

openraft/src/docs/faq/faq.md

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/1032)

Doc: fix typo in faq: n0 should be n1

---

openraft/src/network/snapshot_transport.rs
openraft/src/raft/mod.rs

Since this commit, an application can just call
`Chunked::receive_snapshot()` to implement a default chunk based
snapshot receiving.
Example usage:
```ignore
struct App<C> {
raft: Raft<C>
streaming: Option<Streaming<C>>,
// ...
}
impl<C> App<C> {
fn handle_install_snapshot_request(&mut self, req: InstallSnapshotRequest<C>) -> Result<_, _> {
let res = Chunked::receive_snapshot(&mut self.streaming, &self.raft, req).await?;
if let Some(snapshot) = res {
self.raft.install_snapshot(snapshot).await?;
}
}
}
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/1039)

Refactor: `Chunked::receive_snapshot()` fully implements chunk-based snapshot receving

---

scripts/build_change_log.py

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/1040)

Chore: fix build_change_log.py: yaml.safe_load()

---

change-log.md
change-log/v0.9.0.md
openraft/src/docs/docs.md
openraft/src/docs/upgrade_guide/mod.rs
openraft/src/docs/upgrade_guide/upgrade-v08-v09.md
openraft/src/docs/upgrade_guide/upgrade.md

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/1043)

Doc: add upgrade-guide from 0.8 to 0.9

---

openraft/src/engine/handler/vote_handler/mod.rs
openraft/src/internal_server_state.rs

closed #882 
**Checklist**
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/1044)

Chore: Moving Leading into Box

---

openraft/src/async_runtime.rs
openraft/src/entry/mod.rs
openraft/src/instant.rs
openraft/src/lib.rs
openraft/src/testing/mod.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/1049)

Doc: Add doc to pub sub-mod

---

openraft/src/async_runtime.rs
openraft/src/config/config.rs
openraft/src/entry/mod.rs
openraft/src/instant.rs
openraft/src/lib.rs
openraft/src/membership/into_nodes.rs
openraft/src/membership/membership.rs
openraft/src/raft/mod.rs
openraft/src/raft/trigger.rs
openraft/src/testing/mod.rs

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/1050)

Change: remove deprecated methods from Raft

---

README.md

**Checklist**
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/1054)

Doc: Add `helyim` to user list

---

README.md

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/1055)

Doc: README: check FAQ first

---

openraft/src/membership/effective_membership.rs

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/1069)

Chore: Remove unused `From<&Ent> for EffectiveMembership`

---

openraft/src/engine/handler/replication_handler/mod.rs
openraft/src/progress/entry/mod.rs

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/1085)

chore: add tracing and comment

---

examples/raft-kv-memstore-generic-snapshot-data/README.md
examples/raft-kv-memstore-opendal-snapshot-data/README.md
examples/raft-kv-memstore-singlethreaded/README.md

There is a small typo made in the `examples` for running the `cargo test` suite. `--nocaputre` is not a valid option, here's a simple fix :rocket: 
**Checklist**
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/1089)

Doc: fix typo in example `README.md` files

---

openraft/src/error.rs

Easing client implementation
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/1088)

Feature: Implement TryAsRef<ForwardToLeader<..>> for RaftError

---

openraft/src/raft/mod.rs
tests/tests/client_api/t10_client_writes.rs

`Raft<C>::client_write_ff() -> C::Responder::Receiver` submit a client
request to Raft to update the state machine, returns an application
defined response receiver `Responder::Receiver` to receive the response.
`_ff` means fire and forget.
It is same as [`Raft::client_write`] but does not wait for the response.
When using this method, it is the application's responsibility for
defining mechanism building and consuming the `Responder::Receiver`.
- Part of #1068
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/1095)

Feature: `Raft::client_write_ff()` ff for fire-and-forget

---

openraft/src/docs/faq/faq-toc.md
openraft/src/docs/faq/faq.md
openraft/src/engine/engine_impl.rs

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/1100)

Doc: Add FAQ: store additional info in Node

---

openraft/src/engine/handler/snapshot_handler/mod.rs

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/1111)

Chore: adjust log level for snapshot trigger

---

Makefile
README.md
examples/memstore/src/log_store.rs
macros/src/lib.rs
macros/tests/since/expand/with_doc.expanded.rs
macros/tests/since/expand/with_doc.rs
openraft/src/docs/faq/faq.md
openraft/src/docs/upgrade_guide/upgrade-v08-v09.md
openraft/src/engine/handler/replication_handler/append_membership_test.rs
scripts/README.md
scripts/build_change_log.py
tests/tests/membership/t99_new_leader_auto_commit_uniform_config.rs
tests/tests/replication/t10_append_entries_partial_success.rs

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/1112)

Chore: fix typos

---

openraft/src/core/raft_core.rs
openraft/src/core/sm/worker.rs
openraft/src/docs/components/mod.rs
openraft/src/docs/components/state-machine.md
openraft/src/docs/docs.md
openraft/src/docs/mod.rs
openraft/src/storage/v2.rs
openraft/src/testing/suite.rs

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/1123)

Doc: Add docs::components::state_machine

---

examples/raft-kv-memstore/src/client.rs
examples/raft-kv-memstore/src/network/management.rs
examples/raft-kv-memstore/test-cluster.sh

Add a multi-nodes cluster initialization example in raft-kv-memstore.
**Checklist**
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/1133)

Example: add initialize multi nodes cluster for raft-kv-memstore

---

openraft/src/docs/cluster_control/dynamic-membership.md
openraft/src/docs/getting_started/getting-started.md
openraft/src/network/v1/network.rs
openraft/src/network/v2/network.rs

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/1134)

Doc: ensure connection to the correct node

---

openraft/src/engine/handler/replication_handler/append_membership_test.rs

There is no need to execute `eng.state.server_state = ServerState::Leader` and `eng.state.vote = UTime::new(TokioInstant::now(), Vote::new_committed(2, 2))` since the eng has already done so. 
**Checklist**
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/1136)

Refactor: remove some duplicated code in append_memvership_test.rs

---

openraft/src/config/config.rs
openraft/src/engine/command.rs
openraft/src/engine/handler/replication_handler/mod.rs
openraft/src/log_id_range.rs
openraft/src/progress/entry/mod.rs
openraft/src/progress/entry/tests.rs
openraft/src/progress/inflight/mod.rs
openraft/src/progress/inflight/tests.rs
openraft/src/raft_state/accepted.rs
openraft/src/raft_state/log_state_reader.rs
openraft/src/raft_state/mod.rs
openraft/src/raft_state/tests/accepted_test.rs
openraft/src/replication/mod.rs
openraft/src/replication/request.rs

LogIdRange
Inflight
LogStateReader
Accepted
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/1150)

Refactor: use RaftTypeConfig to replace NID

---

openraft/src/core/raft_core.rs
openraft/src/lib.rs
openraft/src/metrics/wait.rs
openraft/src/metrics/wait_test.rs
openraft/src/raft/mod.rs
openraft/src/raft/raft_inner.rs
openraft/src/type_config.rs
openraft/src/type_config/async_runtime/impls/tokio_runtime.rs
openraft/src/type_config/async_runtime/mod.rs
openraft/src/type_config/async_runtime/watch/mod.rs
openraft/src/type_config/async_runtime/watch/watch_error.rs
openraft/src/type_config/util.rs

**Checklist**
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/1167)

Refactor: Abstract the watch channel into a traits

---

cluster_benchmark/README.md

Fixes a copy issue in the cluster benchmark readme
**Checklist**
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/1160)

Fix cluster benchmark README.md

---

openraft/src/core/balancer.rs
openraft/src/core/mod.rs
openraft/src/core/notification.rs
openraft/src/core/raft_core.rs
openraft/src/core/sm/worker.rs
openraft/src/core/tick.rs
openraft/src/raft/mod.rs
openraft/src/replication/mod.rs
openraft/src/storage/callback.rs
openraft/src/storage/v2/raft_log_storage_ext.rs
openraft/src/testing/suite.rs

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/1172)

Refactor: rename notify to notification

---

openraft/src/docs/protocol/log_replication.md
openraft/src/progress/entry/mod.rs

- Fix: #124
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/1183)

Doc: add algorithm AppendEntries uses to local last matching log id

---

openraft/src/raft/mod.rs

Update the doc of `Raft::external_request()`. The interface was changed in #941.
**Checklist**
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/1205)

Doc: update doc of Raft::external_request()

---

openraft/src/core/raft_core.rs

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/1222)

Refactor: ignore notification for Leader/Candidate when node is in such state

---

openraft/src/raft/message/transfer_leader.rs
openraft/src/raft/mod.rs
tests/tests/fixtures/mod.rs

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/1226)

Refactor: refine method names for `TransferLeaderRequest`

---

openraft/src/raft_state/io_state.rs

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/datafuselabs/openraft/1229)

Refactor: Snapshot with same last log id can be installed

---

README.md

RobustMQ also uses OpenRaft to build clusters, which we hope will add to this use case.Thank you. please evaluate whether it is appropriate. 
Thank you very much.
**Checklist**
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/openraft/1253)

Doc: Add use case, RobustMQ

---

openraft/src/testing/log/suite.rs

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/openraft/1262)

Test: split storage test get_initial_state_membership_from_log_and_sm() into 3 sub tests

---

openraft/src/docs/getting_started/getting-started.md

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/openraft/1263)

Doc: update getting-started

---

examples/raft-kv-memstore-grpc/test-cluster.sh

5051 is node-1 and 5052 is node-2
**Checklist**
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/openraft/1280)

chore: typo in grpc test-cluster.sh

---

examples/rocksstore/src/test.rs

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/openraft/1288)

Chore: remove outdated comment

---

openraft/src/lib.rs

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/openraft/1303)

Chore: use OptionalFeatures for AppData and AppDataResponse

---

openraft/src/entry/traits.rs

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/openraft/1305)

Chore: use OptionalFeatures for RaftEntry

---

openraft/src/raft/mod.rs
openraft/src/type_config.rs

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/openraft/1310)

Chore: add alias, formalize RaftTypeConfig doc example

---

openraft/src/engine/handler/following_handler/mod.rs
openraft/src/progress/entry/mod.rs
openraft/src/progress/entry/update.rs
openraft/src/raft_state/io_state/log_io_id.rs
openraft/src/raft_state/tests/validate_test.rs
openraft/src/replication/response.rs

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/openraft/1313)

Chore: minor code refinements

---

openraft/src/core/raft_core.rs
openraft/src/engine/handler/snapshot_handler/mod.rs
openraft/src/engine/handler/vote_handler/mod.rs
openraft/src/engine/testing.rs
openraft/src/log_id_range.rs
openraft/src/summary.rs
openraft/src/testing/common.rs

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/openraft/1315)

Chore: adjust code format

---

.github/workflows/chaos.yml
.github/workflows/ci.yaml
.github/workflows/coverage.yml

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/openraft/1319)

CI: upgrade upload-artifact to v4

---

examples/raft-kv-memstore-grpc/test-cluster.sh

Quick fix for the grpc example to match the proto files. Verified by running locally.
**Checklist**
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/openraft/1328)

Fix grpc example

---

openraft/src/storage/v2/raft_log_reader.rs

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/openraft/1335)

Doc: refine doc for RaftLogReader::try_get_log_entries()

---

openraft/src/docs/getting_started/getting-started.md

Small PR - Commit 95b73cd0bcef96bb32599858a5e4f43d545a2a89 moved the RocksStore test file. This PR adjusts sources to changes.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/openraft/1332)

Doc: Update RocksStore test reference

---

.github/workflows/commit-message-check.yml
scripts/build_change_log.py

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/openraft/1339)

ci: add several common git message type

---

openraft/src/core/mod.rs
openraft/src/core/raft_core.rs
openraft/src/core/sm/command.rs
openraft/src/core/sm/worker.rs

fix issue https://github.com/databendlabs/openraft/issues/1156 response apply results to client in statemachine worker thread
**Checklist**
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/openraft/1334)

Refactor: response apply results to client in statemachine worker thread

---

.github/workflows/ci.yaml

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/openraft/1345)

ci: add missing test for crate macros

---

raft-essentials.md

correct a typo in the raft-essentials.md
**Checklist**
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/openraft/1354)

doc: correct a typo in the raft-essentials.md

---

examples/raft-kv-memstore-grpc/tests/test_cluster.rs
examples/rocksstore/src/lib.rs
macros/src/lib.rs
openraft/src/core/tick.rs
openraft/src/lib.rs
openraft/src/network/snapshot_transport.rs
openraft/src/testing/log/suite.rs
openraft/src/testing/runtime/mod.rs
stores/memstore/src/lib.rs
tests/tests/append_entries/main.rs
tests/tests/client_api/main.rs
tests/tests/fixtures/mod.rs
tests/tests/life_cycle/main.rs
tests/tests/log_store/main.rs
tests/tests/membership/main.rs
tests/tests/metrics/main.rs
tests/tests/replication/main.rs
tests/tests/snapshot_building/main.rs
tests/tests/snapshot_streaming/main.rs

This pr adds the `#allow[(clippy::uninlined_format_args)]` in the `lib.rs` and modifies `last()` to `next_back()`. 
FYI: https://rust-lang.github.io/rust-clippy/master/index.html#double_ended_iterator_last
**Checklist**
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/openraft/1359)

CI: make clippy happy

---

openraft/src/docs/components/state-machine.md
openraft/src/docs/data/log_pointers.md
openraft/src/docs/feature_flags/feature-flags.md
openraft/src/docs/getting_started/getting-started.md
openraft/src/docs/internal/architecture.md
openraft/src/docs/internal/threading.md
openraft/src/docs/protocol/log_replication.md
openraft/src/docs/protocol/snapshot_replication.md
openraft/src/docs/upgrade_guide/upgrade-v08-v09.md

This pr includes three modifications:
1. Fix indentation in some docs, like `log_pointers.md` and `snapshot_replication.md`.
2. Remove some unused link definitions (e.g., `Adapter` in `architecture.md`)
3. Update some stale or incorrect link definitions (e.g., `RaftNetwork::full_snapshot` to `RaftNetworkV2::full_snapshot`).
**Checklist**
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/openraft/1358)

doc: remove some unused links in relevant docs

---

.github/workflows/commit-message-check.yml
openraft/src/raft/mod.rs

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/openraft/1366)

chore: refactor doc for Raft::get_read_log_id

---

openraft/src/core/raft_core.rs
openraft/src/docs/docs.md
openraft/src/docs/protocol/read.md
openraft/src/raft/impl_raft_blocking_write.rs
openraft/src/raft/linearizable_read/linearize_state.rs
openraft/src/raft/linearizable_read/linearizer.rs
openraft/src/raft/linearizable_read/mod.rs

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/openraft/1372)

chore: fix docs

---

openraft/src/docs/protocol/read.md
openraft/src/raft/linearizable_read/linearize_state.rs
openraft/src/raft/linearizable_read/linearizer.rs
openraft/src/raft/mod.rs

Upgrade tip:
Rename calling to `await_applied` to `try_await_ready`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/openraft/1373)

change: rename `await_applied` to `try_await_ready`; add `await_ready`

---

examples/raft-kv-memstore-network-v2/src/api.rs
examples/raft-kv-memstore-opendal-snapshot-data/src/api.rs
examples/raft-kv-memstore-singlethreaded/src/api.rs
examples/raft-kv-memstore/src/network/api.rs
examples/raft-kv-rocksdb/src/network/api.rs
openraft/src/core/raft_core.rs
openraft/src/raft/linearizable_read/linearize_state.rs
openraft/src/raft/linearizable_read/linearizer.rs
openraft/src/raft/mod.rs
tests/tests/client_api/t11_client_reads.rs
tests/tests/fixtures/mod.rs

**Checklist**
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/openraft/1370)

feat: add wait_apply to app api

---

tests/tests/life_cycle/main.rs
tests/tests/life_cycle/t50_leader_restart_clears_state.rs

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/openraft/1386)

Test: leader state reversion upon restart

---

rt-compio/src/lib.rs

- **fix: compio made `Elapsed` unconstructible**
`Elapsed` was changed to non-instantiable outside compio in a [recent PR](https://github.com/compio-rs/compio/pull/466). This PR fixes that by providing our own `Elapsed` instead.
**Checklist**
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/openraft/1406)

fix: compio made `Elapsed` unconstructible

---

openraft/src/core/raft_core.rs
openraft/src/engine/engine_config.rs
openraft/src/engine/handler/following_handler/mod.rs
openraft/src/engine/handler/replication_handler/mod.rs

---
- Improvement
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/databendlabs/openraft/1414)

refactor: move snapshot triggering out of Engine
